### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#1]
Wir brauchen Tests - obviously.
Denke als Input sind die textArrays der geparsten PDFs genug - da kann man dann sensible Daten ersetzen und die Files commiten

Hat jemand empfehlungen bezüglich testing frameworks?

**Comment by d-a-n** [comment]
Habe für DKB Jest Tests https://github.com/codeofsumit/tresor-import/pull/13 erstellt. Schau mal ob du damit leben kannst 😉

**Comment by codeofsumit** [comment]
Jest is subbr - continue 👍

**Comment by bauerj** [comment]
Ich glaube du kannst hier zu machen.
