### ISSUE TITLE
Test and limit dates

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#101]
I had multiple occasions now where users portfolios crashed because they had activities with dates like `0031-06-01`.
I will check against this on API level and on the frontend but I also think we should add tests and checks in the import so dates earlier than the 90s are not accepted and fail the parsing of the PDF.

What do you think?

**Comment by dredav** [comment]
This is a good idea. We can add also further checks to prevent negativ values and centralize the isActivityValid logic.

**Comment by codeofsumit** [comment]
> This is a good idea. We can add also further checks to prevent negativ values and centralize the isActivityValid logic. 

I agree 👏
