### ISSUE TITLE
[dkb] Unneccessary Files in DKB test

### ISSUE THREAD

**Issue by SirGibihm** [codeofsumit/tresor-import#104]
Duplicate files exist at ```tests/brokers/__mocks__/dkb/``` i. e. the file ```buy.json```is equal to the file ```buy-1.json```. Same for ```div.json``` and ```sell.json```. I will remediate the issue in an upcoming pull request for the ebase parser I am working on.

**Comment by dredav** [comment]
Good catch! Thanks for resolving.
Personally I prefer a good structure of all the test data within a broker like here [tests/brokers/__mocks__/traderepublic](https://github.com/codeofsumit/tresor-import/tree/master/tests/brokers/__mocks__/traderepublic) or [tests/brokers/__mocks__/comdirect](https://github.com/codeofsumit/tresor-import/tree/master/tests/brokers/__mocks__/comdirect). This will be a small but good refactoring test I think.

**Comment by SirGibihm** [comment]
With that you mean removing the double underscore? If so, I will also handle that in my fork.

**Comment by dredav** [comment]
No. Personally I prefer to move the mock files (e.g. `buy-1.json`) into a sub folder (e.g. `buy`) and rename the file itself like `limit_order_financial_transaction_tax.json`.
It makes it easier to understand which information is inside the mock file.

**Comment by dredav** [comment]
Fixed with #167
