### ISSUE TITLE
[ebase] Support for importing ebase transactions

### ISSUE THREAD

**Issue by SirGibihm** [codeofsumit/tresor-import#105]
### eBase Umsatzaufstellung import
ATM documents coming from the online depot ebase can't be importet automatically. It is not possible to receive individual receipts for every transcation (I only have saving plans my dataset is incomplete). It is however possible to download summarized transaction histories as PDF and as CSV. The PDFs are missing all tax/factorage/fee information and just have these costs integrated into the price of the traded bond.  

**PDF**
The following is a censored screenshot of the PDF file. If you require a csv file, i can provide it to you; just mention me.
<img width="1371" alt="Screenshot 2020-09-08 at 16 35 09" src="https://user-images.githubusercontent.com/61882185/92491006-f9e26e80-f1f1-11ea-91a7-922292f740d3.png">

### State of the Development
I allready started developing the parser. You can find it in my [Github Fork](https://github.com/SirGibihm/tresor-import). I plan to create a pull request soon. Maybe this will be delayed a bit by me also coding the CSV importer.  
**I am unsure whether my code suffices for creating a pull request, as i could only test with my limited dataset; please advice on what you require my code to do.**

### eBase different transaction types
The following transaction types are in German as I only have access to those. For JSON examples see the github link above.
* Wiederanlage Fondsertrag - BUY (Fond hat ausgeschüttet aber direkt reinvestiert)
* Ansparplan - BUY (Automatischer Sparplan)
* Entgelt Verkauf - SELL
* Vorabpauschale - Half empty field, unknown purpose. It is not known whether this field is always empty. Empty columns are:
  * Anteile (Shares)
  * Kurs/Kursdatum (Price, Date)
  * Devisenkurs (empty in all other transactions as well)
  * Betrag (Amount)
* Fondsertrag (Ausschüttung) - Empty, see *Vorabpauschale*. Occurs together with *Wiederanlage Fondsertrag*. It is not known whether the field is always empty.

**Comment by dredav** [comment]
>I am unsure whether my code suffices for creating a pull request, as i could only test with my limited dataset; please advice on what you require my code to do.

I think you can create a pull-request when you are done with "your part". If we need more test data we can add it to the pull-request or after a merge, to a new one. Currently we have some pull requests which are waiting for more different test data like Erste Bank, scalable.capital, 1822direkt
