### ISSUE TITLE
Portfolio Performance CSV Bug at WKN

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#107]
In some occassions, the WKN field is stored like this `"884437 "` which will return no results from the Tresor One search. It should be stored like this: `884437`.

Example data
```
Datum;Typ;Wert;Buchungswährung;Bruttobetrag;Währung Bruttobetrag;Wechselkurs;Gebühren;Steuern;Stück;ISIN;WKN;Ticker-Symbol;Wertpapiername;Notiz
2017-08-07T00:00;Kauf;2.040,09;EUR;;;;10,49;0,00;43;;884437;;Starbucks;
2020-02-28T00:00;Verkauf;-2.620,46;EUR;;;;14,59;241,95;42;;884437;;Starbucks;
2020-08-21T00:00;Kauf;5.031,13;EUR;;;;19,93;0,00;48;;865985;;Apple;
```

**Comment by dredav** [comment]
I can reproduce this with the following entry in a csv file:
`2020-09-01T00:00;Kauf;927,42;EUR;;;;0,00;0,00;13;US8552441094;"884437 ";SRB.DE;STARBUCKS CORP.;`

```
{
   "isin":"US8552441094",
   "wkn":"\"884437 \"",
   "type":"Buy",
   "company":"STARBUCKS CORP.",
   "symbol":"SRB.DE",
   "date":"2020-09-01",
   "shares":13,
   "amount":927.42,
   "grossAmount":0,
   "tax":0,
   "fee":0,
   "currency":"EUR",
   "grossCurrency":"",
   "exchangeRate":0,
   "price":71.34,
   "parsed":true,
   "filename":"sample.csv"
}
```
Also we should add the validateActivity to parsed generated activities from portfolio performance and add support to validate wkn. https://github.com/codeofsumit/tresor-import/blob/ec2a71e0e2ac6b054a0cd14cbe6256715d13d527/src/helper/index.js#L37

**Comment by codeofsumit** [comment]
Agreed. How would you validate the wkn? Always string with `length === 6`

**Comment by dredav** [comment]
The ISIN must match the regex: `/^([A-Z]{2})([A-Z0-9]{9})([0-9]{1})$/` ([details](https://en.wikipedia.org/wiki/International_Securities_Identification_Number)) and the WKN `/^([A-Z0-9]{6})$/` ([details](https://de.wikipedia.org/wiki/Wertpapierkennnummer)).
I add this validation tomorrow

**Comment by codeofsumit** [comment]
awesome 👍👍 
Any idea why the WKN comes out wrong in the first place? Is that a csv parse thing?

**Comment by dredav** [comment]
Not really. I can only reproduce this bug in the master branch with an WKN in PP with a space character... I will check tomorrow if there is a difference between master branch in live version in T1.

**Comment by codeofsumit** [comment]
Hmm should we add some sort of trim function that removes special chars, spaces, etc from WKN and ISIN?
