### ISSUE TITLE
[Test] Test-Erstellung

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#111]
<h2>Description</h2>
<blockquote>
<p>Falls noch nicht vorhanden, könnte eingebaut werden, dass geprüft wird ob das Dokument bereits erkannt wird.
Wenn ja, können die erkannten Werte angezeigt werden. Falls etwas nicht stimmt, sollte der Nutzer in der Lage sein, die einzelnen Werte als falsch zu markieren.</p>
</blockquote>
<p>Wenn das zuviel Aufwand wäre, könnte man aber auch einfach nur anzeigen &quot;Sollte schon gehen, beschreib bitte was falsch ausgelesen wird&quot;.</p>
<h2>Document</h2>
<details><summary>scalablecapital-sparplankauf-a1jx52.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Scalable Capital Vermögensverw.GmbH&quot;,
    &quot;Prinzregentenstr. 48&quot;,
    &quot;80538 München&quot;,
    &quot;Wertpapierabrechnung: Kauf&quot;,
    &quot;KOPIE&quot;,
    &quot;WPABRECHNUNG-053.108&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;enkofcy@hzgyjwfryz.yc www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;München&quot;,
    &quot;08.07.2020&quot;,
    &quot;Scalable Capital&quot;,
    &quot;Vermögensverwaltung GmbH&quot;,
    &quot;Prinzregentenstr. 48&quot;,
    &quot;80538 München&quot;,
    &quot;taxpllv@alobwccm.fuhwzbx&quot;,
    &quot;Kuloedm Klkmeowr&quot;,
    &quot;Hdozw-Fl.: 5424381    Hrdtqzykw: 9&quot;,
    &quot;Rdhez-Mk.: 8726822946&quot;,
    &quot;Dxozfaez-Iy.: 93453809&quot;,
    &quot;Jxheuwhv-Mb.: 13988561&quot;,
    &quot;Kurs&quot;,
    &quot;WKN: A1JX52&quot;,
    &quot;ISIN: IE00B3RBWM25&quot;,
    &quot;Auftragsdatum:&quot;,
    &quot;EUR&quot;,
    &quot;Ausführungsplatz: GETTEX - MM Munich&quot;,
    &quot;78,68&quot;,
    &quot;Auftragszeit:&quot;,
    &quot;07.07.2020&quot;,
    &quot;11:00:05:59&quot;,
    &quot;Nominale&quot;,
    &quot;STK 0,635&quot;,
    &quot;Vanguard FTSE All-World U.ETF&quot;,
    &quot;Registered Shares USD Dis.oN&quot;,
    &quot;ext.Vermögensverw.&quot;,
    &quot;Orderroutingssystem&quot;,
    &quot;Art der Auftragserteilung:&quot;,
    &quot;Auftraggeber:&quot;,
    &quot;EUR&quot;,
    &quot;Kurswert&quot;,
    &quot;49,96&quot;,
    &quot;Valuta: 09.07.2020&quot;,
    &quot;Fr Dawncr Oyvgd 7118948049&quot;,
    &quot;EUR&quot;,
    &quot;49,96&quot;,
    &quot;Die Wertpapiere buchen wir zu Gunsten Ihres Depots.&quot;,
    &quot;Details zur Ausführung:&quot;,
    &quot;Handelsdatum&quot;,
    &quot;Handelsuhrzeit&quot;,
    &quot;07.07.2020&quot;,
    &quot;11:00:05:94&quot;,
    &quot;Verwahrart:&quot;,
    &quot;Wertpapierrechnung&quot;,
    &quot;Lagerstelle:&quot;,
    &quot;2299&quot;,
    &quot;Lagerland:&quot;,
    &quot;Großbritannien&quot;,
    &quot;Zeitzone der Handelsuhrzeit:&quot;,
    &quot;MIC des Ausführungsplatzes:&quot;,
    &quot;MEZ/MESZ&quot;,
    &quot;MUNC&quot;,
    &quot;Für die Ausführung dieses Auftrags gelten die Usancen des jeweiligen Ausführungsplatzes.&quot;,
    &quot;Bitte prüfen Sie diese Auftragsbestätigung/Abrechnung auf Richtigkeit und Vollständigkeit. Etwaige Einwendungen gegen diese&quot;,
    &quot;Auftragsbestätigung/Abrechnung müssen nach Zugang unverzüglich bei der Baader Bank AG erhoben werden.&quot;,
    &quot;Dieser Auftrag erfolgte ohne Empfehlung der Bank. Es wurde keine Anlageberatung und keine individuelle Aufklärung durch die Bank&quot;,
    &quot;erbracht.&quot;,
    &quot;Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich um eine umsatzsteuerbefreite Finanzdienstleistung.&quot;,
    &quot;dWiqd5Fk9d55wgr9XhUTKY&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Seite 1/1&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/6f6e177f</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by carstenhag** [comment]
Kann geschlossen werden. Den feature request würde ich dann woanders posten sobald das als eigenes repo verfügbar ist.
