### ISSUE TITLE
Scalable

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#118]
<h2>Description</h2>
<blockquote>
<p>Kauf Abrechnung Sparplan</p>
</blockquote>
<h2>Documents</h2>
<details><summary>2020-10-02 Wertpapierabrechnung IE00BDT8V027.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Fzehcowt Wurdabq Vdumöqmjgfofi.TclB&quot;,
    &quot;Seitzstr. 8 e&quot;,
    &quot;80538 München&quot;,
    &quot;Wertpapierabrechnung: Kauf&quot;,
    &quot;KOPIE&quot;,
    &quot;WPABRECHNUNG-054.108&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;ymjpcbt@trfklgcazi.gv www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;München&quot;,
    &quot;03.10.2020&quot;,
    &quot;Scalable Capital&quot;,
    &quot;Vermögensverwaltung GmbH&quot;,
    &quot;Seitzstraße 8e&quot;,
    &quot;80538 München&quot;,
    &quot;qugkgeq@dgbtrkdr.fowecxf&quot;,
    &quot;Eqcewvmyl Rjyrwef&quot;,
    &quot;Rxndw-Mj.: 1990992    Nwnsmdcpk: 8&quot;,
    &quot;Pbxmp-Wn.: 3094594040&quot;,
    &quot;Jrzystsh-Cc.: 24171949&quot;,
    &quot;Daxyyjpn-Vm.: 36419396&quot;,
    &quot;Kurs&quot;,
    &quot;WKN: A2JEE2&quot;,
    &quot;ISIN: IE00BDT8V027&quot;,
    &quot;Auftragsdatum:&quot;,
    &quot;EUR&quot;,
    &quot;Ausführungsplatz: GETTEX - MM Munich&quot;,
    &quot;19,158&quot;,
    &quot;Auftragszeit:&quot;,
    &quot;02.10.2020&quot;,
    &quot;11:02:00:13&quot;,
    &quot;Nominale&quot;,
    &quot;STK 1,304&quot;,
    &quot;I.M.II-I.Preferred Shares UETF&quot;,
    &quot;Registered Shs Cl.EUR hgd. o.N&quot;,
    &quot;ext.Vermögensverw.&quot;,
    &quot;Orderroutingssystem&quot;,
    &quot;Art der Auftragserteilung:&quot;,
    &quot;Auftraggeber:&quot;,
    &quot;EUR&quot;,
    &quot;Kurswert&quot;,
    &quot;24,98&quot;,
    &quot;Valuta: 06.10.2020&quot;,
    &quot;Dn Yqxgzy Qvtkf 7830310139&quot;,
    &quot;EUR&quot;,
    &quot;24,98&quot;,
    &quot;Die Wertpapiere buchen wir zu Gunsten Ihres Depots.&quot;,
    &quot;Details zur Ausführung:&quot;,
    &quot;Handelsdatum&quot;,
    &quot;Handelsuhrzeit&quot;,
    &quot;02.10.2020&quot;,
    &quot;11:02:06:76&quot;,
    &quot;Verwahrart:&quot;,
    &quot;Wertpapierrechnung&quot;,
    &quot;Lagerstelle:&quot;,
    &quot;1419&quot;,
    &quot;Lagerland:&quot;,
    &quot;Luxemburg&quot;,
    &quot;Zeitzone der Handelsuhrzeit:&quot;,
    &quot;MIC des Ausführungsplatzes:&quot;,
    &quot;MEZ/MESZ&quot;,
    &quot;MUNC&quot;,
    &quot;Für&quot;,
    &quot;die&quot;,
    &quot;Ausführung&quot;,
    &quot;dieses&quot;,
    &quot;Auftrags&quot;,
    &quot;gelten&quot;,
    &quot;die&quot;,
    &quot;Usancen&quot;,
    &quot;des&quot;,
    &quot;jeweiligen&quot;,
    &quot;Ausführungsplatzes.&quot;,
    &quot;Diese&quot;,
    &quot;Auftragsbestätigung/Abrechnung&quot;,
    &quot;wurde&quot;,
    &quot;von&quot;,
    &quot;der&quot;,
    &quot;Baader&quot;,
    &quot;Bank&quot;,
    &quot;AG&quot;,
    &quot;erstellt.&quot;,
    &quot;Bitte&quot;,
    &quot;prüfen&quot;,
    &quot;Sie&quot;,
    &quot;diese&quot;,
    &quot;auf&quot;,
    &quot;Richtigkeit&quot;,
    &quot;und&quot;,
    &quot;Vollständigkeit.&quot;,
    &quot;Etwaige&quot;,
    &quot;Einwendungen&quot;,
    &quot;gegen&quot;,
    &quot;diese&quot;,
    &quot;Auftragsbestätigung/Abrechnung&quot;,
    &quot;müssen&quot;,
    &quot;nach&quot;,
    &quot;Zugang&quot;,
    &quot;unverzüglich&quot;,
    &quot;bei&quot;,
    &quot;der&quot;,
    &quot;Baader&quot;,
    &quot;Bank&quot;,
    &quot;AG&quot;,
    &quot;erhoben&quot;,
    &quot;werden.&quot;,
    &quot;Dieser&quot;,
    &quot;Auftrag&quot;,
    &quot;erfolgte&quot;,
    &quot;ohne&quot;,
    &quot;Empfehlung&quot;,
    &quot;der&quot;,
    &quot;Bank.&quot;,
    &quot;Es&quot;,
    &quot;wurde&quot;,
    &quot;keine&quot;,
    &quot;Anlageberatung&quot;,
    &quot;und&quot;,
    &quot;keine&quot;,
    &quot;individuelle&quot;,
    &quot;Aufklärung&quot;,
    &quot;durch&quot;,
    &quot;die&quot;,
    &quot;Bank&quot;,
    &quot;erbracht.&quot;,
    &quot;Sofern&quot;,
    &quot;keine&quot;,
    &quot;Umsatzsteuer&quot;,
    &quot;ausgewiesen&quot;,
    &quot;ist,&quot;,
    &quot;handelt&quot;,
    &quot;es   sich&quot;,
    &quot;um&quot;,
    &quot;eine&quot;,
    &quot;umsatzsteuerbefreite&quot;,
    &quot;Finanzdienstleistung.&quot;,
    &quot;nB8hSZ1NFGzPdiBvfsiNuk&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Seite 1/1&quot;
  ]
]

</code></pre>
</p></details>
<details><summary>2020-10-02 Wertpapierabrechnung IE00BJGWQN72.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Scalable Capital Vermögensverw.GmbH&quot;,
    &quot;Seitzstr. 8 e&quot;,
    &quot;80538 München&quot;,
    &quot;Wertpapierabrechnung: Kauf&quot;,
    &quot;KOPIE&quot;,
    &quot;WPABRECHNUNG-054.108&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;wtbrgpq@hkthuywjdj.gd www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;München&quot;,
    &quot;03.10.2020&quot;,
    &quot;Scalable Capital&quot;,
    &quot;Vermögensverwaltung GmbH&quot;,
    &quot;Seitzstraße 8e&quot;,
    &quot;80538 München&quot;,
    &quot;awhuwtj@vppwdqso.vsawjvd&quot;,
    &quot;Askbpetxw Sshmibv&quot;,
    &quot;Nrzvj-Cf.: 7514646    Rlgusrqxf: 6&quot;,
    &quot;Xzbrr-Af.: 4760793267&quot;,
    &quot;Kpgdqygd-Ps.: 58132830&quot;,
    &quot;Jzeurvoo-Eq.: 13293421&quot;,
    &quot;Kurs&quot;,
    &quot;WKN: A2PQVE&quot;,
    &quot;ISIN: IE00BJGWQN72&quot;,
    &quot;Auftragsdatum:&quot;,
    &quot;EUR&quot;,
    &quot;Ausführungsplatz: GETTEX - MM Munich&quot;,
    &quot;36,345&quot;,
    &quot;Auftragszeit:&quot;,
    &quot;02.10.2020&quot;,
    &quot;11:05:02:15&quot;,
    &quot;Nominale&quot;,
    &quot;STK 0,687&quot;,
    &quot;WisdomTree Cloud Comp.UCITSETF&quot;,
    &quot;Registered Shares USD Acc o.N.&quot;,
    &quot;ext.Vermögensverw.&quot;,
    &quot;Orderroutingssystem&quot;,
    &quot;Art der Auftragserteilung:&quot;,
    &quot;Auftraggeber:&quot;,
    &quot;EUR&quot;,
    &quot;Kurswert&quot;,
    &quot;24,97&quot;,
    &quot;Valuta: 06.10.2020&quot;,
    &quot;Kk Jfigwv Axppp 5593531894&quot;,
    &quot;EUR&quot;,
    &quot;24,97&quot;,
    &quot;Die Wertpapiere buchen wir zu Gunsten Ihres Depots.&quot;,
    &quot;Details zur Ausführung:&quot;,
    &quot;Handelsdatum&quot;,
    &quot;Handelsuhrzeit&quot;,
    &quot;02.10.2020&quot;,
    &quot;11:05:02:51&quot;,
    &quot;Verwahrart:&quot;,
    &quot;Wertpapierrechnung&quot;,
    &quot;Lagerstelle:&quot;,
    &quot;1719&quot;,
    &quot;Lagerland:&quot;,
    &quot;Irland&quot;,
    &quot;Zeitzone der Handelsuhrzeit:&quot;,
    &quot;MIC des Ausführungsplatzes:&quot;,
    &quot;MEZ/MESZ&quot;,
    &quot;MUNC&quot;,
    &quot;Für&quot;,
    &quot;die&quot;,
    &quot;Ausführung&quot;,
    &quot;dieses&quot;,
    &quot;Auftrags&quot;,
    &quot;gelten&quot;,
    &quot;die&quot;,
    &quot;Usancen&quot;,
    &quot;des&quot;,
    &quot;jeweiligen&quot;,
    &quot;Ausführungsplatzes.&quot;,
    &quot;Diese&quot;,
    &quot;Auftragsbestätigung/Abrechnung&quot;,
    &quot;wurde&quot;,
    &quot;von&quot;,
    &quot;der&quot;,
    &quot;Baader&quot;,
    &quot;Bank&quot;,
    &quot;AG&quot;,
    &quot;erstellt.&quot;,
    &quot;Bitte&quot;,
    &quot;prüfen&quot;,
    &quot;Sie&quot;,
    &quot;diese&quot;,
    &quot;auf&quot;,
    &quot;Richtigkeit&quot;,
    &quot;und&quot;,
    &quot;Vollständigkeit.&quot;,
    &quot;Etwaige&quot;,
    &quot;Einwendungen&quot;,
    &quot;gegen&quot;,
    &quot;diese&quot;,
    &quot;Auftragsbestätigung/Abrechnung&quot;,
    &quot;müssen&quot;,
    &quot;nach&quot;,
    &quot;Zugang&quot;,
    &quot;unverzüglich&quot;,
    &quot;bei&quot;,
    &quot;der&quot;,
    &quot;Baader&quot;,
    &quot;Bank&quot;,
    &quot;AG&quot;,
    &quot;erhoben&quot;,
    &quot;werden.&quot;,
    &quot;Dieser&quot;,
    &quot;Auftrag&quot;,
    &quot;erfolgte&quot;,
    &quot;ohne&quot;,
    &quot;Empfehlung&quot;,
    &quot;der&quot;,
    &quot;Bank.&quot;,
    &quot;Es&quot;,
    &quot;wurde&quot;,
    &quot;keine&quot;,
    &quot;Anlageberatung&quot;,
    &quot;und&quot;,
    &quot;keine&quot;,
    &quot;individuelle&quot;,
    &quot;Aufklärung&quot;,
    &quot;durch&quot;,
    &quot;die&quot;,
    &quot;Bank&quot;,
    &quot;erbracht.&quot;,
    &quot;Sofern&quot;,
    &quot;keine&quot;,
    &quot;Umsatzsteuer&quot;,
    &quot;ausgewiesen&quot;,
    &quot;ist,&quot;,
    &quot;handelt&quot;,
    &quot;es   sich&quot;,
    &quot;um&quot;,
    &quot;eine&quot;,
    &quot;umsatzsteuerbefreite&quot;,
    &quot;Finanzdienstleistung.&quot;,
    &quot;cfCybzBFnqnSjBBGua3oqr&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Seite 1/1&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://tresor.one/portfolio/5f194af3e8e79400081eeb75</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Das Dokument kann seit #90 eingelesen werden.
