### ISSUE TITLE
DKB Verkauf

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#120]
<h2>Description</h2>
<blockquote>
<p>Summe Gebühren falsch. Abwicklungskosten Börse und Transaktionsentgelt Börse werden beim Import nicht berücksichtigt.</p>
</blockquote>
<h2>Document</h2>
<details><summary>Verkauf_-_WKN_A0RGCS_-_Wertpapierabrechnung_vom_10.09.2020_zu_Depot_501003180_-_Ordernr._4926360900.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Seite 1 von 3&quot;,
    &quot;10919 Berlin&quot;,
    &quot;Ehdlg&quot;,
    &quot;Epulzgc Sqydaxk&quot;,
    &quot;Soltcfmmv Iwd. 97&quot;,
    &quot;67261 Gnyjzxg&quot;,
    &quot;Depotnummer&quot;,
    &quot;644786061&quot;,
    &quot;Kundennummer&quot;,
    &quot;5411483794&quot;,
    &quot;Biqpzio Mbtgvsd&quot;,
    &quot;Auftragsnummer&quot;,
    &quot;926827/23.68&quot;,
    &quot;Datum&quot;,
    &quot;10.09.2020&quot;,
    &quot;Rechnungsnummer&quot;,
    &quot;K03712-6675641106/85&quot;,
    &quot;Umsatzsteuer-ID&quot;,
    &quot;DZ517678951&quot;,
    &quot;9021.96247101.8327943AF40&quot;,
    &quot;Wertpapier Abrechnung Verkauf&quot;,
    &quot;Nominale&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;ISIN&quot;,
    &quot;(WKN)&quot;,
    &quot;Stück 92&quot;,
    &quot;I.M.-I.MSCI WORLD UETF&quot;,
    &quot;REGISTERED SHARES ACC O.N&quot;,
    &quot;IE00B60SX394&quot;,
    &quot;(A0RGCS)&quot;,
    &quot;Handels-/Ausführungsplatz&quot;,
    &quot;Stuttgart (gemäß Weisung)&quot;,
    &quot;Börsensegment&quot;,
    &quot;STUB&quot;,
    &quot;Stop-Market-Orde&quot;,
    &quot;r&quot;,
    &quot;Stoplimit&quot;,
    &quot;58,90 EUR&quot;,
    &quot;Schlusstag/-Zeit&quot;,
    &quot;10.09.2020 15:39:56&quot;,
    &quot;Ausführungskurs&quot;,
    &quot;58,887 EUR&quot;,
    &quot;Auftraggeber&quot;,
    &quot;Qjjrchs Vjpheit&quot;,
    &quot;Auftragserteilung/ -ort&quot;,
    &quot;Online-Banking&quot;,
    &quot;Wertpapierrechnung Lagerland Irland&quot;,
    &quot;Kurswert&quot;,
    &quot;5.417,60&quot;,
    &quot;EUR&quot;,
    &quot;Provision&quot;,
    &quot;10,00-&quot;,
    &quot;EUR&quot;,
    &quot;Abwicklungskosten Börse&quot;,
    &quot;0,03-&quot;,
    &quot;EUR&quot;,
    &quot;Transaktionsentgelt Börse&quot;,
    &quot;6,29-&quot;,
    &quot;EUR&quot;,
    &quot;Ermittlung steuerrelevante Erträge&quot;,
    &quot;Veräußerungsgewinn (nach Teilfreistellung)&quot;,
    &quot;278,44&quot;,
    &quot;EUR&quot;,
    &quot;Veräußerungsverlust (nach Teilfreistellung)&quot;,
    &quot;15,37-&quot;,
    &quot;EUR&quot;,
    &quot;Bemessungsgrundlage für die Kapitalertragsteuer&quot;,
    &quot;263,07&quot;,
    &quot;EUR&quot;,
    &quot;Eingebuchte sonstige negative Kapitalerträge&quot;,
    &quot;5,58&quot;,
    &quot;EUR&quot;,
    &quot;Verrechneter Sparerpauschbetrag&quot;,
    &quot;268,65-&quot;,
    &quot;EUR&quot;,
    &quot;Ausmachender Betrag&quot;,
    &quot;5.401,28&quot;,
    &quot;EUR&quot;,
    &quot;Flm Einmrrmap qlwfmq etr myg Fvxmtx 17.21.7173 lh Ravlais mec Japgdp 2962556133&quot;,
    &quot;(EBXD VZ75 1271 1925 2207 4654 83), NWY 49941743 (CDG FOXNQWW5212).&quot;,
    &quot;Die Wertpapiere entnehmen wir Ihrem Depotkonto.&quot;
  ],
  [
    &quot;Seite 2 von 3&quot;,
    &quot;Seite 2 von 3&quot;,
    &quot;Depotnummer&quot;,
    &quot;767358085&quot;,
    &quot;Kundennummer&quot;,
    &quot;4752071067&quot;,
    &quot;Auftragsnummer&quot;,
    &quot;762030/89.90&quot;,
    &quot;Datum&quot;,
    &quot;10.09.2020&quot;,
    &quot;4137.74940986.4896346MC39&quot;,
    &quot;Steuerliche Ausgleichrechnung&quot;,
    &quot;Verrechnete sonstige negative Kapitalerträge&quot;,
    &quot;5,58-&quot;,
    &quot;Verrechneter Sparer-Pauschbetrag&quot;,
    &quot;5,58&quot;,
    &quot;Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich um eine umsatzsteuerbefreite Finanzdienstleistung.&quot;,
    &quot;Für das Geschäft wurde keine Anlageberatung erbracht.&quot;,
    &quot;Initiator der Besprechung war der Kunde.&quot;,
    &quot;Nachrichtlich die Übersicht Ihrer Verrechnungs- und Steuertopfsalden zum Zeitpunkt der Erstellung der Abrechnung.&quot;,
    &quot;Verlustverrechnungstöpfe 2020&quot;,
    &quot;Berechnungsgrundlage&quot;,
    &quot;der gezahlten Steuern&quot;,
    &quot;Euro&quot;,
    &quot;Aktien&quot;,
    &quot;Sonstige&quot;,
    &quot;Sparer-&quot;,
    &quot;Pauschbetrag&quot;,
    &quot;anrechenbare&quot;,
    &quot;Quellensteuer&quot;,
    &quot;Aktien und Sonstige&quot;,
    &quot;Vorher&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;394,42&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;Verkauf&quot;,
    &quot;0,00&quot;,
    &quot;5,58&quot;,
    &quot;268,65-&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;Steuerausgleich&quot;,
    &quot;0,00&quot;,
    &quot;5,58-&quot;,
    &quot;5,58&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;Nachher&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;131,35&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;Berücksichtigte Anschaffungsgeschäfte (alle ermittelten Beträge in EUR)&quot;,
    &quot;Geschäft&quot;,
    &quot;Auftragsnr.&quot;,
    &quot;Ausführ.-tag&quot;,
    &quot;Whr./St.&quot;,
    &quot;Nennwert/Stück&quot;,
    &quot;AS-Kosten&quot;,
    &quot;Erlös&quot;,
    &quot;Teilfrei-&quot;,
    &quot;stellung&quot;,
    &quot;ant. Ergebnis&quot;,
    &quot;Kauf&quot;,
    &quot;5502430500&quot;,
    &quot;06.08.2018&quot;,
    &quot;Stück&quot;,
    &quot;3,8551&quot;,
    &quot;201,50-&quot;,
    &quot;225,69&quot;,
    &quot;7,26-&quot;,
    &quot;16,93&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;5670250300&quot;,
    &quot;05.09.2018&quot;,
    &quot;Stück&quot;,
    &quot;3,8462&quot;,
    &quot;201,50-&quot;,
    &quot;225,16&quot;,
    &quot;7,10-&quot;,
    &quot;16,56&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;5874906500&quot;,
    &quot;05.10.2018&quot;,
    &quot;Stück&quot;,
    &quot;3,8066&quot;,
    &quot;201,50-&quot;,
    &quot;222,84&quot;,
    &quot;6,40-&quot;,
    &quot;14,94&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;6049676600&quot;,
    &quot;05.11.2018&quot;,
    &quot;Stück&quot;,
    &quot;4,0096&quot;,
    &quot;201,50-&quot;,
    &quot;234,72&quot;,
    &quot;9,97-&quot;,
    &quot;23,25&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;6242518300&quot;,
    &quot;05.12.2018&quot;,
    &quot;Stück&quot;,
    &quot;4,0177&quot;,
    &quot;201,50-&quot;,
    &quot;235,20&quot;,
    &quot;10,11-&quot;,
    &quot;23,59&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;6429102000&quot;,
    &quot;07.01.2019&quot;,
    &quot;Stück&quot;,
    &quot;4,2608&quot;,
    &quot;201,50-&quot;,
    &quot;249,43&quot;,
    &quot;14,38-&quot;,
    &quot;33,55&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;6636957100&quot;,
    &quot;05.02.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,9857&quot;,
    &quot;201,50-&quot;,
    &quot;233,38&quot;,
    &quot;9,56-&quot;,
    &quot;22,32&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;6808098700&quot;,
    &quot;05.03.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,8476&quot;,
    &quot;201,50-&quot;,
    &quot;225,35&quot;,
    &quot;7,15-&quot;,
    &quot;16,70&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;7025925600&quot;,
    &quot;05.04.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,7023&quot;,
    &quot;201,50-&quot;,
    &quot;216,89&quot;,
    &quot;4,62-&quot;,
    &quot;10,77&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;7227085100&quot;,
    &quot;06.05.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,6894&quot;,
    &quot;201,50-&quot;,
    &quot;216,20&quot;,
    &quot;4,41-&quot;,
    &quot;10,29&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;7405223000&quot;,
    &quot;05.06.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,7972&quot;,
    &quot;201,50-&quot;,
    &quot;222,57&quot;,
    &quot;6,32-&quot;,
    &quot;14,75&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;
  ],
  [
    &quot;Seite 3 von 3&quot;,
    &quot;Depotnummer&quot;,
    &quot;803674914&quot;,
    &quot;Kundennummer&quot;,
    &quot;0563824722&quot;,
    &quot;Auftragsnummer&quot;,
    &quot;919500/78.37&quot;,
    &quot;Datum&quot;,
    &quot;10.09.2020&quot;,
    &quot;7892.88185976.5608724RN02&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Berücksichtigte Anschaffungsgeschäfte (alle ermittelten Beträge in EUR) fortges.&quot;,
    &quot;Geschäft&quot;,
    &quot;Auftragsnr.&quot;,
    &quot;Ausführ.-tag&quot;,
    &quot;Whr./St.&quot;,
    &quot;Nennwert/Stück&quot;,
    &quot;AS-Kosten&quot;,
    &quot;Erlös&quot;,
    &quot;Teilfrei-&quot;,
    &quot;stellung&quot;,
    &quot;ant. Ergebnis&quot;,
    &quot;Kauf&quot;,
    &quot;4173083717&quot;,
    &quot;05.07.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,5836&quot;,
    &quot;201,50-&quot;,
    &quot;210,09&quot;,
    &quot;2,58-&quot;,
    &quot;6,01 (D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;1036017500&quot;,
    &quot;05.08.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,6826&quot;,
    &quot;201,50-&quot;,
    &quot;215,95&quot;,
    &quot;4,33-&quot;,
    &quot;10,12&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;1270803100&quot;,
    &quot;05.09.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,5785&quot;,
    &quot;201,50-&quot;,
    &quot;209,90&quot;,
    &quot;2,52-&quot;,
    &quot;5,88 (D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;1477708500&quot;,
    &quot;07.10.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,5714&quot;,
    &quot;201,50-&quot;,
    &quot;209,53&quot;,
    &quot;2,41-&quot;,
    &quot;5,62 (D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;1657180700&quot;,
    &quot;05.11.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,4329&quot;,
    &quot;201,50-&quot;,
    &quot;201,44&quot;,
    &quot;0,02&quot;,
    &quot;0,04-&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;1938929200&quot;,
    &quot;05.12.2019&quot;,
    &quot;Stück&quot;,
    &quot;3,3969&quot;,
    &quot;201,50-&quot;,
    &quot;199,38&quot;,
    &quot;0,64&quot;,
    &quot;1,48-&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;2149198100&quot;,
    &quot;06.01.2020&quot;,
    &quot;Stück&quot;,
    &quot;3,3168&quot;,
    &quot;201,50-&quot;,
    &quot;194,73&quot;,
    &quot;2,03&quot;,
    &quot;4,74-&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;2430073400&quot;,
    &quot;05.02.2020&quot;,
    &quot;Stück&quot;,
    &quot;3,2105&quot;,
    &quot;201,50-&quot;,
    &quot;188,49&quot;,
    &quot;3,90&quot;,
    &quot;9,11-&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;2812229500&quot;,
    &quot;05.03.2020&quot;,
    &quot;Stück&quot;,
    &quot;3,5155&quot;,
    &quot;201,50-&quot;,
    &quot;206,40&quot;,
    &quot;1,47-&quot;,
    &quot;3,43 (D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;3252618400&quot;,
    &quot;06.04.2020&quot;,
    &quot;Stück&quot;,
    &quot;4,0735&quot;,
    &quot;201,50-&quot;,
    &quot;239,16&quot;,
    &quot;11,30-&quot;,
    &quot;26,36&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;3548056700&quot;,
    &quot;05.05.2020&quot;,
    &quot;Stück&quot;,
    &quot;3,7373&quot;,
    &quot;201,50-&quot;,
    &quot;219,42&quot;,
    &quot;5,38-&quot;,
    &quot;12,54&quot;,
    &quot;(D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;3923076800&quot;,
    &quot;05.06.2020&quot;,
    &quot;Stück&quot;,
    &quot;3,5004&quot;,
    &quot;201,50-&quot;,
    &quot;205,51&quot;,
    &quot;1,20-&quot;,
    &quot;2,81 (D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;4268070300&quot;,
    &quot;06.07.2020&quot;,
    &quot;Stück&quot;,
    &quot;3,4473&quot;,
    &quot;201,50-&quot;,
    &quot;202,39&quot;,
    &quot;0,27-&quot;,
    &quot;0,62 (D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Kauf&quot;,
    &quot;4602925500&quot;,
    &quot;05.08.2020&quot;,
    &quot;Stück&quot;,
    &quot;3,1346&quot;,
    &quot;181,97-&quot;,
    &quot;183,97&quot;,
    &quot;0,60-&quot;,
    &quot;1,40 (D)&quot;,
    &quot;Fondskorrekturfaktoren *) zur Anschaffung:&quot;,
    &quot;VAP: 7,49&quot;,
    &quot;Summe aller Erträge nach Differenzmethode und/oder Ersatzbemessungsgrundlage&quot;,
    &quot;263,07&quot;,
    &quot;*VAP: Vorabpauschale (verringert den anteiligen Veräußerungserlös)&quot;
  ]
]

</code></pre>
</p></details>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by SirGibihm** [comment]
@codeofsumit Kann es sein, dass du bei dem JSON File das Identifizierungsmerkmal für DKB Dokumente geschwärzt hast? Der Detektionsstring "BYLADEM1001" ist nicht in der JSON enthalten.

**Comment by codeofsumit** [comment]
Das hab nicht ich submitted, das war in User - die Issues werden mit meinem Account gepostet.
Aber kann mir vorstellen dass user das tun. Würd ich auch tun.
Steht da nirgends "Deutsche Kreditbank" das man als ID verwenden kann?

**Comment by SirGibihm** [comment]
Die BIC der DKB ist mMn kein personenbezogenes Datum, da sie für alle Konten der DKB gleich bleibt. Ich habe das JSON dementsprechend mit den anderen JSON Dateien und meinen privaten PDF-Dateien abgeglichen und die Zeile korrigiert. Das Issue sollte damit behoben sein.

**Comment by codeofsumit** [comment]
> Die BIC der DKB ist mMn kein personenbezogenes Datum

Das empfinde ich genau so. Die Frage ist aber nicht was WIR als personenbezogene Daten empfinden, sondern der User der es einreicht.
Ich kann nachvollziehen dass User alles schwärzen was IHRE Bankverbindung betrifft - und am Ende müssen wir das handeln. Unsere Meinung zählt da nicht 😅
