### ISSUE TITLE
Scalable Sparplan

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#121]
<h2>Description</h2>
<blockquote>
<p>Kauf aus Sparplan.</p>
</blockquote>
<h2>Document</h2>
<details><summary>download.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Scalable Capital Vermögensverw.GmbH&quot;,
    &quot;Seitzstr. 8 e&quot;,
    &quot;80538 München&quot;,
    &quot;Wertpapierabrechnung: Kauf&quot;,
    &quot;KOPIE&quot;,
    &quot;WPABRECHNUNG-054.108&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;ezxuzub@wzvqncfelp.nh www.baaderbank.de&quot;,
    &quot;* Rhozgqfuvql Wlnplukylkofb jot cek (zhcqr-) gfnsfvafpd Nywygxdd. Oüd Tpibnu qgy ujbtntp Frhzlz höpglm Kghügznr flrthaqd.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;München&quot;,
    &quot;03.10.2020&quot;,
    &quot;Scalable Capital&quot;,
    &quot;Vermögensverwaltung GmbH&quot;,
    &quot;Seitzstraße 8e&quot;,
    &quot;80538 München&quot;,
    &quot;nrxkrkd@rmkjzmmi.cyvqgho&quot;,
    &quot;Fyzj Tuugfagho&quot;,
    &quot;Axihm-Bj.: 9817402    Zxzvcriiw: 4&quot;,
    &quot;Hfsvt-Bp.: 6078242567&quot;,
    &quot;Syeitzrj-Al.: 46977449&quot;,
    &quot;Algifaoq-Ui.: 49100779&quot;,
    &quot;Kurs&quot;,
    &quot;WKN: A143JN&quot;,
    &quot;ISIN: IE00BZ163M45&quot;,
    &quot;Auftragsdatum:&quot;,
    &quot;EUR&quot;,
    &quot;Ausführungsplatz: GETTEX - MM Munich&quot;,
    &quot;22,979&quot;,
    &quot;Auftragszeit:&quot;,
    &quot;02.10.2020&quot;,
    &quot;11:10:00:22&quot;,
    &quot;Nominale&quot;,
    &quot;STK 4,351&quot;,
    &quot;Vanguard USD Treasury Bd U.ETF&quot;,
    &quot;Registered Shares USD Dis.oN&quot;,
    &quot;ext.Vermögensverw.&quot;,
    &quot;Orderroutingssystem&quot;,
    &quot;Art der Auftragserteilung:&quot;,
    &quot;Auftraggeber:&quot;,
    &quot;EUR&quot;,
    &quot;Kurswert&quot;,
    &quot;99,98&quot;,
    &quot;Valuta: 06.10.2020&quot;,
    &quot;Nd Ttgdci Kifjy 5131250163&quot;,
    &quot;EUR&quot;,
    &quot;99,98&quot;,
    &quot;Die Wertpapiere buchen wir zu Gunsten Ihres Depots.&quot;,
    &quot;Details zur Ausführung:&quot;,
    &quot;Handelsdatum&quot;,
    &quot;Handelsuhrzeit&quot;,
    &quot;02.10.2020&quot;,
    &quot;11:10:00:63&quot;,
    &quot;Verwahrart:&quot;,
    &quot;Wertpapierrechnung&quot;,
    &quot;Lagerstelle:&quot;,
    &quot;1419&quot;,
    &quot;Lagerland:&quot;,
    &quot;Luxemburg&quot;,
    &quot;Zeitzone der Handelsuhrzeit:&quot;,
    &quot;MIC des Ausführungsplatzes:&quot;,
    &quot;MEZ/MESZ&quot;,
    &quot;MUNC&quot;,
    &quot;Für&quot;,
    &quot;die&quot;,
    &quot;Ausführung&quot;,
    &quot;dieses&quot;,
    &quot;Auftrags&quot;,
    &quot;gelten&quot;,
    &quot;die&quot;,
    &quot;Usancen&quot;,
    &quot;des&quot;,
    &quot;jeweiligen&quot;,
    &quot;Ausführungsplatzes.&quot;,
    &quot;Diese&quot;,
    &quot;Auftragsbestätigung/Abrechnung&quot;,
    &quot;wurde&quot;,
    &quot;von&quot;,
    &quot;der&quot;,
    &quot;Baader&quot;,
    &quot;Bank&quot;,
    &quot;AG&quot;,
    &quot;erstellt.&quot;,
    &quot;Bitte&quot;,
    &quot;prüfen&quot;,
    &quot;Sie&quot;,
    &quot;diese&quot;,
    &quot;auf&quot;,
    &quot;Richtigkeit&quot;,
    &quot;und&quot;,
    &quot;Vollständigkeit.&quot;,
    &quot;Etwaige&quot;,
    &quot;Einwendungen&quot;,
    &quot;gegen&quot;,
    &quot;diese&quot;,
    &quot;Auftragsbestätigung/Abrechnung&quot;,
    &quot;müssen&quot;,
    &quot;nach&quot;,
    &quot;Zugang&quot;,
    &quot;unverzüglich&quot;,
    &quot;bei&quot;,
    &quot;der&quot;,
    &quot;Baader&quot;,
    &quot;Bank&quot;,
    &quot;AG&quot;,
    &quot;erhoben&quot;,
    &quot;werden.&quot;,
    &quot;Dieser&quot;,
    &quot;Auftrag&quot;,
    &quot;erfolgte&quot;,
    &quot;ohne&quot;,
    &quot;Empfehlung&quot;,
    &quot;der&quot;,
    &quot;Bank.&quot;,
    &quot;Es&quot;,
    &quot;wurde&quot;,
    &quot;keine&quot;,
    &quot;Anlageberatung&quot;,
    &quot;und&quot;,
    &quot;keine&quot;,
    &quot;individuelle&quot;,
    &quot;Aufklärung&quot;,
    &quot;durch&quot;,
    &quot;die&quot;,
    &quot;Bank&quot;,
    &quot;erbracht.&quot;,
    &quot;Sofern&quot;,
    &quot;keine&quot;,
    &quot;Umsatzsteuer&quot;,
    &quot;ausgewiesen&quot;,
    &quot;ist,&quot;,
    &quot;handelt&quot;,
    &quot;es   sich&quot;,
    &quot;um&quot;,
    &quot;eine&quot;,
    &quot;umsatzsteuerbefreite&quot;,
    &quot;Finanzdienstleistung.&quot;,
    &quot;8C7z2pZyzitvpLx8W8TW57&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Seite 1/1&quot;
  ]
]

</code></pre>
</p></details>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Das Dokument kann seit #90 eingelesen werden.
