### ISSUE TITLE
Scalable

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#122]
<h2>Description</h2>
<blockquote>
<p>Ausschüttung eines ETF mit Quellensteuerabzug</p>
</blockquote>
<h2>Document</h2>
<details><summary>Scalable Ausschützung mit QS.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;DCUP-050.041&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;oiisuoe@zcamrlxjzq.re www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;Scalable Capital Vermögensverw.GmbH&quot;,
    &quot;Seitzstr. 8 e&quot;,
    &quot;80538 München&quot;,
    &quot;München&quot;,
    &quot;24.09.2020&quot;,
    &quot;Scalable Capital&quot;,
    &quot;Vermögensverwaltung GmbH&quot;,
    &quot;Seitzstraße 8e&quot;,
    &quot;80538 München&quot;,
    &quot;cumrbad@mstequqc.hlasryu&quot;,
    &quot;Pjbh Bzwmqukaq&quot;,
    &quot;Vjove-Lm.: 5670110    Zvkuagqsi: 8&quot;,
    &quot;Gpflz-Lm.: 7835308917&quot;,
    &quot;Vorgangs-Nr.: 3190554&quot;,
    &quot;Referenz-Nr.: 70643745&quot;,
    &quot;Fondsausschüttung&quot;,
    &quot;KOPIE&quot;,
    &quot;STK 3,046&quot;,
    &quot;Ausschüttung&quot;,
    &quot;Ex-Tag: 16.09.2020&quot;,
    &quot;ISIN: NL0009690239&quot;,
    &quot;WKN: A1T6SY&quot;,
    &quot;Nominale&quot;,
    &quot;EUR&quot;,
    &quot;0,60 p.STK&quot;,
    &quot;VanEck Vect.Gl Real Estate UE&quot;,
    &quot;Zahlungszeitraum:&quot;,
    &quot;01.01.2020 - 31.12.2020&quot;,
    &quot;Zahltag:&quot;,
    &quot;23.09.2020&quot;,
    &quot;Bruttobetrag&quot;,
    &quot;EUR&quot;,
    &quot;1,83&quot;,
    &quot;Quellensteuer&quot;,
    &quot;0,27&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;1,56&quot;,
    &quot;EUR&quot;,
    &quot;Valuta: 23.09.2020&quot;,
    &quot;Wn Xggyvkl Runhw 0209981274&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 1/2&quot;
  ],
  [
    &quot;DCUP-050.041&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;phzuxcu@lpdflhmspc.gy www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;Fondsausschüttung&quot;,
    &quot;Fortsetzung:&quot;,
    &quot;KOPIE&quot;,
    &quot;Darstellung der steuerlichen Berechnungsgrundlagen:&quot;,
    &quot;vorher&quot;,
    &quot;nachher&quot;,
    &quot;Merkposten / Steuertöpfe&quot;,
    &quot;Erhöhung/Reduktion&quot;,
    &quot;Ausschüttung netto Sonst. Fonds&quot;,
    &quot;Freistellungsauftrag&quot;,
    &quot;EUR&quot;,
    &quot;995,79&quot;,
    &quot;EUR&quot;,
    &quot;1,83&quot;,
    &quot;-&quot;,
    &quot;997,62&quot;,
    &quot;EUR&quot;,
    &quot;Ausschüttung netto Sonst. Fonds&quot;,
    &quot;Ausnutzung FSA&quot;,
    &quot;EUR&quot;,
    &quot;4,21&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;1,83&quot;,
    &quot;-&quot;,
    &quot;2,38&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Quellensteuertopf&quot;,
    &quot;EUR&quot;,
    &quot;0,27&quot;,
    &quot;EUR&quot;,
    &quot;0,27&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;Steuerpflicht brutto&quot;,
    &quot;Steuerpflicht netto&quot;,
    &quot;Bemessungsgrundlagen&quot;,
    &quot;Ausschüttung brutto Sonst. Fonds&quot;,
    &quot;1,83&quot;,
    &quot;1,83&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Ausschüttung netto Sonst. Fonds&quot;,
    &quot;1,83&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Kapitalertragsteuer auf allgemeine Gewinne&quot;,
    &quot;1,83&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;0,27&quot;,
    &quot;-&quot;,
    &quot;0,27&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Quellensteuer 15,00 %&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 2/2&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/afd52ae9</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Das Dokument kann seit #90 eingelesen werden.
