### ISSUE TITLE
[Trade Republic] Steuerrückzahlungen ("Optimierungen") werden nicht korrekt erkannt/eingebucht

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#124]
<h2>Description</h2>
<blockquote>
<p>Bei Realisierung von Verlusten wird eine Rückzahlung von bereits bezahlter Kapitalertragssteuer und Soli (&quot;Kapitalertragssteuer Optimierung&quot; / &quot;Soli Optimierung&quot;) momentan von T1 noch als gezahlte Steuer (positive Euro-Summe) und nicht als &quot;zurückgezahlte&quot; Steuer (negative Euro-Summe) erkannt und verrechnet.</p>
</blockquote>
<h2>Document</h2>
<details><summary>pb16016223858961714661903229205.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;TRADE REPUBLIC BANK GMBH&quot;,
    &quot;KASTANIENALLEE 32&quot;,
    &quot;10435 BERLIN&quot;,
    &quot;Mkjbxfeg Lvthox&quot;,
    &quot;Udotljehbw Kuosq 11&quot;,
    &quot;N 94071 Vifq&quot;,
    &quot;SEITE&quot;,
    &quot;1&quot;,
    &quot;von&quot;,
    &quot;1&quot;,
    &quot;DATUM&quot;,
    &quot;02.10.2020&quot;,
    &quot;ORDER&quot;,
    &quot;99jd-9979&quot;,
    &quot;AUSFÜHRUNG&quot;,
    &quot;461t-b3d3&quot;,
    &quot;DEPOT&quot;,
    &quot;451329731&quot;,
    &quot;Trade Republic Bank GmbH&quot;,
    &quot;Kastanienallee 32&quot;,
    &quot;10435 Berlin&quot;,
    &quot;www.traderepublic.com&quot;,
    &quot;jozfrdt@lpcxmdfmwmluo.rbm&quot;,
    &quot;Sitz der Gesellschaft: Düsseldorf&quot;,
    &quot;AG Düsseldorf HRB 85864&quot;,
    &quot;USt-ID DE307510626&quot;,
    &quot;Geschäftsführer&quot;,
    &quot;Andreas Willius&quot;,
    &quot;Karsten Müller&quot;,
    &quot;ABRE / 2020-10-02 / 84267129 / 6e00-ed2e&quot;,
    &quot;WERTPAPIERABRECHNUNG&quot;,
    &quot;ÜBERSICHT&quot;,
    &quot;Limit-Order Verkauf am 02.10.2020, um 09:04 Uhr an der Lang &amp; Schwarz Exchange.&quot;,
    &quot;Der Kontrahent der Transaktion ist Lang &amp; Schwarz TradeCenter AG &amp; Co. KG.&quot;,
    &quot;POSITION&quot;,
    &quot;ANZAHL&quot;,
    &quot;KURS&quot;,
    &quot;BETRAG&quot;,
    &quot;Workhorse Group Inc.&quot;,
    &quot;Registered Shares New DL -,001&quot;,
    &quot;ISIN: US98138J2069&quot;,
    &quot;50 Stk.&quot;,
    &quot;20,10 EUR&quot;,
    &quot;1.005,00 EUR&quot;,
    &quot;GESAMT&quot;,
    &quot;1.005,00 EUR&quot;,
    &quot;ABRECHNUNG&quot;,
    &quot;POSITION&quot;,
    &quot;BETRAG&quot;,
    &quot;Fremdkostenzuschlag&quot;,
    &quot;-1,00 EUR&quot;,
    &quot;Kapitalertragssteuer Optimierung&quot;,
    &quot;6,57 EUR&quot;,
    &quot;Solidaritätszuschlag Optimierung&quot;,
    &quot;0,36 EUR&quot;,
    &quot;GESAMT&quot;,
    &quot;1.010,93 EUR&quot;,
    &quot;BUCHUNG&quot;,
    &quot;VERRECHNUNGSKONTO&quot;,
    &quot;VALUTA&quot;,
    &quot;BETRAG&quot;,
    &quot;WP80315459201254892581&quot;,
    &quot;06.10.2020&quot;,
    &quot;1.010,93 EUR&quot;,
    &quot;Workhorse Group Inc. Registered Shares New DL -,001 in Wertpapierrechnung.&quot;,
    &quot;Lagerland: USA&quot;,
    &quot;Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.&quot;,
    &quot;Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie&quot;,
    &quot;Leistung.&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://tresor.one/portfolio/5edb7f4921e9ce0007c22013</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by SirGibihm** [comment]
Pullrequest #127 sollte dieses Issue beheben.
