### ISSUE TITLE
Scalable ETF Dividende

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#130]
<h2>Description</h2>
<blockquote>
<p>Dividendenabrechnung Vanguard Europa.</p>
</blockquote>
<h2>Document</h2>
<details><summary>Scalable ETF Dividende </summary><p>
<pre><code class="language-json">[
  [
    &quot;DCUP-050.041&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;hskeisg@ratoxqzvnq.sm www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;Scalable Capital Vermögensverw.GmbH&quot;,
    &quot;Seitzstr. 8 e&quot;,
    &quot;80538 München&quot;,
    &quot;München&quot;,
    &quot;08.10.2020&quot;,
    &quot;Scalable Capital&quot;,
    &quot;Vermögensverwaltung GmbH&quot;,
    &quot;Seitzstraße 8e&quot;,
    &quot;80538 München&quot;,
    &quot;wdovzva@chokgray.wckklgv&quot;,
    &quot;Xlwt Faefatavr&quot;,
    &quot;Scyzi-It.: 1396289    Jaficvwqr: 8&quot;,
    &quot;Uxgna-Lk.: 4076670075&quot;,
    &quot;Vorgangs-Nr.: 3235673&quot;,
    &quot;Referenz-Nr.: 72522748&quot;,
    &quot;Fondsausschüttung&quot;,
    &quot;KOPIE&quot;,
    &quot;STK 24&quot;,
    &quot;Ausschüttung&quot;,
    &quot;Ex-Tag: 24.09.2020&quot;,
    &quot;ISIN: IE00B945VV12&quot;,
    &quot;WKN: A1T8FS&quot;,
    &quot;Nominale&quot;,
    &quot;EUR&quot;,
    &quot;0,19568 p.STK&quot;,
    &quot;Vanguard FTSE Dev.Europe U.ETF&quot;,
    &quot;Registered Shares EUR Dis.oN&quot;,
    &quot;Zahlungszeitraum:&quot;,
    &quot;01.07.2019 - 30.06.2020&quot;,
    &quot;Zahltag:&quot;,
    &quot;07.10.2020&quot;,
    &quot;Bruttobetrag&quot;,
    &quot;EUR&quot;,
    &quot;4,70&quot;,
    &quot;4,70&quot;,
    &quot;EUR&quot;,
    &quot;Valuta: 07.10.2020&quot;,
    &quot;Rx Afmcgxp Xfxog 7399901890&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 1/2&quot;
  ],
  [
    &quot;DCUP-050.041&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;pbtgemf@rcpdhlxhew.at www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;Fondsausschüttung&quot;,
    &quot;Fortsetzung:&quot;,
    &quot;KOPIE&quot;,
    &quot;Darstellung der steuerlichen Berechnungsgrundlagen:&quot;,
    &quot;vorher&quot;,
    &quot;nachher&quot;,
    &quot;Merkposten / Steuertöpfe&quot;,
    &quot;Erhöhung/Reduktion&quot;,
    &quot;Ausschüttung netto Aktienfonds&quot;,
    &quot;Freistellungsauftrag&quot;,
    &quot;EUR&quot;,
    &quot;987,50&quot;,
    &quot;EUR&quot;,
    &quot;3,29&quot;,
    &quot;-&quot;,
    &quot;990,79&quot;,
    &quot;EUR&quot;,
    &quot;Ausschüttung netto Aktienfonds&quot;,
    &quot;Ausnutzung FSA&quot;,
    &quot;EUR&quot;,
    &quot;12,50&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;3,29&quot;,
    &quot;-&quot;,
    &quot;9,21&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Steuerpflicht brutto&quot;,
    &quot;Steuerpflicht netto&quot;,
    &quot;Bemessungsgrundlagen&quot;,
    &quot;Ausschüttung brutto Aktienfonds&quot;,
    &quot;4,70&quot;,
    &quot;4,70&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Ausschüttung netto Aktienfonds&quot;,
    &quot;3,29&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Kapitalertragsteuer auf allgemeine Gewinne&quot;,
    &quot;3,29&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 2/2&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/afd52ae9</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Das Auslesen von Aktivitäten wurde bereits durch #90 erledigt für den scalable.capital broker.
