### ISSUE TITLE
Gratisbroker  Baader Bank

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#131]
<h2>Description</h2>
<blockquote>
<p>Beide Belege wurden nicht automatisch eingelesen. Liegt es an der bank wenn du eine cdv liste brauchst, sende ich sie dir.</p>
</blockquote>
<h2>Documents</h2>
<details><summary>305 Divi. Volkswagen Vz 2020-10-06_1165672_01_0__3232985_wertpapier-ereignisse_72151045_20201006_1017665.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;DCUP-050.041&quot;,
    &quot;GRATISBROKER GmbH | Geschäftsführer: Malte Rubruck, Stefan Mross, Philipp Röben | HRB 242583 Amtsgericht München | USt-IdNr. DE319411410&quot;,
    &quot;GRATISBROKER GmbH erbringt Anlagevermittlung als vertraglich gebundener Vermittler der DonauCapital Wertpapier GmbH&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;rvdlwzz@bemxyinslf.fx www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;DonauCapital Wertpapier GmbH&quot;,
    &quot;wg. GRATISBROKER GmbH&quot;,
    &quot;Passauer Str. 5&quot;,
    &quot;94161 Ruderting&quot;,
    &quot;München&quot;,
    &quot;06.10.2020&quot;,
    &quot;GRATISBROKER GmbH&quot;,
    &quot;rhmlxhz@gdtnmybgepbt.hv&quot;,
    &quot;Stefan Werther&quot;,
    &quot;Stamm-Nr.: 1165672    Portfolio: 1&quot;,
    &quot;Depot-Nr.: 1165672001&quot;,
    &quot;Vorgangs-Nr.: 3232985&quot;,
    &quot;Referenz-Nr.: 72151045&quot;,
    &quot;Dividendenabrechnung&quot;,
    &quot;KOPIE&quot;,
    &quot;STK 12&quot;,
    &quot;Ausschüttung&quot;,
    &quot;Ex-Tag: 01.10.2020&quot;,
    &quot;ISIN: DE0007664039&quot;,
    &quot;WKN: 766403&quot;,
    &quot;Nominale&quot;,
    &quot;EUR&quot;,
    &quot;4,86 p.STK&quot;,
    &quot;Volkswagen AG&quot;,
    &quot;Bruttobetrag&quot;,
    &quot;EUR&quot;,
    &quot;58,32&quot;,
    &quot;Kapitalertragsteuer&quot;,
    &quot;14,58&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Solidaritätszuschlag&quot;,
    &quot;0,80&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;42,94&quot;,
    &quot;EUR&quot;,
    &quot;Valuta: 05.10.2020&quot;,
    &quot;Zu Gunsten Konto 1165672005&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 1/2&quot;
  ],
  [
    &quot;DCUP-050.041&quot;,
    &quot;GRATISBROKER GmbH | Geschäftsführer: Malte Rubruck, Stefan Mross, Philipp Röben | HRB 242583 Amtsgericht München | USt-IdNr. DE319411410&quot;,
    &quot;GRATISBROKER GmbH erbringt Anlagevermittlung als vertraglich gebundener Vermittler der DonauCapital Wertpapier GmbH&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;vmqmuxl@oeflixyjen.wu www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;Dividendenabrechnung&quot;,
    &quot;Fortsetzung:&quot;,
    &quot;KOPIE&quot;,
    &quot;Darstellung der steuerlichen Berechnungsgrundlagen:&quot;,
    &quot;Steuerpflicht brutto&quot;,
    &quot;Steuerpflicht netto&quot;,
    &quot;Bemessungsgrundlagen&quot;,
    &quot;inl. Div.&quot;,
    &quot;58,32&quot;,
    &quot;58,32&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;AbgSt inl. Div. Zahlstelle ohne KiSt&quot;,
    &quot;58,32&quot;,
    &quot;58,32&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;AbgSt inl. Div. Zahlstelle ohne KiSt&quot;,
    &quot;EUR&quot;,
    &quot;14,58&quot;,
    &quot;-&quot;,
    &quot;14,58&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Kapitalertragsteuer 25,00 %&quot;,
    &quot;EUR&quot;,
    &quot;0,80&quot;,
    &quot;-&quot;,
    &quot;0,80&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Solidaritätszuschlag 5,50 %&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 2/2&quot;
  ]
]

</code></pre>
</p></details>
<details><summary>306   34 Biontech K 2020-10-06_1165672_01_0__23229411_wertpapierabrechnung_71805181_20201006_1015987.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;DonauCapital Wertpapier GmbH&quot;,
    &quot;wg. GRATISBROKER GmbH&quot;,
    &quot;Passauer Str. 5&quot;,
    &quot;94161 Ruderting&quot;,
    &quot;Wertpapierabrechnung: Kauf&quot;,
    &quot;KOPIE&quot;,
    &quot;WPABRECHNUNG-054.108&quot;,
    &quot;GRATISBROKER GmbH | Geschäftsführer: Malte Rubruck, Stefan Mross, Philipp Röben | HRB 242583 Amtsgericht München | USt-IdNr. DE319411410&quot;,
    &quot;GRATISBROKER GmbH erbringt Anlagevermittlung als vertraglich gebundener Vermittler der DonauCapital Wertpapier GmbH&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;hxubewc@ofvzxdheyr.aw www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;München&quot;,
    &quot;06.10.2020&quot;,
    &quot;GRATISBROKER GmbH&quot;,
    &quot;huwolvp@dogkjedzmxyb.zh&quot;,
    &quot;Stefan Werther&quot;,
    &quot;Stamm-Nr.: 1165672    Portfolio: 1&quot;,
    &quot;Depot-Nr.: 1165672001&quot;,
    &quot;Vorgangs-Nr.: 23229411&quot;,
    &quot;Referenz-Nr.: 71805181&quot;,
    &quot;Kurs&quot;,
    &quot;WKN: A2PSR2&quot;,
    &quot;ISIN: US09075V1026&quot;,
    &quot;Auftragsdatum:&quot;,
    &quot;EUR&quot;,
    &quot;Ausführungsplatz: GETTEX - MM Munich&quot;,
    &quot;63,92&quot;,
    &quot;Auftragszeit:&quot;,
    &quot;05.10.2020&quot;,
    &quot;08:08:25:12&quot;,
    &quot;Nominale&quot;,
    &quot;STK 34&quot;,
    &quot;BioNTech SE&quot;,
    &quot;Nam.-Akt.(sp.ADRs)1/o.N.&quot;,
    &quot;Depotinhaber&quot;,
    &quot;Orderroutingssystem&quot;,
    &quot;Art der Auftragserteilung:&quot;,
    &quot;Auftraggeber:&quot;,
    &quot;EUR&quot;,
    &quot;Kurswert&quot;,
    &quot;2.173,28&quot;,
    &quot;Valuta: 07.10.2020&quot;,
    &quot;Zu Lasten Konto 1165672005&quot;,
    &quot;EUR&quot;,
    &quot;2.173,28&quot;,
    &quot;Die Wertpapiere buchen wir zu Gunsten Ihres Depots.&quot;,
    &quot;Nominale&quot;,
    &quot;Kurs&quot;,
    &quot;Ausführungsplatz&quot;,
    &quot;Handels-&quot;,
    &quot;datum&quot;,
    &quot;Handels-&quot;,
    &quot;uhrzeit&quot;,
    &quot;Details zur Ausführung:&quot;,
    &quot;GETTEX - MM Munich&quot;,
    &quot;05.10.2020&quot;,
    &quot;08:08:26:21&quot;,
    &quot;STK   34&quot;,
    &quot;EUR&quot;,
    &quot;63,92&quot;,
    &quot;Verwahrart:&quot;,
    &quot;Wertpapierrechnung&quot;,
    &quot;Lagerstelle:&quot;,
    &quot;2679&quot;,
    &quot;Lagerland:&quot;,
    &quot;USA&quot;,
    &quot;Zeitzone der Handelsuhrzeit:&quot;,
    &quot;MIC des Ausführungsplatzes:&quot;,
    &quot;MEZ/MESZ&quot;,
    &quot;MUNC&quot;,
    &quot;Für&quot;,
    &quot;die&quot;,
    &quot;Ausführung&quot;,
    &quot;dieses&quot;,
    &quot;Auftrags&quot;,
    &quot;gelten&quot;,
    &quot;die&quot;,
    &quot;Usancen&quot;,
    &quot;des&quot;,
    &quot;jeweiligen&quot;,
    &quot;Ausführungsplatzes.&quot;,
    &quot;Diese&quot;,
    &quot;Auftragsbestätigung/Abrechnung&quot;,
    &quot;wurde&quot;,
    &quot;von&quot;,
    &quot;der&quot;,
    &quot;Baader&quot;,
    &quot;Bank&quot;,
    &quot;AG&quot;,
    &quot;erstellt.&quot;,
    &quot;Bitte&quot;,
    &quot;prüfen&quot;,
    &quot;Sie&quot;,
    &quot;diese&quot;,
    &quot;auf&quot;,
    &quot;Richtigkeit&quot;,
    &quot;und&quot;,
    &quot;Vollständigkeit.&quot;,
    &quot;Etwaige&quot;,
    &quot;Einwendungen&quot;,
    &quot;gegen&quot;,
    &quot;diese&quot;,
    &quot;Auftragsbestätigung/Abrechnung&quot;,
    &quot;müssen&quot;,
    &quot;nach&quot;,
    &quot;Zugang&quot;,
    &quot;unverzüglich&quot;,
    &quot;bei&quot;,
    &quot;der&quot;,
    &quot;Baader&quot;,
    &quot;Bank&quot;,
    &quot;AG&quot;,
    &quot;erhoben&quot;,
    &quot;werden.&quot;,
    &quot;Dieser&quot;,
    &quot;Auftrag&quot;,
    &quot;erfolgte&quot;,
    &quot;ohne&quot;,
    &quot;Empfehlung&quot;,
    &quot;der&quot;,
    &quot;Bank.&quot;,
    &quot;Es&quot;,
    &quot;wurde&quot;,
    &quot;keine&quot;,
    &quot;Anlageberatung&quot;,
    &quot;und&quot;,
    &quot;keine&quot;,
    &quot;individuelle&quot;,
    &quot;Aufklärung&quot;,
    &quot;durch&quot;,
    &quot;die&quot;,
    &quot;Bank&quot;,
    &quot;erbracht.&quot;,
    &quot;Sofern&quot;,
    &quot;keine&quot;,
    &quot;Umsatzsteuer&quot;,
    &quot;ausgewiesen&quot;,
    &quot;ist,&quot;,
    &quot;handelt&quot;,
    &quot;es   sich&quot;,
    &quot;um&quot;,
    &quot;eine&quot;,
    &quot;umsatzsteuerbefreite&quot;,
    &quot;Finanzdienstleistung.&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Seite 1/1&quot;
  ]
]

</code></pre>
</p></details>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Gratisbroker also use the Baader Bank. Scalable.capital (and Oskar) also use the Baader Bank and maybe the current scalable.capital implementation can handle also the Gratisbroker documents. We need to check this and when it's possible we should rename the implementation to `baaderbank` instead of `scalableCapital`.
