### ISSUE TITLE
Union Investment Wertpapierabrechnung

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#134]
<h2>Description</h2>
<blockquote>
<p>pdf Import von Union Investment ist noch  nicht möglich.</p>
</blockquote>
<h2>Document</h2>
<details><summary>Wertpapierabrechnung_Nr_41_ _UnionDepot_89128193.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Union Investment Service Bank AG · 60621 Frankfurt am Main&quot;,
    &quot;Tel.: 069 58998-0, Fax: 069 58998-9000&quot;,
    &quot;·&quot;,
    &quot;E-Mail: service&quot;,
    &quot;@&quot;,
    &quot;union-investment.de&quot;,
    &quot;·&quot;,
    &quot;Internet: www.union-investment.de&quot;,
    &quot;·&quot;,
    &quot;Registergericht: Amtsgericht Frankfurt am Main HRB 54979&quot;,
    &quot;Vorstand: Horst Dietzel, Rainer Kobusch, Barbara Resch&quot;,
    &quot;·&quot;,
    &quot;Aufsichtsratsvorsitzender: Alexander Lichtenberg&quot;,
    &quot;·&quot;,
    &quot;Gläubiger-ID: IH78TMB54391119463&quot;,
    &quot;Einzahlungen: DZ BANK AG Deutsche Zentral-Genossenschaftsbank, Frankfurt am Main, IBAN: DE34 5006 0400 0000 0006 86 (BIC: GENODEFFXXX)&quot;,
    &quot;Unterdepot-Nr.:&quot;,
    &quot;13970476&quot;,
    &quot;01&quot;,
    &quot;Fonds:&quot;,
    &quot;Uni&quot;,
    &quot;Global&quot;,
    &quot;Vorsorge&quot;,
    &quot;ISIN:&quot;,
    &quot;DE000A1C81G1&quot;,
    &quot;Verwaltungsvergütung:&quot;,
    &quot;1,20&quot;,
    &quot;%&quot;,
    &quot;p.&quot;,
    &quot;a.&quot;,
    &quot;Uni&quot;,
    &quot;EuroRenta&quot;,
    &quot;ISIN:&quot;,
    &quot;DE0008491069&quot;,
    &quot;Verwaltungsvergütung:&quot;,
    &quot;0,60&quot;,
    &quot;%&quot;,
    &quot;p.&quot;,
    &quot;a.&quot;,
    &quot;Uni&quot;,
    &quot;ProfiRente&quot;,
    &quot;Altersvorsorgevertrag&quot;,
    &quot;-&quot;,
    &quot;gefördert&quot;,
    &quot;-&quot;,
    &quot;Hinweis:&quot;,
    &quot;Buchungs-/&quot;,
    &quot;Umsatzart&quot;,
    &quot;Betrag/EUR&quot;,
    &quot;Ausgabe-&quot;,
    &quot;Preis/EUR&quot;,
    &quot;Anteile&quot;,
    &quot;Preisdatum&quot;,
    &quot;aufschlag %&quot;,
    &quot;Vortrag&quot;,
    &quot;Uni&quot;,
    &quot;Global&quot;,
    &quot;Vorsorge&quot;,
    &quot;vom 01.10.2020&quot;,
    &quot;9&quot;,
    &quot;,735&quot;,
    &quot;Vortrag&quot;,
    &quot;Uni&quot;,
    &quot;EuroRenta&quot;,
    &quot;vom 01.10.2020&quot;,
    &quot;286&quot;,
    &quot;,138&quot;,
    &quot;Uni&quot;,
    &quot;Global&quot;,
    &quot;Vorsorge&quot;,
    &quot;06.10.2020&quot;,
    &quot;05.10.2020&quot;,
    &quot;Anlage&quot;,
    &quot;16&quot;,
    &quot;,30&quot;,
    &quot;5&quot;,
    &quot;,00&quot;,
    &quot;233&quot;,
    &quot;,87&quot;,
    &quot;0&quot;,
    &quot;,070&quot;,
    &quot;Uni&quot;,
    &quot;EuroRenta&quot;,
    &quot;06.10.2020&quot;,
    &quot;05.10.2020&quot;,
    &quot;Anlage&quot;,
    &quot;146&quot;,
    &quot;,70&quot;,
    &quot;3&quot;,
    &quot;,00&quot;,
    &quot;68&quot;,
    &quot;,67&quot;,
    &quot;2&quot;,
    &quot;,136&quot;,
    &quot;Kauf&quot;,
    &quot;163&quot;,
    &quot;,00&quot;,
    &quot;Bestand&quot;,
    &quot;Uni&quot;,
    &quot;Global&quot;,
    &quot;Vorsorge&quot;,
    &quot;am 06.10.2020&quot;,
    &quot;9&quot;,
    &quot;,805&quot;,
    &quot;Bestand&quot;,
    &quot;Uni&quot;,
    &quot;EuroRenta&quot;,
    &quot;am 06.10.2020&quot;,
    &quot;288&quot;,
    &quot;,274&quot;,
    &quot;Depotübersicht zum 06.10.2020&quot;,
    &quot;Unterdepot-&quot;,
    &quot;Fondsname/Produktname&quot;,
    &quot;Anteil-&quot;,
    &quot;Rücknahme-&quot;,
    &quot;Depotwert/&quot;,
    &quot;Nr.&quot;,
    &quot;ISIN/Ertragsverwendung&quot;,
    &quot;bestand&quot;,
    &quot;preis/Währung&quot;,
    &quot;Währung&quot;,
    &quot;Verwahrart/Lagerland&quot;,
    &quot;89128193&quot;,
    &quot;01&quot;,
    &quot;Uni&quot;,
    &quot;ProfiRente&quot;,
    &quot;21.403&quot;,
    &quot;,10 EUR&quot;,
    &quot;Uni&quot;,
    &quot;Global&quot;,
    &quot;Vorsorge&quot;,
    &quot;222&quot;,
    &quot;,73&quot;,
    &quot;EUR&quot;,
    &quot;9&quot;,
    &quot;,805&quot;,
    &quot;DE000A1C81G1&quot;,
    &quot;/ausschüttend&quot;,
    &quot;Girosammelverwahrung/Bundesrepublik&quot;,
    &quot;Deutschland&quot;,
    &quot;Uni&quot;,
    &quot;EuroRenta&quot;,
    &quot;66&quot;,
    &quot;,67&quot;,
    &quot;EUR&quot;,
    &quot;288&quot;,
    &quot;,274&quot;,
    &quot;DE0008491069&quot;,
    &quot;/ausschüttend&quot;,
    &quot;Girosammelverwahrung/Bundesrepublik&quot;,
    &quot;Deutschland&quot;,
    &quot;Gesamt-Depotwert&quot;,
    &quot;21.403&quot;,
    &quot;,10 EUR&quot;,
    &quot;Herrn&quot;,
    &quot;Dtrxekqso Gegz&quot;,
    &quot;Bmlweny-Xcqfk-Kbq 1&quot;,
    &quot;39227 Uosoblbtkthh yk Bkwiu&quot;,
    &quot;Gern&quot;,
    &quot;berät&quot;,
    &quot;Sie:&quot;,
    &quot;Sparda-Bank&quot;,
    &quot;Berlin&quot;,
    &quot;eG&quot;,
    &quot;Union&quot;,
    &quot;Investment&quot;,
    &quot;-&quot;,
    &quot;Kundenservice&quot;,
    &quot;Telefon:&quot;,
    &quot;069 58998-6000&quot;,
    &quot;Telefax:&quot;,
    &quot;069 58998-9000&quot;,
    &quot;E-Mail:&quot;,
    &quot;okqnkqp@bypnl-roknwejfxx.bo&quot;,
    &quot;UnionDepot:&quot;,
    &quot;16652235&quot;,
    &quot;Depotinhaber:&quot;,
    &quot;Qxhdlriwb&quot;,
    &quot;Tivn&quot;,
    &quot;6. Oktober 2020&quot;,
    &quot;Abrechnung Nr. 41&quot;,
    &quot;Fortsetzung auf Seite 2&quot;
  ],
  [
    &quot;Bitte überprüfen Sie, ob wir Ihre Aufträge weisungsgemäß ausgeführt haben. Bei Differenzen informieren Sie uns bitte schriftlich unverzüglich&quot;,
    &quot;unter Angabe Ihrer jeweiligen 10-stelligen Unterdepot-Nummer und der Abrechnungsnummer, die Sie auf der ersten Seite der Abrechnung&quot;,
    &quot;finden. Die Verkaufsunterlagen nach&quot;,
    &quot;§&quot;,
    &quot;297 Abs. 5  KAGB und aktuelle Fondsinformationen erhalten Sie kostenlos bei Ihrer Bank oder im&quot;,
    &quot;Internet unter www.union-investment.de.&quot;,
    &quot;Die&quot;,
    &quot;Bewertung&quot;,
    &quot;der&quot;,
    &quot;Fonds&quot;,
    &quot;erfolgt&quot;,
    &quot;zum&quot;,
    &quot;jeweils&quot;,
    &quot;letzten&quot;,
    &quot;verfügbaren&quot;,
    &quot;Rücknahmepreis.&quot;,
    &quot;In&quot;,
    &quot;der&quot;,
    &quot;Depotübersicht&quot;,
    &quot;sind&quot;,
    &quot;alle&quot;,
    &quot;Fondsanteile&quot;,
    &quot;enthalten,&quot;,
    &quot;die&quot;,
    &quot;am&quot;,
    &quot;Tag&quot;,
    &quot;der&quot;,
    &quot;Erstellung&quot;,
    &quot;dieser&quot;,
    &quot;Abrechnung&quot;,
    &quot;in&quot;,
    &quot;Ihrem&quot;,
    &quot;Depotbestand&quot;,
    &quot;sind.&quot;,
    &quot;In&quot;,
    &quot;manchen&quot;,
    &quot;Fällen&quot;,
    &quot;weichen&quot;,
    &quot;die&quot;,
    &quot;Werte&quot;,
    &quot;der&quot;,
    &quot;Depotübersicht&quot;,
    &quot;von&quot;,
    &quot;der&quot;,
    &quot;Abrechnungsübersicht&quot;,
    &quot;ab.&quot;,
    &quot;Das&quot;,
    &quot;kann&quot;,
    &quot;dann&quot;,
    &quot;vorkommen,&quot;,
    &quot;wenn&quot;,
    &quot;zum&quot;,
    &quot;Beispiel&quot;,
    &quot;Fonds&quot;,
    &quot;betroffen&quot;,
    &quot;sind,&quot;,
    &quot;die&quot;,
    &quot;nicht&quot;,
    &quot;taggleich&quot;,
    &quot;abgerechnet&quot;,
    &quot;werden.&quot;,
    &quot;Das&quot;,
    &quot;ist&quot;,
    &quot;bei&quot;,
    &quot;den&quot;,
    &quot;meisten&quot;,
    &quot;Drittfonds&quot;,
    &quot;oder&quot;,
    &quot;Finanzportfolioverwaltungen&quot;,
    &quot;der&quot;,
    &quot;Fall.&quot;,
    &quot;Hier&quot;,
    &quot;können&quot;,
    &quot;Transaktionen&quot;,
    &quot;zwar&quot;,
    &quot;bereits&quot;,
    &quot;für&quot;,
    &quot;einen&quot;,
    &quot;der&quot;,
    &quot;betroffenen&quot;,
    &quot;Fonds&quot;,
    &quot;gebucht&quot;,
    &quot;und&quot;,
    &quot;abgerechnet&quot;,
    &quot;sein,&quot;,
    &quot;für&quot;,
    &quot;den&quot;,
    &quot;anderen&quot;,
    &quot;betroffenen&quot;,
    &quot;Fonds&quot;,
    &quot;aber&quot;,
    &quot;noch&quot;,
    &quot;nicht.&quot;,
    &quot;In&quot;,
    &quot;Ihrer&quot;,
    &quot;nächsten&quot;,
    &quot;Depotübersicht&quot;,
    &quot;ist&quot;,
    &quot;die&quot;,
    &quot;ausstehende&quot;,
    &quot;Buchung&quot;,
    &quot;berücksichtigt.&quot;,
    &quot;Aufgrund&quot;,
    &quot;des&quot;,
    &quot;Beschlusses&quot;,
    &quot;der&quot;,
    &quot;Bundesregierung&quot;,
    &quot;zur&quot;,
    &quot;befristeten&quot;,
    &quot;Senkung&quot;,
    &quot;der&quot;,
    &quot;Mehrwertsteuer&quot;,
    &quot;von&quot;,
    &quot;19&quot;,
    &quot;auf&quot;,
    &quot;16&quot;,
    &quot;Prozent&quot;,
    &quot;ergänzt&quot;,
    &quot;Union&quot;,
    &quot;Investment&quot;,
    &quot;Service&quot;,
    &quot;Bank&quot;,
    &quot;AG&quot;,
    &quot;für&quot;,
    &quot;den&quot;,
    &quot;Zeitraum&quot;,
    &quot;1.&quot;,
    &quot;Juli&quot;,
    &quot;bis&quot;,
    &quot;31.&quot;,
    &quot;Dezember&quot;,
    &quot;2020&quot;,
    &quot;das&quot;,
    &quot;Preis-&quot;,
    &quot;und&quot;,
    &quot;Leistungsverzeichnis.&quot;,
    &quot;Die&quot;,
    &quot;darin&quot;,
    &quot;aufgeführten&quot;,
    &quot;Entgelte&quot;,
    &quot;und&quot;,
    &quot;Gebühren&quot;,
    &quot;berücksichtigen&quot;,
    &quot;den&quot;,
    &quot;reduzierten&quot;,
    &quot;Mehrwertsteuersatz&quot;,
    &quot;und&quot;,
    &quot;wurden&quot;,
    &quot;entsprechend&quot;,
    &quot;gesenkt.&quot;,
    &quot;Bei&quot;,
    &quot;Fragen&quot;,
    &quot;sind&quot;,
    &quot;wir&quot;,
    &quot;gern&quot;,
    &quot;für&quot;,
    &quot;Sie&quot;,
    &quot;da.&quot;,
    &quot;Rufen&quot;,
    &quot;Sie&quot;,
    &quot;uns&quot;,
    &quot;einfach&quot;,
    &quot;an!&quot;,
    &quot;Sie&quot;,
    &quot;erreichen&quot;,
    &quot;uns&quot;,
    &quot;montags&quot;,
    &quot;bis&quot;,
    &quot;freitags&quot;,
    &quot;zwischen&quot;,
    &quot;08:00&quot;,
    &quot;und&quot;,
    &quot;18:00&quot;,
    &quot;Uhr.&quot;,
    &quot;Datenschutzfeld&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&quot;,
    &quot;Seite 2 von 2&quot;,
    &quot;zum Schreiben vom 6. Oktober 2020&quot;,
    &quot;UnionDepot:&quot;,
    &quot;32483307&quot;,
    &quot;Depotinhaber:&quot;,
    &quot;Tzxtsqlhz&quot;,
    &quot;Scej&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/fdf46efd</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
@SirGibihm I found this older issue today. Can you adjust the unioninvest implementation to get this document also parsed?

**Comment by SirGibihm** [comment]
I tried but the format of the allready implemented .pdf files (see my PR) and these are significantly different for some reasons. I had the original .pdf file for the documents from my PR that helped with interpreting the data. I am quite unsure about this. In my previous files a `Buy` operation was marked by the string `Kauf`, followed by `Anlage`. In this file I see both `Anlage` without a `Kauf` as well as a `Kauf` preceeded(!) by `Anlage`. Would it be possible to get the original .pdf? Still working on this though

**Comment by dredav** [comment]
Does a screenshot helps or do you need the entire pdf?  @SirGibihm

**Comment by SirGibihm** [comment]
A screenshot would be totally sufficient! I would prefer the amounts/prices not to be censored if possible

**Comment by dredav** [comment]
I can provide you one tomorrow. I'll attach it here.

**Comment by dredav** [comment]
@SirGibihm 
![image](https://user-images.githubusercontent.com/731073/99932808-78629d00-2d59-11eb-9a98-50e1a77a5e14.png)

**Comment by SirGibihm** [comment]
@dredav Just as an FYI: I am working on it but this is a tricky one to get right. It seems to me like there is a difference between something only titled `Anlage` and something that also includes `Kauf`. As far as I can see it, I would categorize the string `Anlage` to be an indicator for a `Buy` Operation.  

In the previous testfiles `Kauf` always came before `Anlage`
