### ISSUE TITLE
Problem beim Import eines comdirect PDF

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#135]
<h2>Description</h2>
<blockquote>
<p>Bei zwei PDFs vorher hat es funktioniert. Bei diesem nicht. JavaScript Error:</p>
</blockquote>
<p>The fee amount in activity for comdirect must be a number greater than 0.</p>
<p>Im Object steht:</p>
<p>amount: 69.99
broker: &quot;comdirect&quot;
company: &quot;AB SICAV I-American Growth Ptf&quot;
date: &quot;2020-10-07&quot;
fee: -5
isin: &quot;LU0079474960&quot;
price: 116.44409937888199
shares: 0.644
tax: 0
type: &quot;Buy&quot;</p>
<p>Und dann noch:</p>
<p>RangeError: Invalid time value</p>
<h2>Document</h2>
<details><summary>Wertpapierabrechnung_Kauf_0644_St._WKN_986838(ABSICAVI-AM.GR.PTF_A)_vom_07.10.2020D1291D.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;*&quot;,
    &quot;Telefon   :&quot;,
    &quot;04106-708 25 00&quot;,
    &quot;Sgippap Jbyuvotfv&quot;,
    &quot;Nhutfdjzrf. 04&quot;,
    &quot;66441 Jdohrabtuc&quot;,
    &quot;010&quot;,
    &quot;10295&quot;,
    &quot;Depotnr.:&quot;,
    &quot;1850849 83&quot;,
    &quot;BLZ:&quot;,
    &quot;097 575 92&quot;,
    &quot;GESCHÄFTSABRECHNUNG VOM&quot;,
    &quot;08.10.2020&quot;,
    &quot;Wertpapierkauf&quot;,
    &quot;Geschäftsnummer   : 91 060783&quot;,
    &quot;369314691510      Puyejtzwypbndad   : 043522416439Z403&quot;,
    &quot;Geschäftstag      : 07.10.2020        Ausführung          comdirect&quot;,
    &quot;(Festpreisgeschäft)&quot;,
    &quot;Wertpapier-Bezeichnung                                               WPKNR/ISIN&quot;,
    &quot;AB SICAV I-American Growth Ptf                                           986838&quot;,
    &quot;Actions Nom. A o.N.                                                LU0079474960&quot;,
    &quot;Nennwert                  Zum comdirect Preis von&quot;,
    &quot;St.  0,644                USD  144,15789&quot;,
    &quot;Kurswert                    : USD               92,84&quot;,
    &quot;Ausmachender Betrag         : USD               88,20&quot;,
    &quot;Umrechnung zum Devisenkurs 1,176100        : EUR               74,99&quot;,
    &quot;5,00000% Reduktion Kaufaufschlag     : USD                4,64-&quot;,
    &quot;IBAN                                  Valuta         Zu Ihren Lasten vor Steuern&quot;,
    &quot;LH34 5590 3409 0803 1702 09   KLM     09.11.4152        HXL               99,58&quot;,
    &quot;Verwahrungs-Art: WERTPAPIERRECHNUNG LUXEMBURG (AKV)&quot;,
    &quot;Informationen zur steuerlichen Behandlung dieses Geschäftsvorgangs und den auf&quot;,
    &quot;Ihrem Konto gebuchten Endbetrag finden Sie auf der separaten Steuermitteilung.&quot;,
    &quot;comdirect bank AG&quot;,
    &quot;Diese Abrechnung wird von der Bank nicht unterschrieben&quot;,
    &quot;Die Leistung ist gemäß §4 Nr.8 UStG umsatzsteuerfrei. USt-Id-Nr.: DE 812 279 461&quot;,
    &quot;25449&quot;,
    &quot;Quickborn&quot;,
    &quot;Ihren&quot;,
    &quot;Auftrag&quot;,
    &quot;haben&quot;,
    &quot;wir&quot;,
    &quot;gemäß&quot;,
    &quot;unseren&quot;,
    &quot;produktbezogenen&quot;,
    &quot;Geschäftsbedingungen&quot;,
    &quot;\&quot;Trading\&quot;&quot;,
    &quot;wie&quot;,
    &quot;nachstehend&quot;,
    &quot;ausgeführt.&quot;,
    &quot;Die&quot;,
    &quot;Wertpapiere&quot;,
    &quot;haben&quot;,
    &quot;wir&quot;,
    &quot;der&quot;,
    &quot;Abrechnung&quot;,
    &quot;entsprechend&quot;,
    &quot;gebucht.&quot;,
    &quot;Wir&quot;,
    &quot;bitten&quot;,
    &quot;Sie,&quot;,
    &quot;diese&quot;,
    &quot;Abrechnung&quot;,
    &quot;auf&quot;,
    &quot;ihre&quot;,
    &quot;Richtigkeit&quot;,
    &quot;und&quot;,
    &quot;Vollständigkeit&quot;,
    &quot;zu&quot;,
    &quot;überprüfen&quot;,
    &quot;und&quot;,
    &quot;etwaige&quot;,
    &quot;Einwendungen&quot;,
    &quot;unverzüglich&quot;,
    &quot;zu&quot;,
    &quot;erheben.&quot;,
    &quot;A113&quot;,
    &quot;DO15DD/16/04/2010&quot;
  ],
  [
    &quot;Kundennr.&quot;,
    &quot;/BLZ&quot;,
    &quot;Bezeichnung&quot;,
    &quot;abweichend&quot;,
    &quot;wirtschaftlich&quot;,
    &quot;Berechtigter&quot;,
    &quot;Xhnjfze  Agzsrppcb&quot;,
    &quot;Ponjbzbrem. 01&quot;,
    &quot;66628 Uafqtbigpq&quot;,
    &quot;----&quot;,
    &quot;5296424&quot;,
    &quot;891 907 54&quot;,
    &quot;KEINE STEUERBESCHEINIGUNG&quot;,
    &quot;...&quot;,
    &quot;comdirect bank AG&quot;,
    &quot;25451 Quickborn&quot;,
    &quot;Telefon:&quot;,
    &quot;04106 - 708 25 00&quot;,
    &quot;Datum:&quot;,
    &quot;08.10.2020&quot;,
    &quot;Referenz-Nummer:&quot;,
    &quot;2&quot;,
    &quot;KIC37WM7M0105H3&quot;,
    &quot;Depotnummer:&quot;,
    &quot;0124100 29&quot;,
    &quot;Herrn&quot;,
    &quot;Ovhyirl Vcpecnczt&quot;,
    &quot;Fgoovowqjm. 23&quot;,
    &quot;23133 Lloojdkcda&quot;,
    &quot;010&quot;,
    &quot;10295&quot;,
    &quot;Steuerliche Behandlung: Wertpapierkauf Nr. 91060783 vom 07.10.2020&quot;,
    &quot;Stk.               0,644 ABSICAVI-AM.GR.PTF A , WKN / ISIN: 986838  / LU0079474960&quot;,
    &quot;Zu Ihren Lasten vor Steuern:&quot;,
    &quot;EUR            -74,99&quot;,
    &quot;Steuerbemessungsgrundlage&quot;,
    &quot;EUR              0,00&quot;,
    &quot;Kapitalertragsteuer&quot;,
    &quot;EUR              0,00&quot;,
    &quot;Solidaritätszuschlag&quot;,
    &quot;EUR              0,00&quot;,
    &quot;Kirchensteuer&quot;,
    &quot;EUR              0,00&quot;,
    &quot;_____________________&quot;,
    &quot;abgeführte Steuern&quot;,
    &quot;EUR              0,00&quot;,
    &quot;_____________________&quot;,
    &quot;Zu Ihren Lasten nach Steuern:&quot;,
    &quot;EUR            -74,99&quot;,
    &quot;Die Belastung erfolgt mit Valuta 12.10.2020 auf Konto EUR mit der IBAN KA13 6874 0298 5007 6985 60&quot;,
    &quot;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&quot;
  ],
  [
    &quot;Bisher&quot;,
    &quot;einbehaltene&quot;,
    &quot;bzw.&quot;,
    &quot;angerechnete&quot;,
    &quot;Steuer&quot;,
    &quot;in&quot;,
    &quot;EUR&quot;,
    &quot;(4)&quot;,
    &quot;Verrechnungssalden&quot;,
    &quot;in&quot;,
    &quot;EUR&quot;,
    &quot;(4)&quot;,
    &quot;in&quot;,
    &quot;vor&quot;,
    &quot;Ermittlung&quot;,
    &quot;nach&quot;,
    &quot;Ermittlung&quot;,
    &quot;einbehaltene&quot;,
    &quot;Kapitalertragsteuer&quot;,
    &quot;Solidaritätszuschlag&quot;,
    &quot;einbehaltene&quot;,
    &quot;Kirchensteuer&quot;,
    &quot;angerechnete&quot;,
    &quot;ausländische&quot;,
    &quot;Quellensteuer&quot;,
    &quot;vor&quot;,
    &quot;Ermittlung&quot;,
    &quot;nach&quot;,
    &quot;Ermittlung&quot;,
    &quot;aus&quot;,
    &quot;Aktien&quot;,
    &quot;sonstige&quot;,
    &quot;Gewinne&quot;,
    &quot;/&quot;,
    &quot;Verluste&quot;,
    &quot;anrechenbare&quot;,
    &quot;ausländische&quot;,
    &quot;Quellensteuer&quot;,
    &quot;verfügbarer&quot;,
    &quot;Freistellungsauftrag&quot;,
    &quot;einbehaltener&quot;,
    &quot;Gewinne&quot;,
    &quot;/&quot;,
    &quot;Verluste&quot;,
    &quot;2020&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;KEINE STEUERBESCHEINIGUNG&quot;,
    &quot;2020&quot;,
    &quot;in&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;comdirect bank AG&quot;,
    &quot;Diese Abrechnung ist maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;(4) Die ausgewiesenen EUR-Beträge spiegeln den Stand zum Abrechnungszeitpunkt wider.&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/a443dcd3</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by SirGibihm** [comment]
Ich vermute, dass es beim PDF-Parsen zu einem Fehler kam. Der Bug selbst entsteht in Zeile 90 von ```src/brokers/comdirect.js```, da die Zeile  ```LH34 5590 3409 0803 1702 09   KLM     09.11.4152        HXL               99,58``` aus dem o. g. JSON nicht geparsed werden kann. Basierend auf den anderen JSONs *vermute* ich, dass das eigentliche Ergebnis des Parsings aus der PDF hätte Folgendes sein müssen: ```LH34 5590 3409 0803 1702 09  USD 08.10.2020 USD 99,58```  

Ich habe hier leider keine Lösung atm.

**Comment by dredav** [comment]
@SirGibihm Diese Zeile vom original wurde ziemlich sicher durch das [Import-Tool](https://import.tresor.one) verändert. Das Tool arbeitet mit einem Regex, welcher nach IBAN-Nummern sucht und ersetzt diese automatisch. Der Benutzer hat dann wohl zusätzlich die ganze Zeile anonymisiert. Wir müssen dies dann hier in den Testdaten wieder so mocken, dass es für uns passt. Ich verstehe den Benutzer hier, da er einfach alles, was irgendwie nach einer Bankverbindung oder Ähnlichem aussieht, einfach anonymisiert zum Schutze seiner Daten. Wir bekommen ja immerhin den Inhalt des Dokuments.

Übrigens: Die Anonymisierungslogik ersetzt Zahlen nur duch Zahlen und Buchstaben nur duch Buchstaben. Daher:
`LH34 5590 3409 0803 1702 09` wird eine gültige IBAN sein.
`09.11.4152` hier das Datum der Abbuchung von dem Konto
`HXL 99,58` der Betrag in EUR welcher vom Konto eingezogen wurde (Vermutlich: `EUR 78,94` Formel: `(74,99 + (4,64 / 1,176100)`)

**Comment by SirGibihm** [comment]
@dredav Perfekt, dann werde ich den Mock anpassen. Die Bedenken des Nutzers finde ich auch absolut gerechtfertigt, immerhin sind die Daten hier ja öffentlich einsehbar! Ich übernehme das Issue heute Abend.

**Comment by PhilippSchreiber** [comment]
Hey, 
ich habe das Issue erstellt. Wenn ihr irgendwelche Daten braucht, um das besser fixen zu können bitte einfach Bescheid geben. Das Import Tool ist cool – aber irgendwie hatte ich das Gefühl, dass manche Werte auch magic überschrieben wurden, da ich so weit noch gar nicht war.

**Comment by SirGibihm** [comment]
@PhilippSchreiber der Fix ist bereits da und auf dem Weg, es dauert nur noch etwas ;)
