### ISSUE TITLE
[Scalable Broker|Baader Bank Dokument] Dividendenzahlung

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#138]
<h2>Description</h2>
<blockquote>
<p>Es war nicht möglich, die Dividendenzahlung in der UI zu importieren, deswegen anbei die Dividendenzahlung mit Steuern. Das Dokument stammt von der Baader Bank, der Broker ist von Scalable Capital.</p>
</blockquote>
<h2>Document</h2>
<details><summary>1324564_01_0__3269727_security-events_72736753_20201009.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;DCUP-050.041&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;vrkcooi@lajmkqckah.si www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;Fhppa&quot;,
    &quot;Pyuycb Xvark&quot;,
    &quot;Xytqfuojßn 479&quot;,
    &quot;88544 Qkkumftcf&quot;,
    &quot;München&quot;,
    &quot;09.10.2020&quot;,
    &quot;Scalable Capital&quot;,
    &quot;Vermögensverwaltung GmbH&quot;,
    &quot;Seitzstraße 8e&quot;,
    &quot;80538 München&quot;,
    &quot;cwdvmbi@dmutqppj.vjpyhge&quot;,
    &quot;Uncqfi Lfonx&quot;,
    &quot;Ujsoy-Dj.: 1391634    Kpbmuifev: 9&quot;,
    &quot;Rqskh-Oy.: 0495375114&quot;,
    &quot;Ayxroxwo-Ws.: 1967498&quot;,
    &quot;Abmytowm-Nf.: 30811368&quot;,
    &quot;Fondsausschüttung&quot;,
    &quot;STK 28&quot;,
    &quot;Ausschüttung&quot;,
    &quot;Ex-Tag: 24.09.2020&quot;,
    &quot;ISIN: IE00B3RBWM25&quot;,
    &quot;WKN: A1JX52&quot;,
    &quot;Nominale&quot;,
    &quot;USD&quot;,
    &quot;0,454628 p.STK&quot;,
    &quot;Vanguard FTSE All-World U.ETF&quot;,
    &quot;Registered Shares USD Dis.oN&quot;,
    &quot;Zahlungszeitraum:&quot;,
    &quot;01.07.2019 - 30.06.2020&quot;,
    &quot;Zahltag:&quot;,
    &quot;07.10.2020&quot;,
    &quot;Umrechnungskurs:&quot;,
    &quot;1,17942&quot;,
    &quot;EUR/USD&quot;,
    &quot;Bruttobetrag&quot;,
    &quot;USD&quot;,
    &quot;12,73&quot;,
    &quot;Bruttobetrag&quot;,
    &quot;EUR&quot;,
    &quot;10,79&quot;,
    &quot;Kapitalertragsteuer&quot;,
    &quot;1,89&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Solidaritätszuschlag&quot;,
    &quot;0,10&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;8,80&quot;,
    &quot;EUR&quot;,
    &quot;Valuta: 07.10.2020&quot;,
    &quot;Lj Lztwukc Rqnhs 0429367798&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 1/2&quot;
  ],
  [
    &quot;DCUP-050.041&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;emngzds@sthkhgwfbu.xq www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;Fondsausschüttung&quot;,
    &quot;Fortsetzung:&quot;,
    &quot;Darstellung der steuerlichen Berechnungsgrundlagen:&quot;,
    &quot;vorher&quot;,
    &quot;nachher&quot;,
    &quot;Merkposten / Steuertöpfe&quot;,
    &quot;Erhöhung/Reduktion&quot;,
    &quot;bezahlte Kapitalertragsteuer&quot;,
    &quot;EUR&quot;,
    &quot;1,89&quot;,
    &quot;EUR&quot;,
    &quot;1,89&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;Steuerpflicht brutto&quot;,
    &quot;Steuerpflicht netto&quot;,
    &quot;Bemessungsgrundlagen&quot;,
    &quot;Ausschüttung brutto Aktienfonds&quot;,
    &quot;10,79&quot;,
    &quot;10,79&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Ausschüttung netto Aktienfonds&quot;,
    &quot;7,55&quot;,
    &quot;7,55&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Kapitalertragsteuer auf allgemeine Gewinne&quot;,
    &quot;7,55&quot;,
    &quot;7,55&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Kapitalertragsteuer auf allgemeine Gewinne&quot;,
    &quot;EUR&quot;,
    &quot;1,89&quot;,
    &quot;-&quot;,
    &quot;1,89&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Kapitalertragsteuer 25,00 %&quot;,
    &quot;EUR&quot;,
    &quot;0,10&quot;,
    &quot;-&quot;,
    &quot;0,10&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Solidaritätszuschlag 5,50 %&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 2/2&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/c81c00de</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Diese Abrechnung kann seit #90 eingelesen werden.
