### ISSUE TITLE
CSV Flatex Bank AT  (Österreich)

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#140]
<h2>Description</h2>
<blockquote>
<p>Hi,
anbei noch eine Bank. Ich hoffe, es passte auch heute nachmittag alles so, sonst müssen wir einen anderen Weg finden.</p>
</blockquote>
<p>LG Stefan (Fuchs)</p>
<h2>Document</h2>
<details><summary>Flatex_AT.csv</summary><p>
<pre><code class="language-json">[
  [
    {
      &quot;Datum&quot;: &quot;2020-09-01T00:00&quot;,
      &quot;Typ&quot;: &quot;Kauf&quot;,
      &quot;Wert&quot;: &quot;-489,09&quot;,
      &quot;Buchungswährung&quot;: &quot;EUR&quot;,
      &quot;Steuern&quot;: &quot;&quot;,
      &quot;Stück&quot;: &quot;&quot;,
      &quot;ISIN&quot;: &quot;IE00BYWQWR46&quot;,
      &quot;WKN&quot;: &quot;A2PLDF&quot;,
      &quot;Ticker-Symbol&quot;: &quot;ESP0.F&quot;,
      &quot;Wertpapiername&quot;: &quot;VANECK ETFS-VVVG+ESP.ADLA&quot;,
      &quot;Notiz\r&quot;: &quot;285 15 Stck Vaneck VVVg\r&quot;
    },
    {
      &quot;Datum&quot;: &quot;2020-10-05T11:21&quot;,
      &quot;Typ&quot;: &quot;Kauf&quot;,
      &quot;Wert&quot;: &quot;-291,56&quot;,
      &quot;Buchungswährung&quot;: &quot;EUR&quot;,
      &quot;Steuern&quot;: &quot;&quot;,
      &quot;Stück&quot;: &quot;&quot;,
      &quot;ISIN&quot;: &quot;IE00B1XNHC34&quot;,
      &quot;WKN&quot;: &quot;A0MW0M&quot;,
      &quot;Ticker-Symbol&quot;: &quot;IQQH.F&quot;,
      &quot;Wertpapiername&quot;: &quot;ISHSII-GL.CL.ENERGY DLDIS&quot;,
      &quot;Notiz\r&quot;: &quot;301  30  ETF ISHS Energy K 20201005_KaufFondsZertifikate_31016852175_168314353.pdf\r&quot;
    },
    {
      &quot;Datum&quot;: &quot;2020-10-05T11:22&quot;,
      &quot;Typ&quot;: &quot;Kauf&quot;,
      &quot;Wert&quot;: &quot;-188,03&quot;,
      &quot;Buchungswährung&quot;: &quot;EUR&quot;,
      &quot;Steuern&quot;: &quot;&quot;,
      &quot;Stück&quot;: &quot;&quot;,
      &quot;ISIN&quot;: &quot;IE00B1XNHC34&quot;,
      &quot;WKN&quot;: &quot;A0MW0M&quot;,
      &quot;Ticker-Symbol&quot;: &quot;IQQH.F&quot;,
      &quot;Wertpapiername&quot;: &quot;ISHSII-GL.CL.ENERGY DLDIS&quot;,
      &quot;Notiz\r&quot;: &quot;302  19 ETF ISHS-Energy  1918920201005_KaufFondsZertifikate_31016852175_168314378.pdf\r&quot;
    },
    {
      &quot;Datum&quot;: &quot;2020-10-05T11:24&quot;,
      &quot;Typ&quot;: &quot;Kauf&quot;,
      &quot;Wert&quot;: &quot;-118,84&quot;,
      &quot;Buchungswährung&quot;: &quot;EUR&quot;,
      &quot;Steuern&quot;: &quot;&quot;,
      &quot;Stück&quot;: &quot;&quot;,
      &quot;ISIN&quot;: &quot;LU0832435464&quot;,
      &quot;WKN&quot;: &quot;LYX0PM&quot;,
      &quot;Ticker-Symbol&quot;: &quot;VOOL.DE&quot;,
      &quot;Wertpapiername&quot;: &quot;MUL-LYX.S+P500VFER UE A&quot;,
      &quot;Notiz\r&quot;: &quot;303  17 ETF ISHS-VFER K 20201005_KaufFondsZertifikate_31016852175_168314890.pdf\r&quot;
    },
    {
      &quot;Datum&quot;: &quot;2020-10-05T11:27&quot;,
      &quot;Typ&quot;: &quot;Kauf&quot;,
      &quot;Wert&quot;: &quot;-73,33&quot;,
      &quot;Buchungswährung&quot;: &quot;EUR&quot;,
      &quot;Steuern&quot;: &quot;&quot;,
      &quot;Stück&quot;: &quot;&quot;,
      &quot;ISIN&quot;: &quot;LU0832435464&quot;,
      &quot;WKN&quot;: &quot;LYX0PM&quot;,
      &quot;Ticker-Symbol&quot;: &quot;VOOL.DE&quot;,
      &quot;Wertpapiername&quot;: &quot;MUL-LYX.S+P500VFER UE A&quot;,
      &quot;Notiz\r&quot;: &quot;304  10 ETF ISHS-VFER K 20201005_KaufFondsZertifikate_31016852175_168315963.pdf&quot;
    }
  ]
]

</code></pre>
</p></details>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Details siehe #137. Closed.
