### ISSUE TITLE
Postbank Import funktioniert nicht mehr

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#143]
<h2>Description</h2>
<blockquote>
<p>Postbank Import funktioniert nicht mehr</p>
</blockquote>
<h2>Document</h2>
<details><summary>PB_Abrechnung_Orderabrechnung.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Postbank Köln · 51222 Köln&quot;,
    &quot;Jqbv&quot;,
    &quot;Xmnerie Lhmfrel&quot;,
    &quot;Kdvcdtklf Gms. 80&quot;,
    &quot;40035 Jprdtkx&quot;,
    &quot;Depotnummer&quot;,
    &quot;593251079&quot;,
    &quot;Kundennummer&quot;,
    &quot;1833832844&quot;,
    &quot;Oidkjjm Iwzhmmg&quot;,
    &quot;Auftragsnummer&quot;,
    &quot;246941/17.09&quot;,
    &quot;Datum&quot;,
    &quot;05.10.2020&quot;,
    &quot;Rechnungsnummer&quot;,
    &quot;U61085-6398784048/39&quot;,
    &quot;Umsatzsteuer-ID&quot;,
    &quot;LP552174530&quot;,
    &quot;6116.37920120.8977518KH29&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Wertpapier Abrechnung Ausgabe Investmentfonds&quot;,
    &quot;Auftrag vom 03.10.2020 00:33:39 Uhr&quot;,
    &quot;Nominale&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;ISIN&quot;,
    &quot;(WKN)&quot;,
    &quot;Stück 10,0402&quot;,
    &quot;VANGUARD FTSE ALL-WORLD U.ETF&quot;,
    &quot;REGISTERED SHARES USD DIS.ON&quot;,
    &quot;IE00B3RBWM25&quot;,
    &quot;(A1JX52)&quot;,
    &quot;Handels-/Ausführungsplatz&quot;,
    &quot;Außerbörslich (gemäß Weisung)&quot;,
    &quot;Schlusstag&quot;,
    &quot;05.10.2020&quot;,
    &quot;Ausführungskurs&quot;,
    &quot;79,68 EUR&quot;,
    &quot;Wertpapierrechnung Lagerland Grossbritannien&quot;,
    &quot;Kurswert&quot;,
    &quot;800,00-&quot;,
    &quot;EUR&quot;,
    &quot;Provision&quot;,
    &quot;0,90-&quot;,
    &quot;EUR&quot;,
    &quot;Ausmachender Betrag&quot;,
    &quot;800,90-&quot;,
    &quot;EUR&quot;,
    &quot;Sru Feayynilm axswzo dsu uwl Ztuwwn 77.04.2674 es Ibzaea ruo Oiomhu 7909013282&quot;,
    &quot;(QHUE FZ01 2746 8306 0294 9738 56), COJ 12605716 (LOQ HEMBUJVAJCV).&quot;,
    &quot;Die Wertpapiere schreiben wir Ihrem Depotkonto gut.&quot;,
    &quot;Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich um eine umsatzsteuerbefreite Finanzdienstleistung.&quot;,
    &quot;Gegenpartei bei diesem Geschäft war Börse Tradegate&quot;,
    &quot;ABR. OHNE AUSGABEAUFSCHLAG&quot;,
    &quot;IHR ETF-SPARPLAN NR.      1&quot;,
    &quot;Für das Geschäft wurde keine Anlageberatung erbracht.&quot;
  ]
]

</code></pre>
</p></details>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
See also #144
