### ISSUE TITLE
Postbank Import Dividende funktioniert nicht mehr

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#144]
<h2>Description</h2>
<blockquote>
<p>Postbank Import Dividende funktioniert nicht mehr</p>
</blockquote>
<h2>Document</h2>
<details><summary>PB_Abrechnung_ Fonds.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;5155.49788044.1347053ZM72&quot;,
    &quot;Postbank Köln · 51222 Köln&quot;,
    &quot;Gimm&quot;,
    &quot;Cuuiuvd Pjbwgkn&quot;,
    &quot;Kcqnqfcjl Hbn. 10&quot;,
    &quot;28932 Gwjthym&quot;,
    &quot;Depotnummer&quot;,
    &quot;433720767&quot;,
    &quot;Kundennummer&quot;,
    &quot;1122772457&quot;,
    &quot;Gxmpdde Cguzpwe&quot;,
    &quot;Abrechnungsnr.&quot;,
    &quot;03142844236&quot;,
    &quot;Datum&quot;,
    &quot;08.10.2020&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Bitte ggf. Rückseite beachten.&quot;,
    &quot;Ausschüttung Investmentfonds&quot;,
    &quot;Nominale&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;ISIN&quot;,
    &quot;(WKN)&quot;,
    &quot;Stück 131,8133&quot;,
    &quot;VANGUARD FTSE ALL-WORLD U.ETF&quot;,
    &quot;REGISTERED SHARES USD DIS.ON&quot;,
    &quot;IE00B3RBWM25&quot;,
    &quot;(A1JX52)&quot;,
    &quot;Zahlbarkeitstag&quot;,
    &quot;07.10.2020&quot;,
    &quot;Bestandsstichtag&quot;,
    &quot;23.09.2020&quot;,
    &quot;Ex-Tag&quot;,
    &quot;24.09.2020&quot;,
    &quot;Geschäftsjahr&quot;,
    &quot;01.07.2019 - 30.06.2020&quot;,
    &quot;Devisenkurs&quot;,
    &quot;EUR / USD  1,1798&quot;,
    &quot;Devisenkursdatum&quot;,
    &quot;08.10.2020&quot;,
    &quot;Ausschüttung pro St.&quot;,
    &quot;0,454628000&quot;,
    &quot;USD&quot;,
    &quot;mit Teilfreistellung (Aktien-&quot;,
    &quot;fonds)&quot;,
    &quot;0,318239600&quot;,
    &quot;USD&quot;,
    &quot;Herkunftsland&quot;,
    &quot;Irland&quot;,
    &quot;Ausschüttung&quot;,
    &quot;59,93&quot;,
    &quot;USD&quot;,
    &quot;50,80+&quot;,
    &quot;EUR&quot;,
    &quot;davon steuerfreier Anteil wg. Teilfreistellung&quot;,
    &quot;17,98&quot;,
    &quot;USD&quot;,
    &quot;Kapitalertragsteuerpfl. Ertrag nach Teilfreistellung&quot;,
    &quot;41,95&quot;,
    &quot;USD&quot;,
    &quot;Umrechnung in EUR&quot;,
    &quot;35,56&quot;,
    &quot;EUR&quot;,
    &quot;Verrechneter Sparer-Pauschbetrag&quot;,
    &quot;35,56&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;Berechnungsgrundlage für die Kapitalertragsteuer&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;Ausmachender Betrag&quot;,
    &quot;50,80+&quot;,
    &quot;EUR&quot;,
    &quot;Lagerstelle Clearstream Banking Lux (849133 / 64003)&quot;,
    &quot;Wly Qcbxbw pomikz bly zfs Cvkmjbsctcoz 47.61.3474 jh Mzvmojf bdi Moeluq 740462681 (LSHT VD05 7052 5972 2913 9688&quot;,
    &quot;65), OPX 995 717 49 (VMR JNJIWBMTTJL).&quot;,
    &quot;Keine Steuerbescheinigung.&quot;,
    &quot;Nachrichtlich die Übersicht Ihrer Verrechnungs- und Steuertopfsalden zum Zeitpunkt der Erstellung der Abrechnung.&quot;,
    &quot;Verrechnungstöpfe 2020&quot;,
    &quot;Berechnungsgrundlage&quot;,
    &quot;der gezahlten Steuern&quot;,
    &quot;Euro&quot;,
    &quot;Aktien&quot;,
    &quot;Sonstige&quot;,
    &quot;Sparer-&quot;,
    &quot;Pauschbetrag&quot;,
    &quot;anrechenbare&quot;,
    &quot;Quellensteuer&quot;,
    &quot;Aktien&quot;,
    &quot;Sonstige&quot;,
    &quot;Nachher&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;319,28&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;
  ],
  []
]

</code></pre>
</p></details>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by SirGibihm** [comment]
Derzeit existiert kein Postbank Parser oder übersehe ich da etwas? Dementsprechend eher Feature Request als Bug.

**Comment by codeofsumit** [comment]
https://github.com/codeofsumit/tresor-import/blob/master/src/brokers/postbank.js

**Comment by dredav** [comment]
@SirGibihm Tests haben wir leider noch keine für die Postbank, wenn du das Issue hier anschaust, kannst du dann auch noch #56 anschauen?
