### ISSUE TITLE
Can't commit anymore

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#159]
Hi all, I'm trying since half an hour to commit something but the precommit hook won't let me.

First problem was husky not using the proper node version. Fixed that.
Now `npm audit` is annoying me. `npm audit fix` is not helping, upgrading the dependency myself doesn't help either. `npm update` will break everything.

How do you guys commit?

**Comment by dredav** [comment]
@codeofsumit  You can skip the precommit hook at the moment (until we fixed the audit thing by replacing `uglifyjs-webpack-plugin`) with the argument `--no-verify`: `git commit --no-verify -m "Lorem ipsum"`

**Comment by codeofsumit** [comment]
Hm, that won't work for me. To create releases and changelogs, I have other scripts that commit e.g. the new version tags and those scripts fail now. Removed the audit from the hook now.
