### ISSUE TITLE
Support Multiple Pages

### ISSUE THREAD

**Issue by hija** [codeofsumit/tresor-import#16]
(English version below)

Onvista kombiniert z.T. mehrere Abrechnungen in ein Dokument, wodurch eine PDF mit mehreren Seiten entsteht. Derzeit lesen wir nur die erste Seite ein (https://github.com/codeofsumit/tresor-import/blob/45719c7e7cf65c9c79466122997265144ba8d441/src/index.js#L38).

Frage:

- Können wir annehmen, dass eine Seite in der PDF mit einer Abrechnung gleichzusetzen ist? Dann könnten wir die Extraktionsfunktion einmal pro Seite anwenden. Oder gibt es Broker, bei denen eine Abrechnung über mehrere Seiten geht?

---

Onvista sometimes combines multiple bills into one document, i.e. resulting in a pdf with multiple pages.

Currently we are just reading in the first page (https://github.com/codeofsumit/tresor-import/blob/45719c7e7cf65c9c79466122997265144ba8d441/src/index.js#L38). 

Question:

- Should we assume that one page in a document corresponds to one bill (Abrechnung), so that we just execute our extraction function for every single page in the document? Or are there cases in which one bill is longer than one page and thus this would break functionality?

---

**Comment by bauerj** [comment]
Ich denke dieses Vorgehen wäre sinnvoll:

1. Alle Seiten einlesen
2. Die Broker-Erkennung auf der ersten Seite ausführen
3. Alle Seiten an den Broker-Handler geben

Für jeden Broker könnte dann individuell festgelegt werden was für eine Bedeutung hinter den einzelnen Seiten steckt

**Comment by hija** [comment]
Wollen wir dann ein Array von Arrays machen?

[[Seite1-Array],[Seite2-Array],...] oder habt ihr bessere Ideen? Dann bleibt die Information vorhanden, welche Information auf welcher Seite steht :)

**Comment by bauerj** [comment]
Klingt gut 👍

**Comment by hija** [comment]
@codeofsumit Wärst du damit einverstanden?

**Comment by codeofsumit** [comment]
Klar - dann sollte getPage und alles danach entsprechend in einem Loop durchgehen und alle Ergebnisse in einem Array von Activities (Collection) speichern.

Für Comdirect und Traderepublic kann man das ja ebenfalls in `index.js` anpassen indem man `[activity]` zurück gibt.

Bin gespannt 👍  - mega, dass ihr da so dabei seid!

**Comment by codeofsumit** [comment]
Ich kann das angehen aber ich brauche eine Beispiel PDF - kann mir jemand eine an sumit@tresor.one schicken? Dann kümmere ich mich drum dass mehrere PDFs ausgelesen werden

**Comment by carstenhag** [comment]
Soo leute lasst uns hier mal weitermachen. Hab leider keine PDF mit meheren Seiten, @hija hast du vielleicht eins?

**Comment by hija** [comment]
Seite 1 und Seite 2 sind eins-zu-eins identisch. Man kann einen beliebigen PDF-Merger nutzen und zwei Dokumente mergen. 

Aus Datenschutzgründen würde ich ungern meine Abrechnung hier online stellen. 

@codeofsumit willst du einfach zwei PDFs mergen und das dann selbst implementieren oder soll ich dir eine Abrechnung von mir schicken mit der Bitte, dass du die Datei oder Informationen daraus nicht veröffentlichst? :)

**Comment by codeofsumit** [comment]
@hija guter Punkt. So könnte man es machen.
@carstenhag kannst du zwei PDFs deiner Abrechnungen mergen und das angehen? Bin aktuell noch busy mit dem nächsten Release und komm vor nächster Woche nicht dazu

**Comment by carstenhag** [comment]
Habe dir gerade 15 PDFs geschickt. Habe schon länger nichts mehr in JS gemacht und das Wochenende ist schon vorbei, frühestens könnte ich mir als nächsten Samstag was anschauen. 

@hija Ich denke mal du hast schon einige PDFs, wenn du möchtest, kann ich dir aber meine auch noch schicken.

**Comment by carstenhag** [comment]
Gerade was probiert, aber js ohne Typen frustriert mich ziemlich... Ich weiß einfach nicht wo hinten und vorne ist ohne Typen, und dann noch mit async/await... 😢

**Comment by codeofsumit** [comment]
😂 da die Mammut Nummer jetzt deployed ist kann ich wieder ran hier an den Import

**Comment by codeofsumit** [comment]
@hija @bauerj @carstenhag 
schaut gerne mal drüber: https://github.com/codeofsumit/tresor-import/pull/30
