### ISSUE TITLE
Bei Dividenden muss der Amount der Brutto-Wert sein

### ISSUE THREAD

**Issue by dredav** [codeofsumit/tresor-import#160]
- Bei Trade Republic wird der Amount in der aktuellen Version als Netto-Wert angegeben.
- Bitte alle anderen Brokers prüfen
- Weitere Informationen und die Diskussion dazu: https://community.tresor.one/c/help/trade-republic-dividende-falsche-berechnung-der-quellensteuer

Wenn der fix live ist bitte Milaan aus der Comminuty informieren: https://community.tresor.one/u/383ad5f6

**Comment by SirGibihm** [comment]
Just to make sure, you always want amount to be the gross amount, not the net amount for Dividends, Sells, and Buys?

**Comment by codeofsumit** [comment]
No. Think of it this way, all amounts are from a portfolio perspective, NOT a bank accounts perspective. 

The total amount for Buy is what was actually put into the stock. That means it does not include taxes or fees. 
For a Sell it is what the stock was sold for - that means it includes fees and taxes. 

That's also how it is on the PDFs. 

One helper is that this always has to be true:

Price (or Dividend) * Shares = Amount

**Comment by SirGibihm** [comment]
Got it, thank you.   There is one weird edge-case that I still have a question about: For Comdirect buys, it can be possible to have a "negative" fee in which you are billed 24.84€ but receive 25.39€ in stocks, see the testfile ```comdirect/buy/savings_plan.json```. Currently, it is not allowed to have negative fees (validation fails) and instead this negative fee is just dropped from the equation. Thus, the amount is set to 24.84€. However, this is not what the "depot sees", it sees 25.39€. Should we adjust the validation function to allow for this?

**Comment by SirGibihm** [comment]
Pull request #163 should fix these issues.

**Comment by SirGibihm** [comment]
I got the feeling that several other issues are somewhat related to this issue or would cause merge issues i. e.  #148 #164

**Comment by dredav** [comment]
>Got it, thank you. There is one weird edge-case that I still have a question about: For Comdirect buys, it can be possible to have a "negative" fee in which you are billed 24.84€ but receive 25.39€ in stocks, see the testfile comdirect/buy/savings_plan.json. Currently, it is not allowed to have negative fees (validation fails) and instead this negative fee is just dropped from the equation. Thus, the amount is set to 24.84€. However, this is not what the "depot sees", it sees 25.39€. Should we adjust the validation function to allow for this?

In the sample `comdirect/buy/savings_plan.json` I can't find a negativ fee, or did I miss something @SirGibihm?

**Comment by SirGibihm** [comment]
> 
> In the sample `comdirect/buy/savings_plan.json` I can't find a negativ fee, or did I miss something @SirGibihm?

Its in sample `comdirect/buy/savings_plan.json` only. [here](https://github.com/codeofsumit/tresor-import/blob/master/tests/brokers/__mocks__/comdirect/buy/purchase_reduction.json#L26) you can see "Kurswert EUR 25,39". However, the user is billed 24.84€, see [here](https://github.com/codeofsumit/tresor-import/blob/master/tests/brokers/__mocks__/comdirect/buy/purchase_reduction.json#L128)
