### ISSUE TITLE
[Consorsbank] Import fehlgeschlagen

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#161]
<h2>Description</h2>
<blockquote>
<p>T1 meldet &quot;1 AKTIVITÄT BRAUCHT DEINE HILFE!&quot; zeigt dann allerdings nichts an was zu korrigieren wäre.</p>
</blockquote>
<h2>Documents</h2>
<details><summary>2020-09-30 Dividende (2020-09-02).1.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;Iotcze Zekla&quot;,
    &quot;Piwlnpxr. 91h&quot;,
    &quot;99292 Qügazfk&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;9771836094&quot;,
    &quot;0019440826/36&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;1000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;06.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Dividendengutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;PEPSICO&quot;,
    &quot;INC. Registered Shares DL -,0166&quot;,
    &quot;851995&quot;,
    &quot;US7134481081&quot;,
    &quot;Bestand&quot;,
    &quot;0,20467 Stück&quot;,
    &quot;Dividende pro Stück 1,0225 USD&quot;,
    &quot;Schlusstag 02.09.2020&quot;,
    &quot;Brutto in USD&quot;,
    &quot;0,21 USD&quot;,
    &quot;abzgl. Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,21 USD&quot;,
    &quot;0,03 USD&quot;,
    &quot;Netto in USD&quot;,
    &quot;0,18 USD&quot;,
    &quot;Devisenkurs&quot;,
    &quot;1,178600 USD / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;0,18 EUR&quot;,
    &quot;Quellensteuer in EUR&quot;,
    &quot;0,03 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;QOUQ&quot;,
    &quot;FT29 0919 0257&quot;,
    &quot;9310 6103 50&quot;,
    &quot;0,15 EUR&quot;,
    &quot;Valuta 30.09.2020&quot;,
    &quot;BIC&quot;,
    &quot;CSDBDE71XXX&quot;,
    &quot;Anrechenbare Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,21 USD&quot;,
    &quot;0,03&quot;,
    &quot;EUR&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;0,18 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;-0,18 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;62,01 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;-0,18 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;61,83 EUR&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;26,22 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;26,22 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;2,24 EUR&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;0,03 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;2,27 EUR&quot;,
    &quot;Depotnummer:&quot;,
    &quot;8825722761&quot;,
    &quot;5307395359/77&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;1000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;06.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;
  ]
]

</code></pre>
</p></details>
<details><summary>2020-09-30 Dividende (2020-09-02).2.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;Yomyoa Vrsaw&quot;,
    &quot;Jrnojozd. 45j&quot;,
    &quot;28947 Züuhlox&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;6446579399&quot;,
    &quot;1849384820/69&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;1000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;06.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Dividendengutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;PEPSICO&quot;,
    &quot;INC. Registered Shares DL -,0166&quot;,
    &quot;851995&quot;,
    &quot;US7134481081&quot;,
    &quot;Bestand&quot;,
    &quot;0,92499 Stück&quot;,
    &quot;Dividende pro Stück 1,0225 USD&quot;,
    &quot;Schlusstag 02.09.2020&quot;,
    &quot;Brutto in USD&quot;,
    &quot;0,95 USD&quot;,
    &quot;abzgl. Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,95 USD&quot;,
    &quot;0,14 USD&quot;,
    &quot;Netto in USD&quot;,
    &quot;0,81 USD&quot;,
    &quot;Devisenkurs&quot;,
    &quot;1,178600 USD / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;0,81 EUR&quot;,
    &quot;Quellensteuer in EUR&quot;,
    &quot;0,12 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;IBAN&quot;,
    &quot;JG95 8613 5257&quot;,
    &quot;0716 7299 70&quot;,
    &quot;0,69 EUR&quot;,
    &quot;Valuta 30.09.2020&quot;,
    &quot;BIC&quot;,
    &quot;FWAFDC12NGS&quot;,
    &quot;Anrechenbare Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,95 USD&quot;,
    &quot;0,12&quot;,
    &quot;EUR&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;0,81 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;-0,81 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;61,83 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;-0,81 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;61,02 EUR&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;26,22 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;26,22 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;2,27 EUR&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;0,12 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;2,39 EUR&quot;,
    &quot;Depotnummer:&quot;,
    &quot;9096629400&quot;,
    &quot;0249999548/35&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;1000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;06.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/383ad5f6</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Fixed with #142. Fix will deployed soon.
