### ISSUE TITLE
Trade Republic Dividendenabrechnung wird nicht importiert

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#165]
<h2>Description</h2>
<blockquote>
<p>Siehe oben. Ist nicht nur bei mir der Fall</p>
</blockquote>
<h2>Document</h2>
<details><summary>pb16031008133063193089312597683.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;TRADE REPUBLIC BANK GMBH&quot;,
    &quot;KASTANIENALLEE 32&quot;,
    &quot;10435 BERLIN&quot;,
    &quot;xxxx xxxxx&quot;,
    &quot;xxxx x&quot;,
    &quot;D xxx xxx&quot;,
    &quot;SEITE&quot;,
    &quot;1&quot;,
    &quot;von&quot;,
    &quot;1&quot;,
    &quot;DATUM&quot;,
    &quot;19.10.2020&quot;,
    &quot;DEPOT&quot;,
    &quot;123456789&quot;,
    &quot;Trade Republic Bank GmbH&quot;,
    &quot;Kastanienallee 32&quot;,
    &quot;10435 Berlin&quot;,
    &quot;www.traderepublic.com&quot;,
    &quot;odggegi@oocgfpunyemab.tkz&quot;,
    &quot;Sitz der Gesellschaft: Düsseldorf&quot;,
    &quot;AG Düsseldorf HRB 85864&quot;,
    &quot;USt-ID DE307510626&quot;,
    &quot;Geschäftsführer&quot;,
    &quot;Andreas Willius&quot;,
    &quot;Karsten Müller&quot;,
    &quot;ABRE / 2020-10-19 / 98336624 / ad01-e337&quot;,
    &quot;DIVIDENDE&quot;,
    &quot;ÜBERSICHT&quot;,
    &quot;Dividende mit dem Ex-Tag 02.10.2020.&quot;,
    &quot;POSITION&quot;,
    &quot;ANZAHL&quot;,
    &quot;ERTRÄGNIS&quot;,
    &quot;BETRAG&quot;,
    &quot;McCormick &amp; Co. Inc.&quot;,
    &quot;Reg. Shares (Non Voting) o.N.&quot;,
    &quot;ISIN: US5797802064&quot;,
    &quot;0,1471 Stk.&quot;,
    &quot;0,62 USD&quot;,
    &quot;0,09 USD&quot;,
    &quot;GESAMT&quot;,
    &quot;0,09 USD&quot;,
    &quot;ABRECHNUNG&quot;,
    &quot;POSITION&quot;,
    &quot;BETRAG&quot;,
    &quot;Quellensteuer DE für US-Emittent&quot;,
    &quot;-0,01 USD&quot;,
    &quot;Zwischensumme&quot;,
    &quot;0,08 USD&quot;,
    &quot;Zwischensumme&quot;,
    &quot;1,1723 EUR/USD&quot;,
    &quot;0,07 EUR&quot;,
    &quot;Kapitalertragssteuer&quot;,
    &quot;-0,01 EUR&quot;,
    &quot;GESAMT&quot;,
    &quot;0,06 EUR&quot;,
    &quot;BUCHUNG&quot;,
    &quot;VERRECHNUNGSKONTO&quot;,
    &quot;VALUTA&quot;,
    &quot;BETRAG&quot;,
    &quot;EL10685783006346232350&quot;,
    &quot;19.10.2020&quot;,
    &quot;0,06 EUR&quot;,
    &quot;McCormick &amp; Co. Inc. Reg. Shares (Non Voting) o.N. in Wertpapierrechnung.&quot;,
    &quot;Lagerland: USA&quot;,
    &quot;Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.&quot;,
    &quot;Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie&quot;,
    &quot;Leistung.&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>tresor.one/portfolio/5f58f41870b4990008262d9e</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Der Fehler war nicht im Import sondern in T1 Core. Daher kann das Issue geschlossen werden.
