### ISSUE TITLE
Dokument kann nicht importiert werden

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#168]
<h2>Description</h2>
<blockquote>
<p>der Wertpapierkauf bei comdirect kann mittels 0 Klick Import nicht importiert werden</p>
</blockquote>
<h2>Document</h2>
<details><summary>Wertpapierabrechnung_Kauf_70_St._WKN_531350(ENERGIEKONTOR_O.N.)_vom_19.10.202019470D.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;*&quot;,
    &quot;Telefon   :&quot;,
    &quot;04106-708 25 00&quot;,
    &quot;xxxxxxxx&quot;,
    &quot;xxxxxx&quot;,
    &quot;xxxxx xxxxx&quot;,
    &quot;010&quot;,
    &quot;xxxxx&quot;,
    &quot;Depotnr.:&quot;,
    &quot;xxxxxxx 00&quot;,
    &quot;BLZ:&quot;,
    &quot;200 411 55&quot;,
    &quot;GESCHÄFTSABRECHNUNG VOM&quot;,
    &quot;19.10.2020&quot;,
    &quot;Wertpapierkauf&quot;,
    &quot;Geschäftsnummer   : 92 123123&quot;,
    &quot;Ordernummer       : 00012312373-001  Rechnungsnummer   : 123123123123DC65&quot;,
    &quot;Geschäftstag      : 19.10.2020        Ausführungsplatz  : TRADEGATE&quot;,
    &quot;Handelszeit       : 15:46 Uhr (MEZ/MESZ)                  (Kommissionsgeschäft)&quot;,
    &quot;Wertpapier-Bezeichnung                                               WPKNR/ISIN&quot;,
    &quot;Energiekontor AG                                                         531350&quot;,
    &quot;Inhaber-Aktien o.N.                                                DE0005313506&quot;,
    &quot;Nennwert                  Zum Kurs von&quot;,
    &quot;St.  70                   EUR  36,90&quot;,
    &quot;Kurswert                    : EUR            2.583,00&quot;,
    &quot;--------------------------------------------------------------------------------&quot;,
    &quot;Eigene Entgelte&quot;,
    &quot;Provision                   : EUR               11,36&quot;,
    &quot;Börsenplatzabhäng. Entgelt  : EUR                2,50&quot;,
    &quot;Summe Entgelte              : EUR               13,86&quot;,
    &quot;--------------------------------------------------------------------------------&quot;,
    &quot;IBAN                                  Valuta         Zu Ihren Lasten vor Steuern&quot;,
    &quot;DE85 1233 1234 1234 1234 40   EUR     21.10.2020        EUR            2.596,86&quot;,
    &quot;Verwahrungs-Art: GIROSAMMELDEPOT&quot;,
    &quot;GLOBALURKUNDE, KEIN STUECKEAUSDRUCK&quot;,
    &quot;Ihre Wertpapier-Order wurde über das Online Banking erteilt.&quot;,
    &quot;Informationen zur steuerlichen Behandlung dieses Geschäftsvorgangs und den auf&quot;,
    &quot;Ihrem Konto gebuchten Endbetrag finden Sie auf der separaten Steuermitteilung.&quot;,
    &quot;Bei Fragen geben Sie bitte die Ordernummer an.&quot;,
    &quot;comdirect bank AG&quot;,
    &quot;Diese Abrechnung wird von der Bank nicht unterschrieben&quot;,
    &quot;Die Leistung ist gemäß §4 Nr.8 UStG umsatzsteuerfrei. USt-Id-Nr.: DE 812 279 461&quot;,
    &quot;25449&quot;,
    &quot;Quickborn&quot;,
    &quot;Ihren&quot;,
    &quot;Auftrag&quot;,
    &quot;haben&quot;,
    &quot;wir&quot;,
    &quot;gemäß&quot;,
    &quot;unseren&quot;,
    &quot;produktbezogenen&quot;,
    &quot;Geschäftsbedingungen&quot;,
    &quot;\&quot;Trading\&quot;&quot;,
    &quot;wie&quot;,
    &quot;nachstehend&quot;,
    &quot;ausgeführt.&quot;,
    &quot;Die&quot;,
    &quot;Wertpapiere&quot;,
    &quot;haben&quot;,
    &quot;wir&quot;,
    &quot;der&quot;,
    &quot;Abrechnung&quot;,
    &quot;entsprechend&quot;,
    &quot;gebucht.&quot;,
    &quot;Wir&quot;,
    &quot;bitten&quot;,
    &quot;Sie,&quot;,
    &quot;diese&quot;,
    &quot;Abrechnung&quot;,
    &quot;auf&quot;,
    &quot;ihre&quot;,
    &quot;Richtigkeit&quot;,
    &quot;und&quot;,
    &quot;Vollständigkeit&quot;,
    &quot;zu&quot;,
    &quot;überprüfen&quot;,
    &quot;und&quot;,
    &quot;etwaige&quot;,
    &quot;Einwendungen&quot;,
    &quot;unverzüglich&quot;,
    &quot;zu&quot;,
    &quot;erheben.&quot;,
    &quot;A113&quot;,
    &quot;DO15DD/16/04/2010&quot;
  ],
  [
    &quot;Kundennr.&quot;,
    &quot;/BLZ&quot;,
    &quot;Bezeichnung&quot;,
    &quot;abweichend&quot;,
    &quot;wirtschaftlich&quot;,
    &quot;Berechtigter&quot;,
    &quot;xxxxxxxx&quot;,
    &quot;xxxxxxxxx&quot;,
    &quot;xxxxx xxxxx&quot;,
    &quot;----&quot;,
    &quot;123451234&quot;,
    &quot;200 123 12&quot;,
    &quot;KEINE STEUERBESCHEINIGUNG&quot;,
    &quot;...&quot;,
    &quot;comdirect bank AG&quot;,
    &quot;25451 Quickborn&quot;,
    &quot;Telefon:&quot;,
    &quot;04106 - 708 25 00&quot;,
    &quot;Datum:&quot;,
    &quot;19.10.2020&quot;,
    &quot;Referenz-Nummer:&quot;,
    &quot;2&quot;,
    &quot;ABC3TW123N12345&quot;,
    &quot;Depotnummer:&quot;,
    &quot;123456 00&quot;,
    &quot;Herrn&quot;,
    &quot;xxxxxxxx&quot;,
    &quot;xxxxxxxxx&quot;,
    &quot;xxxxx xxxxx&quot;,
    &quot;010&quot;,
    &quot;12345&quot;,
    &quot;Steuerliche Behandlung: Wertpapierkauf Nr. 1234567 vom 19.10.2020&quot;,
    &quot;Stk.              70 ENERGIEKONTOR O.N. , WKN / ISIN: 531350  / DE0005313506&quot;,
    &quot;Zu Ihren Lasten vor Steuern:&quot;,
    &quot;EUR         -2.596,86&quot;,
    &quot;Steuerbemessungsgrundlage&quot;,
    &quot;EUR              0,00&quot;,
    &quot;Kapitalertragsteuer&quot;,
    &quot;EUR              0,00&quot;,
    &quot;Solidaritätszuschlag&quot;,
    &quot;EUR              0,00&quot;,
    &quot;Kirchensteuer&quot;,
    &quot;EUR              0,00&quot;,
    &quot;_____________________&quot;,
    &quot;abgeführte Steuern&quot;,
    &quot;EUR              0,00&quot;,
    &quot;_____________________&quot;,
    &quot;Zu Ihren Lasten nach Steuern:&quot;,
    &quot;EUR         -2.596,86&quot;,
    &quot;Die Belastung erfolgt mit Valuta 21.10.2020 auf Konto EUR mit der IBAN ML55 1379 4715 8239 8927 35&quot;,
    &quot;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&quot;
  ],
  [
    &quot;Bisher&quot;,
    &quot;einbehaltene&quot;,
    &quot;bzw.&quot;,
    &quot;angerechnete&quot;,
    &quot;Steuer&quot;,
    &quot;in&quot;,
    &quot;EUR&quot;,
    &quot;(4)&quot;,
    &quot;Verrechnungssalden&quot;,
    &quot;in&quot;,
    &quot;EUR&quot;,
    &quot;(4)&quot;,
    &quot;in&quot;,
    &quot;vor&quot;,
    &quot;Ermittlung&quot;,
    &quot;nach&quot;,
    &quot;Ermittlung&quot;,
    &quot;einbehaltene&quot;,
    &quot;Kapitalertragsteuer&quot;,
    &quot;Solidaritätszuschlag&quot;,
    &quot;einbehaltene&quot;,
    &quot;Kirchensteuer&quot;,
    &quot;angerechnete&quot;,
    &quot;ausländische&quot;,
    &quot;Quellensteuer&quot;,
    &quot;vor&quot;,
    &quot;Ermittlung&quot;,
    &quot;nach&quot;,
    &quot;Ermittlung&quot;,
    &quot;aus&quot;,
    &quot;Aktien&quot;,
    &quot;sonstige&quot;,
    &quot;Gewinne&quot;,
    &quot;/&quot;,
    &quot;Verluste&quot;,
    &quot;anrechenbare&quot;,
    &quot;ausländische&quot;,
    &quot;Quellensteuer&quot;,
    &quot;verfügbarer&quot;,
    &quot;Freistellungsauftrag&quot;,
    &quot;einbehaltener&quot;,
    &quot;Gewinne&quot;,
    &quot;/&quot;,
    &quot;Verluste&quot;,
    &quot;2020&quot;,
    &quot;1.467,57&quot;,
    &quot;1.467,57&quot;,
    &quot;80,53&quot;,
    &quot;80,53&quot;,
    &quot;117,23&quot;,
    &quot;117,23&quot;,
    &quot;261,25&quot;,
    &quot;261,25&quot;,
    &quot;KEINE STEUERBESCHEINIGUNG&quot;,
    &quot;2020&quot;,
    &quot;in&quot;,
    &quot;3.643,59&quot;,
    &quot;3.643,59&quot;,
    &quot;3.388,89&quot;,
    &quot;3.388,89&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;comdirect bank AG&quot;,
    &quot;Diese Abrechnung ist maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;(4) Die ausgewiesenen EUR-Beträge spiegeln den Stand zum Abrechnungszeitpunkt wider.&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>Michael Keser</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Waiting for user feedback before final triage. Document can be parse on my side. Discussion: https://community.tresor.one/c/help/pdf-import-comdirect-keine-reaktion
