### ISSUE TITLE
Consors Bank 

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#171]
<h2>Description</h2>
<blockquote>
<p>Dieser Dividenden PDF wird nicht erkannt wenn ich ihn importieren will.</p>
</blockquote>
<h2>Document</h2>
<details><summary>DIVIDENDENGUTSCHRIFT_938596851_wkn851921_dat20201020_id919410752.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;Cxyv Nvyhslhg&quot;,
    &quot;Qvhplw-Vkmse-Zbi. 46f&quot;,
    &quot;88582 Cpswchkn&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;1474040989&quot;,
    &quot;4947452429/45&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;2000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;20.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Dividendengutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;OCCIDENTAL PETROLEUM&quot;,
    &quot;CORP. Registered Shares DL -,20&quot;,
    &quot;851921&quot;,
    &quot;US6745991058&quot;,
    &quot;Bestand&quot;,
    &quot;560 Stück&quot;,
    &quot;Dividende pro Stück 0,01 USD&quot;,
    &quot;Schlusstag 13.09.2020&quot;,
    &quot;Brutto in USD&quot;,
    &quot;5,60 USD&quot;,
    &quot;abzgl. Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;5,60 USD&quot;,
    &quot;0,84 USD&quot;,
    &quot;Zwischensumme in USD&quot;,
    &quot;4,76 USD&quot;,
    &quot;Devisenkurs&quot;,
    &quot;1,184300 USD / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;4,73 EUR&quot;,
    &quot;Quellensteuer in EUR&quot;,
    &quot;0,71 EUR&quot;,
    &quot;Zwischensumme in EUR&quot;,
    &quot;4,02 EUR&quot;,
    &quot;abzgl. Kapitalertragsteuer&quot;,
    &quot;25,00 % von&quot;,
    &quot;1,89 EUR&quot;,
    &quot;0,47 EUR&quot;,
    &quot;abzgl. Solidaritätszuschlag&quot;,
    &quot;5,50 % von&quot;,
    &quot;0,47 EUR&quot;,
    &quot;0,02 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;IBAN&quot;,
    &quot;LR30 6900 2699&quot;,
    &quot;2126 4460 39&quot;,
    &quot;3,53 EUR&quot;,
    &quot;Valuta 15.10.2020&quot;,
    &quot;BIC&quot;,
    &quot;CSDBDE71XXX&quot;,
    &quot;Anrechenbare Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;5,60 USD&quot;,
    &quot;0,71&quot;,
    &quot;EUR&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;4,73 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;-2,84 EUR&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;-0,71 EUR&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;1,89 EUR&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Depotnummer:&quot;,
    &quot;0938596851&quot;,
    &quot;1001058579/00&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;2000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;20.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://tresor.one/portfolio/5f82ca9736ae2d002f53f7f2#</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
I reference the wrong issue in the commit message... I repoen this issue again.

**Comment by SirGibihm** [comment]
I can not replicate any issue. Might have been fixed allready by #160 or #142. Will contact the user if the issue is still present
