### ISSUE TITLE
Ertragsgutschriften nicht importierbar Consorsbank

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#172]
<h2>Description</h2>
<blockquote>
<p>Die Ertragsgutschriften bei der Consorsbank sind nicht importierbar.
Der Import bleibt im Bild mit kompatiblen Brokern stehen.</p>
</blockquote>
<p>Es Betrift z.B. LTC Properties und AGNC Investment.</p>
<h2>Document</h2>
<details><summary>ERTRAGSGUTSCHRIFT_878641213_wkn884625_dat20190502_id776469860.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;Gzxmgcv Udhif&quot;,
    &quot;Gqfwhgo-Xrgfg-Zon. 64&quot;,
    &quot;09394 Dzrcx&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;1275229953&quot;,
    &quot;6170587500/41&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;3666&quot;,
    &quot;0&quot;,
    &quot;Datum:&quot;,
    &quot;02.05.2019&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Ertragsgutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;LTC PROPERTIES INC. Registered Shares DL -,01&quot;,
    &quot;884625&quot;,
    &quot;US5021751020&quot;,
    &quot;Bestand&quot;,
    &quot;53 Ukügk&quot;,
    &quot;Ertragsausschüttung je Anteil 0,19 USD&quot;,
    &quot;Schlusstag 17.04.2019&quot;,
    &quot;Brutto in USD&quot;,
    &quot;1,30 VFM&quot;,
    &quot;abzgl. Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,82 WDB&quot;,
    &quot;7,05 ORI&quot;,
    &quot;Netto in USD&quot;,
    &quot;7,59 XWB&quot;,
    &quot;Devisenkurs&quot;,
    &quot;1,123200 USD / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;8,48 VMH&quot;,
    &quot;Quellensteuer in EUR&quot;,
    &quot;1,22 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;IBAN&quot;,
    &quot;BO44 2949 2619&quot;,
    &quot;1574 4022 01&quot;,
    &quot;5,09 JTX&quot;,
    &quot;Valuta 30.04.2019&quot;,
    &quot;BIC&quot;,
    &quot;FHUNCK81WUT&quot;,
    &quot;Anrechenbare Quellensteuer&quot;,
    &quot;0,0285 USD pro Stück&quot;,
    &quot;1,22&quot;,
    &quot;EUR&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;9,16 KHZ&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;5,49 VKA&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;-9,21 GZG&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;9,39 QPB&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;5,60 XOA&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;5,19 MRY&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;7,38 ZAT&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;3,15 TJF&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;2,31 FAI&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;403,93 NVO&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;-8,63 DPK&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;689,75 NGL&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;43,64 MOU&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;7,52 YGM&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;49,16 EHS&quot;,
    &quot;Depotnummer:&quot;,
    &quot;3621841041&quot;,
    &quot;4374742450/34&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;2000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;02.05.2019&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;,
    &quot;Informationen zum&quot;,
    &quot;Investmentsteuergesetz&quot;,
    &quot;Ausschüttung gem. §2 Abs. 11 InvStG&quot;,
    &quot;5,23 ERQ&quot;,
    &quot;abzgl. Teilfreistellung&quot;,
    &quot;5,84 % hjq 0,84 EXB&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Ertragsausschüttung mit Teilfreistellung&quot;,
    &quot;1,10 RIY&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/ed4e41fd</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
The description sounds like an T1 Core issue because the supported broker view before the drop handle will not disappear. [Community Discussion](https://community.tresor.one/c/help/abrechnung-hochladen-geht-nicht)
