### ISSUE TITLE
[Consorsbank] Ertragsgutschrift Import 

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#178]
<h2>Description</h2>
<blockquote>
<p>Es wird der Schlusstag anstatt der Valuta-Tag importiert</p>
</blockquote>
<h2>Document</h2>
<details><summary>ERTRAGSGUTSCHRIFT_898509160_wkn899744_dat20201020_id919407415.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;Max Mustermann&quot;,
    &quot;XX XXX XXXXXXXXXX XX&quot;,
    &quot;XXXXX XXXXXXXXXXX&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;XXXXXXXXXX&quot;,
    &quot;XXXXXXXXXX/00&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;1000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;20.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Ertragsgutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;REALTY INCOME CORP. Registered Shares DL 1&quot;,
    &quot;899744&quot;,
    &quot;US7561091049&quot;,
    &quot;Bestand&quot;,
    &quot;15 Stück&quot;,
    &quot;Ertragsausschüttung je Anteil 0,234 USD&quot;,
    &quot;Schlusstag 29.09.2020&quot;,
    &quot;Brutto in USD&quot;,
    &quot;3,51 USD&quot;,
    &quot;abzgl. Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;3,51 USD&quot;,
    &quot;0,53 USD&quot;,
    &quot;Netto in USD&quot;,
    &quot;2,98 USD&quot;,
    &quot;Devisenkurs&quot;,
    &quot;1,184300 USD / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;2,96 EUR&quot;,
    &quot;Quellensteuer in EUR&quot;,
    &quot;0,45 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;IBAN&quot;,
    &quot;DEXX XXXX XXXX&quot;,
    &quot;XXXX XXXX XX&quot;,
    &quot;2,52 EUR&quot;,
    &quot;Valuta 15.10.2020&quot;,
    &quot;BIC&quot;,
    &quot;CSDBDE71XXX&quot;,
    &quot;Anrechenbare Quellensteuer&quot;,
    &quot;0,0351 USD pro Stück&quot;,
    &quot;0,45&quot;,
    &quot;EUR&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;2,96 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;-2,96 EUR&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;161,09 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;-2,96 EUR&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;158,13 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;46,06 EUR&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;0,45 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;46,51 EUR&quot;,
    &quot;Depotnummer:&quot;,
    &quot;XXXXXXXXXX&quot;,
    &quot;XXXXXXXXXX/00&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;1000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;20.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;,
    &quot;Informationen zum&quot;,
    &quot;Investmentsteuergesetz&quot;,
    &quot;Ausschüttung gem. §2 Abs. 11 InvStG&quot;,
    &quot;2,96 EUR&quot;,
    &quot;abzgl. Teilfreistellung&quot;,
    &quot;0,00 % von 2,96 EUR&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Ertragsausschüttung mit Teilfreistellung&quot;,
    &quot;2,96 EUR&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/b900d5a6</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
This is an follow up from the [community discussion](https://community.tresor.one/c/feature-ideas/ertragsgutschrift-nicht-importierbar-consorsbank#comment_336742) but I can't reproduce this issue (using the ex-date instead of valuta). This issue should be fixed with #142 and already live on production...
