### ISSUE TITLE
[Scalable Capital] JS-Fehler beim Auslesen einer Dividenden-PDF

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#180]
<h2>Description</h2>
<blockquote>
<p>Ich @carstenhag hatte jetzt zum ersten Mal eine Scalable-Capital PDF importiert. Da die Seite komische Faxen gemacht hatte, hab ich die JS-Console geöffnet. Es wird ein Fehler beim Import geworfen. Korrekt importiert wird es aber komischerweise.</p>
</blockquote>
<pre><code>scalableCapital.js:227 Error while parsing page (scalable.capital) TypeError: Cannot read property 'substring' of undefined
    at findByStartingTerm (scalableCapital.js:57)
    at findISIN (scalableCapital.js:84)
    at parsePage (scalableCapital.js:188)
    at Module.parsePages (scalableCapital.js:225)
    at parseActivitiesFromPages (index.js:59)
    at _callee2$ (index.js:217)
    at tryCatch (pdf.worker.js:755)
    at Generator.invoke [as _invoke] (pdf.worker.js:930)
    at Generator.prototype.&lt;computed&gt; [as next] (pdf.worker.js:798)
    at asyncGeneratorStep (index.js:22) 
</code></pre>
<pre><code class="language-json">{
  &quot;broker&quot;: &quot;scalablecapital&quot;,
  &quot;type&quot;: &quot;Dividend&quot;,
  &quot;date&quot;: &quot;2020-10-07&quot;,
  &quot;isin&quot;: &quot;IE00B3RBWM25&quot;,
  &quot;company&quot;: &quot;Vanguard FTSE All-World U.ETF&quot;,
  &quot;shares&quot;: 0.635,
  &quot;price&quot;: 0.38546743314510523,
  &quot;amount&quot;: 0.25,
  &quot;fee&quot;: 0,
  &quot;tax&quot;: 0,
  &quot;filename&quot;: &quot;download (1).pdf_0&quot;,
  &quot;parsed&quot;: true,
  &quot;duplicate&quot;: true
}
</code></pre>
<h2>Document</h2>
<details><summary>download (1).pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;DCUP-050.041&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;irardxv@gcawopicdl.rj www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;Scalable Capital Vermögensverw.GmbH&quot;,
    &quot;Seitzstr. 8 e&quot;,
    &quot;80538 München&quot;,
    &quot;München&quot;,
    &quot;09.10.2020&quot;,
    &quot;Scalable Capital&quot;,
    &quot;Vermögensverwaltung GmbH&quot;,
    &quot;Seitzstraße 8e&quot;,
    &quot;80538 München&quot;,
    &quot;vfsmxbv@gzaddvab.hrdvszf&quot;,
    &quot;Dljloyi Yjiqghzt&quot;,
    &quot;Xkdsn-Nb.: 9504900    Vwxbnulkd: 9&quot;,
    &quot;Ehsuk-Bz.: 5639107133&quot;,
    &quot;Wefvzpdy-Mm.: 3268949&quot;,
    &quot;Saznbjvv-Qn.: 70477101&quot;,
    &quot;Fondsausschüttung&quot;,
    &quot;KOPIE&quot;,
    &quot;STK 0,635&quot;,
    &quot;Ausschüttung&quot;,
    &quot;Ex-Tag: 24.09.2020&quot;,
    &quot;ISIN: IE00B3RBWM25&quot;,
    &quot;WKN: A1JX52&quot;,
    &quot;Nominale&quot;,
    &quot;USD&quot;,
    &quot;0,454628 p.STK&quot;,
    &quot;Vanguard FTSE All-World U.ETF&quot;,
    &quot;Registered Shares USD Dis.oN&quot;,
    &quot;Zahlungszeitraum:&quot;,
    &quot;01.07.2019 - 30.06.2020&quot;,
    &quot;Zahltag:&quot;,
    &quot;07.10.2020&quot;,
    &quot;Umrechnungskurs:&quot;,
    &quot;1,17942&quot;,
    &quot;EUR/USD&quot;,
    &quot;Bruttobetrag&quot;,
    &quot;USD&quot;,
    &quot;0,29&quot;,
    &quot;Bruttobetrag&quot;,
    &quot;EUR&quot;,
    &quot;0,25&quot;,
    &quot;0,25&quot;,
    &quot;EUR&quot;,
    &quot;Valuta: 07.10.2020&quot;,
    &quot;Zu Gunsten Konto 1332876000&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 1/2&quot;
  ],
  [
    &quot;DCUP-050.041&quot;,
    &quot;Scalable Capital Vermögensverwaltung GmbH | Geschäftsführung: Erik Podzuweit, Florian Prucker | HRB 217778, Amtsgericht München |&quot;,
    &quot;USt-IdNr. DE300434774 | www.scalable.capital&quot;,
    &quot;Baader Bank Aktiengesellschaft Weihenstephaner Straße 4 85716 Unterschleißheim Deutschland T 00800 00 222 337* F +49 89 5150 2442&quot;,
    &quot;mjqxktj@iewutsgjgt.aj www.baaderbank.de&quot;,
    &quot;* Kostenfreie Telefonnummer aus dem (inter-) nationalen Festnetz. Für Anrufe aus anderen Netzen können Gebühren anfallen.&quot;,
    &quot;Herausgeberin und verantwortlich für den Inhalt ist die Baader Bank Aktiengesellschaft.&quot;,
    &quot;Fondsausschüttung&quot;,
    &quot;Fortsetzung:&quot;,
    &quot;KOPIE&quot;,
    &quot;Darstellung der steuerlichen Berechnungsgrundlagen:&quot;,
    &quot;vorher&quot;,
    &quot;nachher&quot;,
    &quot;Merkposten / Steuertöpfe&quot;,
    &quot;Erhöhung/Reduktion&quot;,
    &quot;Ausschüttung netto Aktienfonds&quot;,
    &quot;Allgemeiner Verlustverrechnungstopf&quot;,
    &quot;EUR&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;0,01&quot;,
    &quot;-&quot;,
    &quot;0,01&quot;,
    &quot;EUR&quot;,
    &quot;Ausschüttung netto Aktienfonds&quot;,
    &quot;Freistellungsauftrag&quot;,
    &quot;EUR&quot;,
    &quot;99,84&quot;,
    &quot;EUR&quot;,
    &quot;0,16&quot;,
    &quot;-&quot;,
    &quot;100,00&quot;,
    &quot;EUR&quot;,
    &quot;Ausschüttung netto Aktienfonds&quot;,
    &quot;Ausnutzung FSA&quot;,
    &quot;EUR&quot;,
    &quot;0,16&quot;,
    &quot;-&quot;,
    &quot;EUR&quot;,
    &quot;0,16&quot;,
    &quot;-&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;Steuerpflicht brutto&quot;,
    &quot;Steuerpflicht netto&quot;,
    &quot;Bemessungsgrundlagen&quot;,
    &quot;Ausschüttung brutto Aktienfonds&quot;,
    &quot;0,25&quot;,
    &quot;0,25&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Ausschüttung netto Aktienfonds&quot;,
    &quot;0,17&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Kapitalertragsteuer auf allgemeine Gewinne&quot;,
    &quot;0,17&quot;,
    &quot;0,00&quot;,
    &quot;EUR&quot;,
    &quot;EUR&quot;,
    &quot;Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.&quot;,
    &quot;Einkünfte aus Kapitalvermögen im Sinne von § 20 EStG sind einkommensteuerpflichtig.&quot;,
    &quot;Bitte beachten Sie Ihre eventuelle Meldepflicht nach § 67 AWV.&quot;,
    &quot;Seite 2/2&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/6f6e177f</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by carstenhag** [comment]
Die anderen JS fehler die ich gesehen hatte, hab ich bei https://community.tresor.one/c/help/drag-drop-abrechnung-hochladen-geht-erst-nach-1-2-mal-seite-neuladen reported. Hat aber nichts mit diesem Fehler hier zu tun.

**Comment by dredav** [comment]
Danke für das Issue @carstenhag. Der Fehler kommt durch die zweite Seite der Abrechnung, welcher nur die steuerlichen Berechnungsgrundlagen darstellt. Bisher wird nur für die erste Seite geprüft, ob diese geparsed werden kann und wenn ja, dann werden alle Seiten eines Dokuments eingelesen. Hat ein Dokument mehrere Seiten, jedoch nicht auf allen eine Abrechnung, kommt es daher aktuell noch zu Fehlern, da die Seiten nicht als Activity geparsed werden können. Ich habe es aber bereits auf meiner Todo-Liste, jede Seite zu prüfen (und die Validierung besser zu machen, dass z.B. Seiten mit `steuerlichen Berechnungsgrundlagen` nicht für den Broker ausgelesen werden). Ich lasse daher das Issue als Work-Tracking offen.

**Comment by carstenhag** [comment]
FYI sowas tritt auch bei meiner "1822direkt-dividende"-Datei auf (Sumit und @dredav, ihr habt die Datei). Das ist die mock-dividenden-Datei.

```
1822direkt.js:135 Unknown page type for 1822direkt
parsePage @ 1822direkt.js:135
parsePages @ 1822direkt.js:162
parseActivitiesFromPages @ index.js:59
_callee2$ @ index.js:217
tryCatch @ pdf.worker.js:755
invoke @ pdf.worker.js:930
prototype.<computed> @ pdf.worker.js:798
asyncGeneratorStep @ index.js:22
_next @ index.js:24
Promise.then (async)
asyncGeneratorStep @ index.js:22
_next @ index.js:24
Promise.then (async)
asyncGeneratorStep @ index.js:22
_next @ index.js:24
Promise.then (async)
asyncGeneratorStep @ index.js:22
_next @ index.js:24
Promise.then (async)
asyncGeneratorStep @ index.js:22
_next @ index.js:24
Promise.then (async)
asyncGeneratorStep @ index.js:22
_next @ index.js:24
Promise.then (async)
asyncGeneratorStep @ index.js:22
_next @ index.js:24
Promise.then (async)
asyncGeneratorStep @ index.js:22
_next @ index.js:24
eval @ index.js:24
eval @ index.js:24
eval @ index.js:234
load (async)
__webpack_exports__.default @ index.js:139
eval @ index.js:134
(anonymous) @ 6de8fc4897651f34a5c7.js:1
tryCatch @ pdf.worker.js:755
invoke @ pdf.worker.js:930
prototype.<computed> @ pdf.worker.js:798
r @ f43e7611103c06583653.js:2
l @ f43e7611103c06583653.js:2
(anonymous) @ f43e7611103c06583653.js:2
(anonymous) @ f43e7611103c06583653.js:2
addFiles @ 6de8fc4897651f34a5c7.js:1
drop @ 6de8fc4897651f34a5c7.js:1
Qt @ f43e7611103c06583653.js:2
n @ f43e7611103c06583653.js:2
c._wrapper @ f43e7611103c06583653.js:2
1822direkt.js:164 Error while parsing page (1822direkt) RangeError: Invalid time value
    at format (index.js:383)
    at parsePage (1822direkt.js:141)
    at Module.parsePages (1822direkt.js:162)
    at parseActivitiesFromPages (index.js:59)
```
