### ISSUE TITLE
[Consorsbank] ISIN wird nicht erkannt

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#181]
<h2>Description</h2>
<blockquote>
<p>Die Dividendenabrechnung bei einigen PDFs wird nicht erkannt, weil anscheinend die ISIN mit der WKN vertauscht ist!?</p>
</blockquote>
<h2>Document</h2>
<details><summary>DIVIDENDENGUTSCHRIFT_123456_wkn851745_dat20191216_id821618319.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;Mukt Japvpofo&quot;,
    &quot;Ivjobncyvl 2&quot;,
    &quot;92095 Hqvfney&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;3373142192&quot;,
    &quot;1529019884/04&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;1000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;16.12.2019&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Dividendengutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;3M&quot;,
    &quot;CO. Registered Shares DL -,01&quot;,
    &quot;851745&quot;,
    &quot;US88579Y1010&quot;,
    &quot;Bestand&quot;,
    &quot;0,49489 Stück&quot;,
    &quot;Dividende pro Stück 1,44 USD&quot;,
    &quot;Schlusstag 20.11.2019&quot;,
    &quot;Brutto in USD&quot;,
    &quot;0,71 USD&quot;,
    &quot;abzgl. Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,71 USD&quot;,
    &quot;0,11 USD&quot;,
    &quot;Zwischensumme in USD&quot;,
    &quot;0,60 USD&quot;,
    &quot;Devisenkurs&quot;,
    &quot;1,117400 USD / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;0,64 EUR&quot;,
    &quot;Quellensteuer in EUR&quot;,
    &quot;0,10 EUR&quot;,
    &quot;Zwischensumme in EUR&quot;,
    &quot;0,54 EUR&quot;,
    &quot;abzgl. Kapitalertragsteuer&quot;,
    &quot;25,00 % von&quot;,
    &quot;0,24 EUR&quot;,
    &quot;0,06 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;IBAN&quot;,
    &quot;BQ42 6041 9860&quot;,
    &quot;0357 8363 95&quot;,
    &quot;0,48 EUR&quot;,
    &quot;Valuta 12.12.2019&quot;,
    &quot;BIC&quot;,
    &quot;ARURUE36UFP&quot;,
    &quot;Anrechenbare Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,71 USD&quot;,
    &quot;0,10&quot;,
    &quot;EUR&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;0,64 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;-0,40 EUR&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;-0,10 EUR&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;0,24 EUR&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Depotnummer:&quot;,
    &quot;0808013440&quot;,
    &quot;8526850321/92&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;1000&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;16.12.2019&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/f5da060c</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by SirGibihm** [comment]
Ich kann das Problem hier nicht replizieren, vermutlich bereits an anderer Stelle gefixt. Vermutlich gleiche Situation wie bei #178 #171 etc.
