### ISSUE TITLE
Werden leider nicht importier

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#182]
<h2>Description</h2>
<blockquote>
<p>Keine Reaktion trotz mehrmaligen Versuchen.</p>
</blockquote>
<h2>Documents</h2>
<details><summary>DIVIDENDENGUTSCHRIFT_848699501_wkn878841_dat20201023_id919935062.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;uqdqr&quot;,
    &quot;etnzhmtj&quot;,
    &quot;vynxbzdv&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;9402516825&quot;,
    &quot;4939045068/89&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;4100&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;23.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Dividendengutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;CISCO&quot;,
    &quot;SYSTEMS INC. Registered Shares DL-,001&quot;,
    &quot;878841&quot;,
    &quot;US17275R1023&quot;,
    &quot;Bestand&quot;,
    &quot;2,74899 Stück&quot;,
    &quot;Dividende pro Stück 0,36 USD&quot;,
    &quot;Schlusstag 30.09.2020&quot;,
    &quot;Brutto in USD&quot;,
    &quot;0,99 USD&quot;,
    &quot;abzgl. Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,99 USD&quot;,
    &quot;0,15 USD&quot;,
    &quot;Zwischensumme in USD&quot;,
    &quot;0,84 USD&quot;,
    &quot;Devisenkurs&quot;,
    &quot;1,187700 USD / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;0,83 EUR&quot;,
    &quot;Quellensteuer in EUR&quot;,
    &quot;0,13 EUR&quot;,
    &quot;Zwischensumme in EUR&quot;,
    &quot;0,71 EUR&quot;,
    &quot;abzgl. Kapitalertragsteuer&quot;,
    &quot;25,00 % von&quot;,
    &quot;0,31 EUR&quot;,
    &quot;0,08 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;IBAN&quot;,
    &quot;DE69 7603 0080&quot;,
    &quot;0840 6995 09&quot;,
    &quot;0,63 EUR&quot;,
    &quot;Valuta 21.10.2020&quot;,
    &quot;BIC&quot;,
    &quot;CSDBDE71XXX&quot;,
    &quot;Anrechenbare Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,99 USD&quot;,
    &quot;0,13&quot;,
    &quot;EUR&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;0,83 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;-0,52 EUR&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;-0,13 EUR&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;0,31 EUR&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Depotnummer:&quot;,
    &quot;0848699501&quot;,
    &quot;1111316118/00&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;4100&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;23.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;
  ]
]

</code></pre>
</p></details>
<details><summary>DIVIDENDENGUTSCHRIFT_848699501_wkn851247_dat20201009_id917269991.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;Ofhxb Qffxqg&quot;,
    &quot;Jwcjdfujmzg. 42m&quot;,
    &quot;69312 Vczcdb&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;4156851654&quot;,
    &quot;5808802939/15&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;4100&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;09.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Dividendengutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;DIAGEO&quot;,
    &quot;PLC Reg. Shares LS -,28935185&quot;,
    &quot;851247&quot;,
    &quot;GB0002374006&quot;,
    &quot;Bestand&quot;,
    &quot;4,75812 Stück&quot;,
    &quot;Dividende pro Stück 0,4247 GBP&quot;,
    &quot;Schlusstag 12.08.2020&quot;,
    &quot;Brutto in GBP&quot;,
    &quot;2,02 GBP&quot;,
    &quot;Zwischensumme in GBP&quot;,
    &quot;2,02 GBP&quot;,
    &quot;Devisenkurs&quot;,
    &quot;0,913400 GBP / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;2,21 EUR&quot;,
    &quot;Zwischensumme in EUR&quot;,
    &quot;2,21 EUR&quot;,
    &quot;abzgl. Kapitalertragsteuer&quot;,
    &quot;25,00 % von&quot;,
    &quot;2,21 EUR&quot;,
    &quot;0,55 EUR&quot;,
    &quot;abzgl. Solidaritätszuschlag&quot;,
    &quot;5,50 % von&quot;,
    &quot;0,55 EUR&quot;,
    &quot;0,03 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;IBAN&quot;,
    &quot;DE69 7603 0080&quot;,
    &quot;0840 6995 09&quot;,
    &quot;1,63 EUR&quot;,
    &quot;Valuta 08.10.2020&quot;,
    &quot;BIC&quot;,
    &quot;CSDBDE71XXX&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;2,21 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;2,21 EUR&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Depotnummer:&quot;,
    &quot;0848699501&quot;,
    &quot;1111316118/00&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;4100&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;09.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;
  ]
]

</code></pre>
</p></details>
<details><summary>DIVIDENDENGUTSCHRIFT_848699501_wkn878841_dat20201023_id919935061.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;Itfob Pgsire&quot;,
    &quot;Yqexrmmtjfp. 75c&quot;,
    &quot;06813 Dodjix&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;2930820110&quot;,
    &quot;0360176677/18&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;4100&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;23.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Dividendengutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;CISCO&quot;,
    &quot;SYSTEMS INC. Registered Shares DL-,001&quot;,
    &quot;878841&quot;,
    &quot;US17275R1023&quot;,
    &quot;Bestand&quot;,
    &quot;10 Stück&quot;,
    &quot;Dividende pro Stück 0,36 USD&quot;,
    &quot;Schlusstag 30.09.2020&quot;,
    &quot;Brutto in USD&quot;,
    &quot;3,60 USD&quot;,
    &quot;abzgl. Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;3,60 USD&quot;,
    &quot;0,54 USD&quot;,
    &quot;Zwischensumme in USD&quot;,
    &quot;3,06 USD&quot;,
    &quot;Devisenkurs&quot;,
    &quot;1,187700 USD / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;3,03 EUR&quot;,
    &quot;Quellensteuer in EUR&quot;,
    &quot;0,45 EUR&quot;,
    &quot;Zwischensumme in EUR&quot;,
    &quot;2,58 EUR&quot;,
    &quot;abzgl. Kapitalertragsteuer&quot;,
    &quot;25,00 % von&quot;,
    &quot;1,23 EUR&quot;,
    &quot;0,31 EUR&quot;,
    &quot;abzgl. Solidaritätszuschlag&quot;,
    &quot;5,50 % von&quot;,
    &quot;0,31 EUR&quot;,
    &quot;0,01 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;IBAN&quot;,
    &quot;DE69 7603 0080&quot;,
    &quot;0840 6995 09&quot;,
    &quot;2,26 EUR&quot;,
    &quot;Valuta 21.10.2020&quot;,
    &quot;BIC&quot;,
    &quot;CSDBDE71XXX&quot;,
    &quot;Anrechenbare Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;3,60 USD&quot;,
    &quot;0,45&quot;,
    &quot;EUR&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;3,03 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;-1,80 EUR&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;-0,45 EUR&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;1,23 EUR&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Depotnummer:&quot;,
    &quot;0848699501&quot;,
    &quot;1111316118/00&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;4100&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;23.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/4615bbbf</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by SirGibihm** [comment]
I tested all of the files given and ran into no issues. If you want the files to be added I can add a pull request for that, see my [branch](https://github.com/SirGibihm/tresor-import/tree/182_consorbank_divdenden_fail). Please advise

**Comment by dredav** [comment]
Did you use the current master version to test or the latest [release](https://github.com/codeofsumit/tresor-import/tree/2.3.0)? I'm not sure if the master has some unreleased changes but I think, when you don't have an issue we don't need to add these files as examples.

>Keine Reaktion trotz mehrmaligen Versuchen.

That sounds more like: The import is not starting (the blue import bar in T1 is not visible). I will adjust the import.tresore.one tool soon with an additional question, if the blue or orange bar was visible or not.

**Comment by SirGibihm** [comment]
I used the master, not the release so we should just wait for the new release i guess.
