### ISSUE TITLE
[Consorsbank] Valutatag für Import nutzen

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#189]
<h2>Description</h2>
<blockquote>
<p>Würde gerne den Valutatag statt den Schlusstag für den Import nutzen.</p>
</blockquote>
<h2>Document</h2>
<details><summary>ERTRAGSGUTSCHRIFT_858155107_wkn899744_dat20201020_id919399134.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).&quot;,
    &quot;Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929&quot;,
    &quot;Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de&quot;,
    &quot;Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449&quot;,
    &quot;Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé&quot;,
    &quot;Vvhutwwmw Ftazsse&quot;,
    &quot;Ajnmubhrx Hglwsvucbn&quot;,
    &quot;Unsvsw Oxnmopw. 97&quot;,
    &quot;45673 Rxmysfügl&quot;,
    &quot;Consorsbank • 90318 Nürnberg&quot;,
    &quot;Depotnummer:&quot;,
    &quot;6086869054&quot;,
    &quot;6506073135/66&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;2100&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;20.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;1 von 2&quot;,
    &quot;Ertragsgutschrift&quot;,
    &quot;Wertpapierbezeichnung&quot;,
    &quot;WKN&quot;,
    &quot;ISIN&quot;,
    &quot;REALTY INCOME CORP. Registered Shares DL 1&quot;,
    &quot;899744&quot;,
    &quot;US7561091049&quot;,
    &quot;Bestand&quot;,
    &quot;1,88649 Stück&quot;,
    &quot;Ertragsausschüttung je Anteil 0,234 USD&quot;,
    &quot;Schlusstag 29.09.2020&quot;,
    &quot;Brutto in USD&quot;,
    &quot;0,44 USD&quot;,
    &quot;abzgl. Quellensteuer&quot;,
    &quot;15,00 % von&quot;,
    &quot;0,44 USD&quot;,
    &quot;0,07 USD&quot;,
    &quot;Netto in USD&quot;,
    &quot;0,37 USD&quot;,
    &quot;Devisenkurs&quot;,
    &quot;1,184300 USD / EUR&quot;,
    &quot;Brutto in EUR&quot;,
    &quot;0,37 EUR&quot;,
    &quot;Quellensteuer in EUR&quot;,
    &quot;0,06 EUR&quot;,
    &quot;Netto zugunsten&quot;,
    &quot;IBAN&quot;,
    &quot;DE67 7603 0080&quot;,
    &quot;0850 1551 05&quot;,
    &quot;0,31 EUR&quot;,
    &quot;Valuta 15.10.2020&quot;,
    &quot;BIC&quot;,
    &quot;CSDBDE71XXX&quot;,
    &quot;Anrechenbare Quellensteuer&quot;,
    &quot;0,0351 USD pro Stück&quot;,
    &quot;0,06&quot;,
    &quot;EUR&quot;,
    &quot;Bitte beachten Sie die weiteren Informationen auf Seite 2.&quot;
  ],
  [
    &quot;Details zur Abrechnung&quot;,
    &quot;Steuerpflichtiger Gesamtertrag&quot;,
    &quot;0,37 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;-0,37 EUR&quot;,
    &quot;Mit Quellensteuer verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;somit verrechnete Quellensteuer&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Bemessungsgrundlage für Kapitalertragsteuer gesamt&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Details zu den Verrechnungstöpfen&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; vor der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Mit Verrechnungstopf \&quot;Allgemein\&quot; verrechnet&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Allgemein\&quot; nach der Abrechnung&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Sparerpauschbetrag vor der Abrechnung&quot;,
    &quot;404,98 EUR&quot;,
    &quot;Mit Sparerpauschbetrag verrechnet&quot;,
    &quot;-0,37 EUR&quot;,
    &quot;Sparerpauschbetrag nach der Abrechnung&quot;,
    &quot;404,61 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; vor der Abrechnung&quot;,
    &quot;14,41 EUR&quot;,
    &quot;Änderung Verrechnungstopf \&quot;Quellensteuer\&quot;&quot;,
    &quot;0,06 EUR&quot;,
    &quot;Verrechnungstopf \&quot;Quellensteuer\&quot; nach der Abrechnung&quot;,
    &quot;14,47 EUR&quot;,
    &quot;Depotnummer:&quot;,
    &quot;7912630335&quot;,
    &quot;9885701292/49&quot;,
    &quot;Vermerk der Bank:&quot;,
    &quot;2100&quot;,
    &quot;2&quot;,
    &quot;Datum:&quot;,
    &quot;20.10.2020&quot;,
    &quot;Seite:&quot;,
    &quot;2 von 2&quot;,
    &quot;Informationen zum&quot;,
    &quot;Investmentsteuergesetz&quot;,
    &quot;Ausschüttung gem. §2 Abs. 11 InvStG&quot;,
    &quot;0,37 EUR&quot;,
    &quot;abzgl. Teilfreistellung&quot;,
    &quot;0,00 % von 0,37 EUR&quot;,
    &quot;0,00 EUR&quot;,
    &quot;Ertragsausschüttung mit Teilfreistellung&quot;,
    &quot;0,37 EUR&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://dashboard.tresor.one/p/5f194af3e8e79400081eeb75</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by SirGibihm** [comment]
I remember already fixing this earlier; this is also confirmed by testing the given file. Can't figure out the according pull request but this can be closed.
