### ISSUE TITLE
[Smartbroker] Quellensteuer fehlt bei Dividendenimport

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#195]
<h2>Description</h2>
<blockquote>
<p>Die Steuern werden beim Import nur teilweise berücksichtigt. Ich erwarte beim Import eine Summe von 5,14€ (statt aktuell 4,37€) und Steuern in Höhe von 1,34€ (die aktuell importierten 0,57€ plus die fehlende Quellensteuer in Höhe von 0,77€)</p>
</blockquote>
<h2>Document</h2>
<details><summary>Dividenden_LTC_PTIES_INC______DL-,01_vom_29_10_2020.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Herr&quot;,
    &quot;XXX&quot;,
    &quot;XXX&quot;,
    &quot;XXX&quot;,
    &quot;XXX&quot;,
    &quot;BNP Paribas S.A. Niederlassung Deutschland &gt; Standort: München &gt; Landsberger Straße 300 &gt; 80687 München &gt; Sitz: Nürnberg HRB Nürnberg 31129 &gt; USt.-Ident-Nr.: DE&quot;,
    &quot;191528929 &gt; Sitz der Hauptniederlassung der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449 &gt; Président du&quot;,
    &quot;Conseil d‘Administration: Jean Lemierre, Directeur Général: Jean-Laurent Bonnafé&quot;,
    &quot;Depot-Nr.&quot;,
    &quot;XXX&quot;,
    &quot;Abrechnungs-Nr.&quot;,
    &quot;69892042 / 29.10.2020&quot;,
    &quot;Depotinhaber&quot;,
    &quot;3.17/ABREEREIERTR/GDBERTRG/003161/301020/000715&quot;,
    &quot;München, 29.10.2020&quot;,
    &quot;BELEGDRUCK=J&quot;,
    &quot;ORIGINAL=1&quot;,
    &quot;FAXVERSAND=N&quot;,
    &quot;EMAILVERSAND=N&quot;,
    &quot;DEPOTNUMMER=XXX&quot;,
    &quot;DEPOTUNTERBEZEICHNUNG=&quot;,
    &quot;VERSANDARTENSCHLUESSEL=DRUCK&quot;,
    &quot;ADRESSZEILE1=Herr&quot;,
    &quot;ADRESSZEILE2=XXX&quot;,
    &quot;ADRESSZEILE3=XXX&quot;,
    &quot;ADRESSZEILE4=XXX&quot;,
    &quot;ADRESSZEILE5=&quot;,
    &quot;ADRESSZEILE6=&quot;,
    &quot;BELEGNUMMER=3161&quot;,
    &quot;SEITENNUMMER=1&quot;,
    &quot;STEUERERSTATTUNG=N&quot;,
    &quot;Dieser Beleg wird maschinell erstellt und daher nicht unterschrieben.&quot;,
    &quot;Erträgnisgutschrift aus Wertpapieren&quot;,
    &quot;Dividendengutschrift&quot;,
    &quot;Gattungsbezeichnung&quot;,
    &quot;LTC Properties Inc. Registered Shares DL -,01&quot;,
    &quot;ISIN&quot;,
    &quot;US5021751020&quot;,
    &quot;Nominal&quot;,
    &quot;STK 32,000&quot;,
    &quot;Ex-Tag&quot;,
    &quot;21.10.2020&quot;,
    &quot;Zahltag&quot;,
    &quot;30.10.2020&quot;,
    &quot;Dividenden-Betrag pro Stück&quot;,
    &quot;USD 0,190000&quot;,
    &quot;Dividende für&quot;,
    &quot;01.07.2020 - 30.06.2021&quot;,
    &quot;Wert&quot;,
    &quot;30.10.2020&quot;,
    &quot;Konto-Nr.&quot;,
    &quot;XXX&quot;,
    &quot;Devisenkurs&quot;,
    &quot;EUR/USD 1,1821&quot;,
    &quot;Betrag zu Ihren Gunsten&quot;,
    &quot;EUR&quot;,
    &quot;3,80&quot;,
    &quot;Hinweise zur steuerlichen Verrechnung:&quot;,
    &quot;vorher&quot;,
    &quot;aktuell&quot;,
    &quot;Steuerpflichtiger Ausschüttungsbetrag&quot;,
    &quot;EUR&quot;,
    &quot;5,14&quot;,
    &quot;US-Quellensteuer 15%&quot;,
    &quot;USD&quot;,
    &quot;0,91&quot;,
    &quot;davon anrechenbare US-Quellensteuer 15%&quot;,
    &quot;EUR&quot;,
    &quot;0,77&quot;,
    &quot;Aktienverlusttopf&quot;,
    &quot;EUR&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;allgemeiner Verlusttopf&quot;,
    &quot;EUR&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;Quellensteuertopf&quot;,
    &quot;EUR&quot;,
    &quot;0,00&quot;,
    &quot;0,00&quot;,
    &quot;zu versteuern&quot;,
    &quot;EUR&quot;,
    &quot;2,06&quot;,
    &quot;einbehaltene Kapitalertragsteuer&quot;,
    &quot;EUR&quot;,
    &quot;0,51&quot;,
    &quot;einbehaltener Solidaritätszuschlag&quot;,
    &quot;EUR&quot;,
    &quot;0,02&quot;,
    &quot;einbehaltene Kirchensteuer&quot;,
    &quot;EUR&quot;,
    &quot;0,04&quot;,
    &quot;im laufenden Jahr einbehaltene Kapitalertragsteuer&quot;,
    &quot;EUR&quot;,
    &quot;6,54&quot;,
    &quot;im laufenden Jahr einbehaltener Solidaritätszuschlag&quot;,
    &quot;EUR&quot;,
    &quot;0,35&quot;,
    &quot;im laufenden Jahr einbehaltene Kirchensteuer&quot;,
    &quot;EUR&quot;,
    &quot;0,52&quot;,
    &quot;Kapitalertragsteuer, Solidaritätszuschlag und ggf. Kirchensteuer nach gemeldetem Kirchensteuersatz verrechnet mit dem&quot;,
    &quot;Finanzamt Frankfurt/M. V-Höchst, Steuernummer 047/220/15370.&quot;,
    &quot;Steuerlicher Stichtag: 30.10.2020&quot;,
    &quot;Jahressteuerbescheinigung folgt&quot;,
    &quot;Verwahrart: Wertpapierrechnung&quot;,
    &quot;Lagerland: USA&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>https://community.tresor.one/u/97e9f35e</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by dredav** [comment]
Can fixed with #192

**Comment by SirGibihm** [comment]
The smartbroker broker is not even implemented yet. The parser that takes over importing this file is the onvista broker. A proper parser (that fixed this issue) is implemented in #169
