### ISSUE TITLE
Add tax support for DKB

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#24]
DKB Imports currently don't extract the `tax` field

**Comment by dredav** [comment]
Has anyone some documents from DKB with taxes?

**Comment by dredav** [comment]
@jhonnen Do you have a statement with withholding taxes paid in a foreign currency? The current solution can handle only withholding taxes paied in EUR: https://github.com/codeofsumit/tresor-import/blob/98ac4a180c9556264fd1fcc8bc0ee3b36cc27b2d/src/brokers/dkb.js#L63

**Comment by jhonnen** [comment]
The implementation was based on the existing test files, which are in USD. They list the amount both in USD and EUR.

https://github.com/codeofsumit/tresor-import/blob/2a20722b4d920b6d66de8820e8458a62c1a3b4e1/tests/brokers/__mocks__/dkb/div-1.json#L61

I have no other statements available.
