### ISSUE TITLE
Trade Republic - Quartalsberichte / Depot Bestand

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#25]
Ein User hat gefragt, ob man nicht auch Konto-Auszüge / Quartalsberichte reinziehen könnte damit man nicht jede PDF einzeln rein ballern muss.

Ich weiß nicht was für Infos da so drinstehen - denkt ihr das ist möglich?

**Comment by carstenhag** [comment]
According to https://old.reddit.com/r/Finanzen/comments/gi7uqj/tresor_one_unterst%C3%BCtzt_jetzt_trade_republic_und/fqduixl/ it's not an alternative unfortunately :(
