### ISSUE TITLE
flatex Support

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#26]
Ich habe ein paar Files zum testen

**Comment by carstenhag** [comment]
Magst du die dann vielleicht schon in den mock-ordner packen bzw die arrays hochladen? Dann kann ich mich mal dran versuchen.

**Comment by codeofsumit** [comment]
done. Der User hatte bereits selbst seine Adresse durch XXX ersetzt - ich hoffe das hat die Struktur nicht beeinflusst. Brauchen auf jeden Fall noch ein paar weitere PDFs zum testen.
Gerne an sumit@tresor.one

**Comment by carstenhag** [comment]
Thanks, working on it.

**Comment by carstenhag** [comment]
I think these samples are from Flatex AT only. We need Flatex DE samples as well, possibly they differ. I've already noticed that flatex files differ a lot, which is unfortunate.

**Comment by pnzz7** [comment]
Hey ✌️ Ich bin btw der User der PDFs. Das editieren hat leider anscheinend die Struktur zerstört. habe jetzt einen Pull Request mit den korrekten mocks + flatex parser erstellt (#34) - leider nach wie vor aktuell nur für AT und dafür hab ich aktuell auch nur buy + dividend orders

**Comment by pnzz7** [comment]
sorry @carstenhag hab deinen pull request leider erst danach gesehen

**Comment by carstenhag** [comment]
Ups ja, kein Problem, ich hatte vergessen den PR mit dem Issue zu linken :/

**Comment by codeofsumit** [comment]
Welcher PR solls sein? Kann einer geschlossen werden?
