### ISSUE TITLE
Support für Trade Republic

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#3]
Issue für Trade Republic Support

**Comment by codeofsumit** [comment]
merged an done - will deploy to tresor.one later today

**Comment by codeofsumit** [comment]
@zirkler please test the import with dividend fix on https://dev.tresor.one
Careful - it's the dev-frontend but it's **PRODUCTION DATA**

**Comment by zirkler** [comment]
Successfully tested 👍🏼

**Comment by codeofsumit** [comment]
Found another bug 😂 
https://github.com/codeofsumit/tresor-import/blob/master/src/brokers/traderepublic.js#L173

**Comment by zirkler** [comment]
Oops, had this disabled during initial development. Validation is enabled now: https://github.com/codeofsumit/tresor-import/pull/15
Sorry for the PR spamming.

**Comment by codeofsumit** [comment]
All good, I should've detected it in the review.
All fixes, including the TR logos for import, are now on production tresor.one

![trade republic](https://user-images.githubusercontent.com/2399810/80092113-81d91c00-8562-11ea-9040-2ee88de168fe.gif)
