### ISSUE TITLE
flatex

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#307]
## Description
> test

## Document
<details><summary>Onlinebanking.pdf</summary><p>

```json
[
  [
    "Onlinebanking",
    "about:blank",
    "1 von 2",
    "29.11.2020, 17:37"
  ],
  [
    "Onlinebanking",
    "about:blank",
    "2 von 2",
    "29.11.2020, 17:37"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by dredav** [comment]
Invalid sample. Closed.
