### ISSUE TITLE
[unknown] Dividendenabrechnung kann nicht hochgeladen werden

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#321]
## Description
> Ich versuche CSV zu erstellen und nachzusenden.

LG
Stefan (Fuchs)

## Document
<details><summary>389  Divi. Intel 72637510_2020_Erträge_vom_02.12.2020_20201202122943.pdf.pdf</summary><p>

```json
[
  [],
  []
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by SirGibihm** [comment]
Hier ist wohl etwas mit dem Upload schiefgelaufen, ggf einfach eine falsche Datei? Kontaktiere den Nutzer mal.

**Comment by dredav** [comment]
@SirGibihm Did you get any information from the user?

**Comment by dredav** [comment]
Same issue as in #328?

**Comment by SirGibihm** [comment]
Yes, confirmed this with the user.
