### ISSUE TITLE
ebase Umsatz Kauf, Dividende und Wiederanlage der Dividende

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#339]
## Description
> Mir ist beim Hochladen des pdf Dokumentes aufgefallen, dass die automatische Wiederanlage der Dividende als Verkauf (Sell) angezeigt wird. Dies müsste ja ein Kauf (Buy) sein. Die Dividende wird als solches nicht erkannt, weil der Betrag nicht direkt auftaucht. Hier kann ich mir nur eine Notlösung vorstellen, weil der Wiederanlagebetrag die Dividende ist. Ich habe in meinem Profil ein Testdepot ebase angelegt. Da ist das jetzt hochgeladene Dokument drin.

## Document
<details><summary>Umsätze ebase.pdf</summary><p>

```json
[
  [
    "Umsätze",
    "im Zeitraum: 03.09.2020 -  03.12.2020",
    "03.12.2020 13:43 Uhr",
    "bgjhw Sdilp advp PF  04030224126",
    "Mhaggxmylirp: Ryna Sahnxmzoi",
    "Pbnblpz: 273,75 GLN",
    "Umsatzarten:",
    "Zugang",
    "Abgang",
    "Fondsertrag / Vorabpauschale",
    "Sonstige Umsätze",
    "Pos.",
    "Umsatzart / Bezeichnung",
    "ISIN",
    "Buchungsdatum",
    "Anteile",
    "Kurs /",
    "Kursdatum",
    "Devisenkurs",
    "Betrag",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "13.11.2020",
    "0,635652",
    "74,01 USD",
    "12.11.2020",
    "1,178500",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "15.10.2020",
    "0,644632",
    "72,38 USD",
    "14.10.2020",
    "1,168800",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Wiederanlage Fondsertrag",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "12.10.2020",
    "0,039737",
    "71,47 USD",
    "09.10.2020",
    "2,84 USD",
    "02",
    "Fondsertrag (Ausschüttung)",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "08.10.2020",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "15.09.2020",
    "0,671205",
    "70,59 USD",
    "14.09.2020",
    "1,186900",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Fondsumschichtung (Zugang)",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "11.09.2020",
    "0,515934",
    "70,89 USD",
    "10.09.2020",
    "1,182900",
    "EUR/USD",
    "30,98 EUR",
    "Seite",
    "1 von",
    "1"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/afd52ae9

---
Issue submitted with https://import.tresor.one

**Comment by SirGibihm** [comment]
Wow there is quite an issue here: The transaction `Wiederanlage Fondsertrag` takes a dividend in a foreign currency (here USD) and reinvests this automatically. No conversion rate is given at all so we can't parse this transaction really. My best workaround here ist to make it a `TransferIn` transaction but this would is no correct representation either. @dredav do you have any idea on how to handle this?

**Comment by SirGibihm** [comment]
@dredav Friendly reminder, PR #341 will solve a lot of the issues that are reported to us but we can't finish it until the issue above is handled in some way

**Comment by dredav** [comment]
Sorry @SirGibihm, I've got to much github notifcations regarding all the new issues... I need to adjust the notifications settings.

The best idea I have is to create the `Wiederanlage Fondsertrag` as an `USD` activity and the other one as `EUR`. T1 Core need to convert the amount/price with the fx rate of the transaction date. But I'm not sure if that is possible (and I'm sure it's not supported yet).

How can we implement this without the `USD` activity... Currently I have no good idea... 😐 I will think about it...

**Comment by codeofsumit** [comment]
Don't get stuck on this. It's a very difficult edge case. For now, the user can create a Buy activity manually for this part. Return a fail on that dividend-reinvest if possible

**Comment by SirGibihm** [comment]
@dredav @codeofsumit I have it fail silently now. Not sure if this is what we want... This bears the risk of users not noticing something went wrong so if you want it to fail loudly, please tell me! The workaround also includes hardcoding `EUR` which is also bad. But I don't see any nice solution at all.

**Comment by codeofsumit** [comment]
We should never fail silently IMO. As we talked on our last hangout, it should at least tell T1 that there was an error so we can show the user that the activity is being ignored.
I'm not sure if this poses a problem on PDFs with multiple activities in them where some succeed and some fail 🤔

**Comment by SirGibihm** [comment]
Yep, I  think you are right. Have it fail loudly now.
