### ISSUE TITLE
[hbh] - New Broker - PDF only broken character

### ISSUE THREAD

**Issue by fhavellant** [codeofsumit/tresor-import#378]
Hello,

![image](https://user-images.githubusercontent.com/29174141/101357808-3d548380-389a-11eb-871d-f487dfbb18ab.png)
please check the corresponding image. I wanted to start the import parser for the HVB depot.
Appearantely i only get such broken characters while analyzing that.
In this case this will not work, right?
or am i doing something wrong?

Bye,
Florian

**Comment by SirGibihm** [comment]
Hi Florian, welcome to the project and thank you for participating! It seems like the .pdf to json parsers fails at the document you posted. Could you validate, that the text wihin the .pdf file is stored as some kind of characters/strings and not as image data? E. g. can you copy-paste the information if you open the file using adobe reader?

**Comment by fhavellant** [comment]
Thanks for the quick information.
If copy text out of the PDF i simply get this: .# 8 $  ;    

Looks like that this is then image data.

**Comment by SirGibihm** [comment]
I don't think OCR will be an option for this as it needs to be run in a browser. Is there any other export (.csv, .xml) or sth similar you can use?

**Comment by fhavellant** [comment]
I don't find one. So this means we can conclude the task since there will be no further actions possible.

**Comment by SirGibihm** [comment]
I guess so. Sorry to say that :/ If more people request this issue, we will reopen and look for an alternative

**Comment by dredav** [comment]
One question @fhavellant: Do you have other documents from this bank / broker? Are all documents "without text"?
