### ISSUE TITLE
Fix Demo

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#4]
Demo funktioniert noch nicht weil ich pdfjs nicht mit Webpack zum laufen bekomme

**Comment by d-a-n** [comment]
I guess this can be closed now 👍

**Comment by codeofsumit** [comment]
True

**Comment by hija** [comment]
Kann es sein, dass erst einmal "npm run build" ausgeführt werden muss, bevor "npm start" verwendet werden kann? Zumindest hat es bei mir sonst nicht funktioniert...
Dann sollten wir die README nochmal anpassen :)

**Comment by codeofsumit** [comment]
Jo das kann sein danke für den Hinweis. Wir sollten `npm run build` einfach in den Start command mit aufnehmen

**Comment by codeofsumit** [comment]
kommt in #21 (auch wenns da nicht hingehört)

**Comment by hija** [comment]
Sorry, dass ich das nochmal aufmache. Ich versuche lokal ein wenig am Import zu arbeiten, aber der file watcher / webpack aktualisiert nicht automatisch. D.h. mein Workflow ist im Moment:

npm start -> Gucken ob was funktioniert.
Falls nicht: Prozess beenden und neustarten.

Das dauert ziemlich lang. Ich kenne es so, dass ein watcher automatisch den Server neustartet bzw. das Asset neulädt, sobald eine Änderung erkannt wird. Das klappt leider bei mir nicht. Kann mir jemand Hinweise geben, wie ich das bei Windows 10 einrichten kann?

**Comment by codeofsumit** [comment]
@hija ein watcher ist drin aber kein Hot-Reload. Mit npm start werden die Dateien neu compiled aber die Seite musst zu trotzdem nochmal kurz neu laden.
