### ISSUE TITLE
Wrong Date in Trade Republic PDF?

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#42]
Von einem User:

> bei den Dividendenzahlung von TradeRepublic ist mir aufgefallen, dass diese dem ex-Div.Tag zugeordnet werden und nicht Valuta. Das sollte noch angepasst werden. 

cc @zirkler

**Comment by zirkler** [comment]
Werde ich die Tage mal angehen, mir ist jedoch nicht ganz klar, wieso das eine Datum sinnvoller als das andere ist, kannst du mir das vielleicht erklären?

**Comment by codeofsumit** [comment]
Hi @zirkler, klar.
Das Ex-Dividend Date ist der Tag, an dem man eine Aktie haben muss, damit man die Dividende bekommt. Üblicherweise der Tag der Hauptversammlung.

Beispiel:

Du kaufst Daimler am 01. Mai
Hauptversammlung ist am 15. Mai
Ex-Dividend Tag am 16. Mai
Dividenden Ausschüttung am 01. Juni

Du bekommst die Dividende, weil du vor dem Ex-Dividend Tag gekauft hast. Hättest du am 20. Mai gekauft, hättest du die Dividende nicht bekommen.
In den Tresor Aktivitäten soll das Transaktions-Datum - also den Tag an dem du die Ausschüttung bekommen hast, eingetragen werden. Deshalb ist das Ex-Dividend-Date für T1 Transaktionen irrelevant.

Hoffe das hilft 👍

**Comment by codeofsumit** [comment]
FYI Im Branch #48 ist das wohl auch gefixt - ggf kann man das einfach in nen eigenen Branch ziehen?
