### ISSUE TITLE
[Roadmap] General Issues and discussions

### ISSUE THREAD

**Issue by SirGibihm** [codeofsumit/tresor-import#441]
@dredav @carstenhag @codeofsumit 
This issue serves as a place to collect what bigger things are on our roadmap, maybe a place where we can define how we want to treat things. Please feel free to comment on further roadmap-things, I will extend this list.
## PDFs regarding stock-splits (e. g. Tesla)
I talked to Sumit about this and we came to the agreement, that stock splits are NOT to be parsed by Tresor Import. Sumit plans to create another tool for the community where they can notify about such splits. We decided against a Tresor Import function that handles this as the importer is supposed to focus on its core business: Handling everything regarding importing data to the users depot

## Further activity types
As stated in the README, we currently have the transaction types:
* `Buy`
* `Sell`
* `Dividend`

This will be extended by `TransferIn` and `TransferOut`. 

Furthermore, I suggest we also add the category `cancellation`(storno) that undos a previous transaction, see #437. For the moment I will parse this as a `Sell`but this will confuse the FIFO ordering of stock buys- and sells. @codeofsumit We would have to talk to you about this regarding the backend. Alternatively we can just tell the user to delete the activity, that has been cancelled.
## Depot Overview Import
Currently we have a mixmash on how we handle depot overviews. Most of them are parsed as `Buy` which is not entirely true. I would prefer yet another type of activity to be implemented  (`depotOverview`) as `TransferIn` is something different as well. The reason why I suggest another type of activity is that the user can easily see in the UI what he imported when. If everything is a `Buy`or transfer in but you want to edit previous acitivities (maybe because of an error) you need clear identification of the activities.

## Better user feedback
The user should be notified more about what happend to the import. A status message could be returned by the activity, that informs the user what happened. E. G. for the cancellation activities above: It could return: "This is a Storno File which should not be imported. Go to the activity that got cancelled and delete it from your depot."

**Comment by dredav** [comment]
Should we move the dicussions to [discussions](https://github.com/codeofsumit/tresor-import/discussions/new)?

**Comment by SirGibihm** [comment]
Absolutely, no Idea why I did not do that in the first place.
