### ISSUE TITLE
Beleg wird nicht eingelesen

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#459]
## Description
> erkennt wohl die Bank  nicht..

LG Stefan (Fuchs)

Schönen 3. Advent!

## Document
<details><summary>416    35 Daimler VK 202637510_2020_Abrechnung_vom_11.12.2020_20201212041526.pdf</summary><p>

```json
[
  [],
  []
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by SirGibihm** [comment]
The user submitted the original .pdf to me. Sadly, it was a .pdf without text information but instead text in image format which explains the empty arrays; there just are no strings in this .pdf. (maybe a scan). We cannot do anything here thus closed. The user has been informed about this.
