### ISSUE TITLE
Erste Bank Support

### ISSUE THREAD

**Issue by thomasschuiki** [codeofsumit/tresor-import#47]
Bin selbest bei dieser Bank und würde beginnen [hier](https://github.com/thomaseitler/tresor-import) einen Parser zu schreiben.

https://www.erste-am.at

**Comment by codeofsumit** [comment]
@thomaseitler cool! Einfach dieses Repo forken:
https://github.com/codeofsumit/tresor-import

In der README steht wie du starten kannst. Wenn du fragen hast, einfach hier fragen :)

**Comment by thomaseitler** [comment]
Bin schon mitten drin ;)
Bei den PFDs hab ich derzeit nur meine eigenen also Buys und Dividends.

**Comment by codeofsumit** [comment]
Yeah 💪  - ich hab leider noch PDFs zur Erste bekommen. Falls sich das ändert sag ich Bescheid!

**Comment by dredav** [comment]
The implementation is merged in #190. Release for T1 is comming soon!
