### ISSUE TITLE
Lets remove "npm audit" from the precommit hook

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#61]
The precommit adds `npm audit` which results in errors that can't be fixed. I had several thousand `low` vulnerabilities for which no fix was available even after `npm update`.
I have removed the audit check for now from precommit so it doesn't block development.

Github will warn us directly in the repo about dependency vulnerabilities anyway.

What are your thoughts on this?

**Comment by d-a-n** [comment]
Is `audit` part of you build pipeline? I would really advise to keep it in. It's impossible to keep track of issues manually.

Can't we just increase the level to moderate or high?

> npm audit --audit-level=high

**Comment by codeofsumit** [comment]
@d-a-n good point - that would also work for me. Can you create a PR with this change?

**Comment by dredav** [comment]
The other option is to add [dependabot](https://github.com/marketplace/dependabot-preview), but I will prefer the native `npm audit`
