### ISSUE TITLE
[comdirect] Parse Tax PDF

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#63]
comdirect liefert Steuerinfos in separaten PDFs.
Diese sollten wir der Vollständigkeit ebenfalls parsen können damit comdirect Kunden ebenfalls Steuerinfos zu ihren Aktivitäten finden.
Das ist aber ein bisschen Tricky, da die Steuerinfo hier einer bereits vorhandenen Aktivität zugeordnet werden muss.

Hat jemand Ideen wie wir das machen können? Die Steuer und die Abrechnung muss ja nicht im selben Schwung importiert werden 🤔

**Comment by dredav** [comment]
Ich denke, es ist kein Problem. Auf jeder Abrechnung von comdirect steht der Hinweis:
> Information zur steuerlichen Behandlung dieses Geschäftsvorganges und den auf Ihrem Konto gebuchten Endbetrag finden Sie auf der separaten Steuermitteilung (Referenz-Nr. 1234ABCD).

Auf der jeweiligen Steuermitteilung ist ebenfalls oben Referenz-Nr. aufgebracht (oben rechts):
>Referenz-Nummer: 1234ABCD

**Daher mein Vorschlag:**
Jede Activity erhält die Property `TransactionId`. Aktuell wird diese bei comdirect mit der Referenz-Nr. gefüllt und ist bei anderen Brokern leer. Nach dem Erzeugen einer Activity mit einer TransactionId wird bei T1 geprüft, ob bereits eine Activity mit der gleichen `TransactionId` vorhanden ist und diese dann gemerged (also es müssen entweder die Tax-Werte übernommen werden, oder alle anderen Werte ohne Tax - je nach dem ob zuerst das Steuerdokument oder die Abrechnung importiert wurde).

Wird nur eines der beiden Dokumente importiert, fehlen die restlichen Werte. T1 könnte natürlich auch sicherstellen, dass eine Activity mit `TransactionId` und `Company` vorhanden sein muss. So hätte man keine "Nur Steuer-Activity-Leichen".

Ich kann das ganze im Import umsetzten.

**Comment by martinseener** [comment]
Wie sieht es denn mit Steuerbescheinigungen aus, wo nur eine Quellensteuer bezahlt wird? Momentan müsste ich die manuell umrechnen von USD in EUR und dann bei Gebühren der Dividende hinzufügen?

**Comment by codeofsumit** [comment]
> Wie sieht es denn mit Steuerbescheinigungen aus, wo nur eine Quellensteuer bezahlt wird? Momentan müsste ich die manuell umrechnen von USD in EUR und dann bei Gebühren der Dividende hinzufügen?

Meiner Erfahrung nach stehen die Euro Beträge ebenfalls in diesen PDFs inklusive Umrechnungskurs. 
Hast du eine PDF in der NUR der Dollar Wert angegeben ist?

**Comment by martinseener** [comment]
> > Wie sieht es denn mit Steuerbescheinigungen aus, wo nur eine Quellensteuer bezahlt wird? Momentan müsste ich die manuell umrechnen von USD in EUR und dann bei Gebühren der Dividende hinzufügen?
> 
> Meiner Erfahrung nach stehen die Euro Beträge ebenfalls in diesen PDFs inklusive Umrechnungskurs.
> Hast du eine PDF in der NUR der Dollar Wert angegeben ist?

Habe das nochmal am Beispiel LTC Properties (comdirect) geprüft. Da nennt sich die Datei `Ertragsgutschrift_18000_St._WKN_884625(LTC_PTIES_INC._____DL-01)_vom_30.04.20203D0372.pdf`

Dort gibts also den Ertrag und die 15% Quellensteuer in USD und dann wird der tatsächliche EUR Ertrag einmal mit dem aktuellen Kurs umgerechnet. Weiß jetzt leider nicht, ob/wo ich das eintragen sollte oder ob das beim Steuerimport - falls da mal was kommt - wichtig ist.
Am Ende sinds ja Kosten die man gegen rechnen muss auch wenn man diese Steuer teilweise wiederbekommt.

![Screenshot from 2020-07-19 14-30-08](https://user-images.githubusercontent.com/1584417/87874729-6ef0af00-c9cc-11ea-9490-148fbda9d22a.png)

**Comment by dredav** [comment]
Die Quellensteuer (bei Dividenden) werden in T1 bisher nicht erfasst - meineswissens bei allen Brokern. Bei Verkauf fällt Quellensteuer glaub nicht an. In meinen Augen ist das auch soweit richtig, da die Steuer ja "vor" (also noch z.B. in US) der Dividende "gezahlt" wird - aber man könnte die Quellensteuer natürlich auch zu den anderen Steuern wie Kapitalertragsteuer, Solidaritätszuschlag und Kirchensteuer (+ andere ausländische Steuern) hinzufügen.
Die Quellensteuer selbst steht jedoch nur in der Abrechnung und nicht in der Steuermitteilung von comdirect. In der Steuermitteilung von comdirect sind bei mir alle Beträge (bisher) in Euro ausgewiesen.

**Comment by dredav** [comment]
Laut einem Benutzer aus der [Community](https://community.tresor.one/c/help/comdirect-import) stehen auf der zweiten Seite einer Abrechnung (ich vermute bei Käufen und Verkäufen) die aktuell gezahlten Steuern. Hier könnte man beide Seiten bei dem Import betrachen.

**Comment by codeofsumit** [comment]
@dredav @SirGibihm die Steuerabrechnungen für Dividenden könnten wir als ganz normale Dividenden Aktivitäten importieren. Da stehen ja alle Infos drin (inkl Steuern). Dann kann der User ENTWEDER die Ertragsgutschrift ODER die Steuermitteilung importieren

**Comment by SirGibihm** [comment]
Ein Beispiel hierfür findet sich in meinem aktuellen PR https://github.com/codeofsumit/tresor-import/pull/215/commits/b2b95eabb59503f4cef0b69f8f27acadc1ffe114 Hier habe ich den Weg beschritten schlicht array.flat() aufzurufen und alle Steuern aus einem Verkaufsdokument zu parsen.
