### ISSUE TITLE
[comdirect] Kosteninformation Kauf 10 St. WKN A1EWWW vom 25.09.2019

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#655]
## Description
> Kosteninformation Kauf 10 St. WKN A1EWWW vom 25.09.2019

## Document
<details><summary>Kosteninformation_Kauf_10_St._WKN_A1EWWW_vom_25.09.201930B0E2.pdf</summary><p>

```json
DELTED AS REQUESTED
```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by gonzotp1** [comment]
Please delete this document

**Comment by gonzotp1** [comment]
thank you

**Comment by SirGibihm** [comment]
> Please delete this document

@gonzotp1 Document has been fully deleted. If you opened this issue: Kosteninformation files are not parsed by Tresor One as they are not the actual bills for the stock/etf/whatever. This will be shown on the website in the future. Closing the issue
