### ISSUE TITLE
[Trade Republic] Import-Problem - Verkauf

### ISSUE THREAD

**Issue by Grimmy1st** [codeofsumit/tresor-import#70]
Import des Verkauf-PDFs via Trade Republic funktioniert scheinbar nicht - "Diese Datei wird nicht importiert"
[Verkauf Trade Republic_geschwärzt.pdf](https://github.com/codeofsumit/tresor-import/files/4919285/Verkauf.Trade.Republic_geschwarzt.pdf)

**Comment by codeofsumit** [comment]
Hi @Grimmy1st, danke fürs reporten. Geschwärzte PDFs verändern leider die Datenstruktur.
Üblicherweise lassen wir den Import lokal laufen, ziehen das `contents` array das bei deinem PDF Import in der Konsole geloggt wird und posten das hier - mit allen persönlichen Daten durch `XXX` ersetzt.

Damit haben wir die korrekte Datenstruktur zum testen, ohne deine Daten irgendwo zu veröffentlichen.

D.h. am Besten holst du dir das Repo mal lokal und lässt es laufen 👍

**Comment by dredav** [comment]
Hallo @Grimmy1st 
Du hast die `Kosteninformation` von TradeRepublic und nicht die `Abrechnung` versucht zu importieren. Aktuell wird jedoch nur die `Abrechnung` unterstützt, welche in der Regel einige Stunden nach der Kosteninformation von TradeRepublic bereitgestellt wird.

**Comment by Grimmy1st** [comment]
Okay, mea cupla - kann geschlossen werden.
