### ISSUE TITLE
comdirect Wertpapierkauf PDF Import ignoriert Tradeplatform/Ausführungsplatz

### ISSUE THREAD

**Issue by martinseener** [codeofsumit/tresor-import#75]
Erstmal vielen Dank für T1. Ein sehr cooles Tool und leichter zu benutzen als PP. Weiter so!

Mir ist heut beim Import meiner Wertpapiere ein Bug ins Auge gesprungen. Beim Import der comdirect PDFs z.B: `Wertpapierabrechnung_Kauf_20_St._WKN_850001(ERICSSON_B_(FRIA))_vom_26.05.20201D259F.pdf` oder `Wertpapierabrechnung_Kauf_015_St._WKN_LYX0AG(LYX.MSCI_WORLD_U.ETF_D)_vom_15.01.2020B9386C.pdf` nimmt er korrekterweise alle Werte soweit heraus, aber der Importer ignoriert den Ausführungsplatz bzw. die Tradeplattform.
Wenn ich mir die Papiere im T1 nachher anschaue, sind alle im Handelsplatz Frankfurt gekauft, was natürlich dann falsche Werte macht. Meine Wertpapiere sind im Wert alle +/- einige Cent Unterschied zum eigentlichen Wert.
Außerdem fehlen noch Handelsplätze wie `GETTEX` oder `QUOTRIX`.

1. Hinzufügen fehlender Handelsplattformen
2. Auslesen der richtigen Platform aus PDF und Berücksichtigung beim Anlegen des Wertpapiers

Weiterhin ist mir grade beim manuellen Ändern der Plattform meiner Wertpapiere aufgefallen, das die Werte einiger Plattformen (XETRA, Stuttgart) nicht angerufen werden kann (siehe Fehlerimage).

Vielen Dank für die Hilfe

Anhänge:
![ericsson](https://user-images.githubusercontent.com/1584417/87874001-7f9e2680-c9c6-11ea-9e1f-2a7dbe2372de.png)
![ericssont1](https://user-images.githubusercontent.com/1584417/87874003-82008080-c9c6-11ea-95a3-d07861e5ce40.png)
![msciw](https://user-images.githubusercontent.com/1584417/87874004-8462da80-c9c6-11ea-93b5-bd2699eb7a7d.png)
![msciw1](https://user-images.githubusercontent.com/1584417/87874005-862c9e00-c9c6-11ea-9da1-97f6b7b2f28f.png)
![preisfehler](https://user-images.githubusercontent.com/1584417/87874008-87f66180-c9c6-11ea-91ad-a8ce1a574131.png)

**Comment by codeofsumit** [comment]
Hi Martin,

Der Ausführungsplatz ist für das Anlegen einer Aktivität irrelevant. 

Der Ausführungsplatz ist nur wichtig für das Laden der Kurse was komplett unabhängig von deinen Aktivitäten ist und mit dem Import auch nix zutun hat. 

Du kannst ja das gleiche Wertpapier an 10 verschiedenen Börsen kaufen, für deine Performance Berechnung ist nur wichtig welchen Preis du gezahlt hast (völlig egal wo) und mit welchem Preis du das vergleichst (Aktueller Kurs, hier ist der Handelsplatz den du wählst wichtig). 

Bei T1 (und anderen Tools) wählst du in den Holding Einstellungen also aus, von welchem Handelsplatz die Preise genommen werden sollen - und dagegen wird dann deine Performance berechnet. 
Man könnte theoretisch den default Wert aus den PDFs auslesen beim Import der ersten PDF - ist aber viel Aufwand für nen kleinen Benefit. Nehm ich aber mal mit auf 👌. 

Wir arbeiten aktuell an einem Update für die Handelsplätze - so dass wir in Zukunft noch mehr unterstützen. 

Da das aber nichts mit dem Import hier zutun hat, schließe ich die Issue wieder.

**Comment by codeofsumit** [comment]
Ach so, und dass die Kurse beim ändern des Handelsplatzes nicht geupdated werden ist ein Bug. Den fixen wir aktuell - hat mit Caching zutun. Cc @felixheck

**Comment by martinseener** [comment]
Hallo Sumit,
vielen Dank für die schnelle Reaktion und deine Erklärung macht jetzt für mich auch total Sinn ;-) Danke dir!
Vielleicht wäre es dann ne gute Idee, wenn man seine "Detault" Handelsplattform im Profil hinterlegen könnte, mit welchem man die aktuellen Kurse vergleichen möchte? Ich glaube bei der comdirect ist das Tradegate. Was denkst du dazu?
