### ISSUE TITLE
[Trade Republic] Brutto-Dividende, Steuer und Währungsproblem

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#85]
![image](https://user-images.githubusercontent.com/2399810/89257388-53b9ac80-d626-11ea-97f6-bcd016498ad2.png)
![image](https://user-images.githubusercontent.com/2399810/89257396-57e5ca00-d626-11ea-868b-b7ef4b8b3aca.png)

Folgendes Problem bei dieser Abrechnung:

a) Die Steuer die ausgelesen wird ist falsch - Quellsteuer fehlt
b) Quellsteuer ist nicht in Euro angegeben
c) Brutto-Dividende sollte eigentlich der "Amount" sein, aber die gibt es auch nur in USD 🤔

Wie lösen wir das? Ggf muss mutli-währung asap kommen 🤯

Falls wir mehrere Währungen supporten würden, müsste der Import für TR aber den oberen Betrag (10,29 USD) auslesen. Was denkt ihr?

Hier das Array
```js
[
  [
    "TRADE REPUBLIC BANK GMBH",
    "KASTANIENALLEE 32",
    "10435 BERLIN",
    "XXXX XXXX XXXX",
    "XXXXXXXX",
    "D 61197 XXXX XXXX",
    "SEITE",
    "1",
    "von",
    "1",
    "DATUM",
    "03.08.2020",
    "DEPOT",
    "XXXXXXXX",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "service@traderepublic.com",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "ABRE / 2020-08-03 / XXXX / 510a-XXXX",
    "DIVIDENDE",
    "ÜBERSICHT",
    "Dividende mit dem Ex-Tag 09.07.2020.",
    "POSITION",
    "ANZAHL",
    "ERTRÄGNIS",
    "BETRAG",
    "General Mills Inc.",
    "Registered Shares DL -,10",
    "ISIN: US3703341046",
    "21 Stk.",
    "0,49 USD",
    "10,29 USD",
    "GESAMT",
    "10,29 USD",
    "ABRECHNUNG",
    "POSITION",
    "BETRAG",
    "Quellensteuer DE für US-Emittent",
    "-1,54 USD",
    "Zwischensumme",
    "8,75 USD",
    "Zwischensumme",
    "1,1775 EUR/USD",
    "7,43 EUR",
    "Kapitalertragssteuer",
    "-0,88 EUR",
    "Solidaritätszuschlag",
    "-0,05 EUR",
    "GESAMT",
    "6,50 EUR",
    "BUCHUNG",
    "VERRECHNUNGSKONTO",
    "VALUTA",
    "BETRAG",
    "XXXXXXXX",
    "03.08.2020",
    "6,50 EUR",
    "General Mills Inc. Registered Shares DL -,10 in Girosammelverwahrung.",
    "Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.",
    "Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie",
    "Leistung."
  ]
]

```

**Comment by dredav** [comment]
Das Problem besteht aktuell meines Wissens bei allen Brokern, die von T1 unterstützt werden. Bisher werden Quellensteuer immer in der Ursprungswährung angegeben, daher kommt man (falls man die Quellensteuer nicht ignoriert) nicht um den Währungssupport herum.

Ich persönlich kann mich damit auch anfreunden, wenn man Quellensteuer ignoriert.

Von der EZB gibt es eine Liste mit "offiziellen" Umrechnungskursen, welche via API abgerufen werden könne: https://exchangeratesapi.io/

**Comment by dredav** [comment]
Man könnte sonst aber auch die Berechnung umstellen: `tax = amount - shares * price - fee`. Ich habe mir das bisher noch nicht genau angeschaut, aber das müsste bei allen Broken gehen.

Vorteil von dieser Lösung:
- Dividende in Brutto
- Steuern werden komplett erfasst, auch wenn diese uns nicht bekannt sind (z.B. ausländische Finanztransaktionssteuer)
- Die Problematik mit den Währungsumrechnungen sind gekonnt vertagt

**Comment by carstenhag** [comment]
mMn sollten Quellensteuern ignoriert werden. Es gibt ja eh noch die Teilfreistellung je nach Fonds-Art, und die ist viel wichtiger da sie ja vom Wohnland abhängt.
