### ISSUE TITLE
[ING] Missing tax support for dividend statements

### ISSUE THREAD

**Issue by dredav** [codeofsumit/tresor-import#87]
We don't have statements with taxes of dividend from ING. Can anyone provide some of these?

**Comment by wrelix** [comment]
Just sent some to Sumit

**Comment by dredav** [comment]
Hi @wrelix, you can also provide the documents with the new [submit tool](http://import.tresor.one). Select the document(s), anonymize them and add a simple description. The Tool will create a new Issue and after that, I will close this one. The new progress is less time-consuming for Sumit.

**Comment by wrelix** [comment]
@dredav ok, done!

**Comment by dredav** [comment]
@wrelix Thanks! I'll look into it in the next days. I close this issue and we can continue in the [issue](https://github.com/codeofsumit/tresor-import/issues/112) you created with the submit tool.
