### ISSUE TITLE
Example PDFs for import

### ISSUE THREAD

**Issue by ewoks** [codeofsumit/tresor-import#91]
Would it make sense to add few small example PDFs for importing (1 per supported provider)?

**Comment by carstenhag** [comment]
Not sure what you mean. Could you perhaps explain further what you mean?

In the repo, under the tests folder, you can find the "scanned" PDFs as `.json` files.
See for example https://github.com/codeofsumit/tresor-import/tree/master/tests/brokers/__mocks__/ing.

**Comment by ewoks** [comment]
I actually missed `.json` files per provider (ing, consor, etc..) before.
Not sure if all supported providers are there (i.e. didn't find comDirect).. Thanks for clarifying this

**Comment by carstenhag** [comment]
Ah okay, I see. I guess @codeofsumit or someone else just didn't add comdirect tests. Would be cool to include them though!

**Comment by dredav** [comment]
Yes, for comdirect there are currently no tests available. #88 is adding basic tests for buy and dividends. Please feel free to add your own document dumps as json file and the related tests or send the pdf documents to @codeofsumit sumit@tresor.one. On the community page you can see all the missing documents: https://community.tresor.one/c/help/der-automatische-import-benotigt-deine-hilfe-um-noch-besser-zu-werden

**Comment by dredav** [comment]
@ewoks Can we close this issue? The PR for comdirect tests was merged and with #146 we get the first tests for `Postbank`. Do you have some bank documents which are currently missing? You can provide them with our submit document tool which allows you to anonymize the document content.

**Comment by ewoks** [comment]
@dredav it is fair to close it. Thanks once again
