### ISSUE TITLE
DKB Bug gemeldet im Forum

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#946]
## Description
> Mein Sparplan wird nicht erkannt.

Der Import dauert sehr lange, irgendwann passiert nichts mehr, wenn ich dann die Seite neu lade, taucht die im Forum gezeigte Position im Depot auf.

https://community.tresor.one/c/help/bug-portfolio-aktivitaten-von-1970

## Document
<details><summary>Fondssparpläne_vom_31.12.2020_zu_Depot_505743724_-_Sammelabrechnung_505743724-3.pdf</summary><p>

```json
[
  [
    "10919 Berlin",
    "Elqxw",
    "Zcmxu Mwodhbduic",
    "Gwcbnzifa 3",
    "95921 Wunmyir",
    "Xooijmmgvpf",
    "765145186",
    "Srxumzatoueu",
    "8937151790",
    "Jxcoj Psrpwmtusx",
    "Datum",
    "31.12.2020",
    "Vertragsbeginn",
    "37.79.5678",
    "Khcvqhxsbqlw",
    "c.i.e.",
    "Sparplannummer",
    "3",
    "Iydonyopxowe-RX",
    "CG502959435",
    "6858.37276880.1933227WS30",
    "Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.",
    "Halbjahresabrechnung Sparplan",
    "Wertpapierbezeichnung",
    "ISIN",
    "(WKN)",
    "ISHS IV-ISHS MSCI EMIMI ES ETF",
    "REG. SHARES USD ACC. O.N.",
    "IE00BFNM3P36",
    "(A2N6TH)",
    "Im Rahmen Ihres bestehenden Sparplans haben wir vereinbarungsgemäß nachstehende Käufe außerbörslich für Sie",
    "durchgeführt.",
    "Die Gegenwerte haben wir Ihnen belastet und die erworbenen Stücke Ihrem Depotkonto gutgeschrieben.",
    "(Wertpapierrechnung Lagerland Irland)",
    "Umsatzart",
    "Sparrate in",
    "EUR",
    "Ordernummer",
    "Preis je Stück",
    "in EUR",
    "Devise",
    "Anteilsumsatz",
    "in Stück",
    "Schlusstag",
    "Valuta",
    "Zwischengewinn",
    "in EUR",
    "Steuerausgleich",
    "in EUR",
    "Kauf",
    "75,00",
    "604955/89.00",
    "5,4911",
    "1,0000",
    "13,6583",
    "21.12.2020",
    "23.12.2020",
    "0,00",
    "0,00",
    "+ Provision",
    "1,50",
    "Summe",
    "76,50",
    "Im Abrechnungszeitraum angelegter Betrag",
    "EUR",
    "75,00",
    "Im Abrechnungszeitraum erworbene Anteile",
    "Stück",
    "13,6583",
    "Durchschnittspreis der erworbenen Anteile",
    "EUR",
    "5,49",
    "Evtl. anfallende Erträge werden Ihnen mit separater Abrechnung vergütet. Für evtl. Bestandsveränderungen aus",
    "zusätzlichen Käufen oder Verkäufen haben Sie separate Abrechnungen erhalten."
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/8873bc0f

---
Issue submitted with https://import.tresor.one

**Comment by roscha444** [comment]
Mein Dokument wird hier in der DemoPage richtig verarbeitet

![grafik](https://user-images.githubusercontent.com/33632422/104120603-57b9cb00-5338-11eb-9392-caf75839c3ed.png)

Wenn ich das Dokument in TresorOne hochlade, lädt der Import dauerhaft bis ich die Seite aktualisiere

![grafik](https://user-images.githubusercontent.com/33632422/104120614-699b6e00-5338-11eb-9ed1-304c94eca170.png)

Dann finde ich diese Position

![grafik](https://user-images.githubusercontent.com/33632422/104120622-7ae47a80-5338-11eb-9b2e-96eee11f5ebb.png)

**Comment by SirGibihm** [comment]
Ich glaube es liegt daran, dass wir hier einen Bug gefixt haben, der noch nicht im Release gelandet ist. Sumit hat grade 10.01.2020 19:30 einen Release gemacht. Funktioniert es jetzt bei T1?

**Comment by roscha444** [comment]
> 
> 
> Ich glaube es liegt daran, dass wir hier einen Bug gefixt haben, der noch nicht im Release gelandet ist. Sumit hat grade 10.01.2020 19:30 einen Release gemacht. Funktioniert es jetzt bei T1?

Fehler tritt nicht mehr auf. Wird ordnungsgemäß importiert.

**Comment by SirGibihm** [comment]
Ok perfekt, mache das Issue hier dann zu
